### ISSUE TITLE
add a callback to allow filtering of incoming connections by IP address

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#2558]
We should be able to reject connection attempts from blacklisted IP addresses.

Ideally, we'd be able to send a CONNECTION_CLOSE with a special error code for this, to allow the client to recognize that they've been blocked (and that there's no point in trying again any time soon).

**Comment by roz3x** [comment]
hi , would this kind of implimentation work ?
```go

func (s *baseServer) handlePacketImpl(p *receivedPacket) bool /* should the buffer be released */ {
        // If we're creating a new session, the packet will be passed to the session.
        // The header will then be parsed again.
        hdr, _, _, err := wire.ParsePacket(p.data, s.config.ConnectionIDLength)

        //if blocked ,  sending the connection close directly
        if isBlocked(p.remoteAddr) {
                if err := s.sendConnectionClosed( p.remoteAddr, hdr); err != nil {
                        s.logger.Debugf("Error closing connection: %s", err)
                }
               return false
        }

        ....
}


```

**Comment by marten-seemann** [comment]
Yes, something along those lines. A few thoughts:
1. It probably makes sense to only do this for Initial packets.
2. It should use the CONNECTION_REFUSED error.

The tricky thing here is getting the API right, and I'd like to hear @lucas-clemente's opinion on this:
We could add a callback to the `quic.Config`: 
```go
AcceptConnection func(net.Addr) bool
```
or maybe the other way round:
```go
RejectConnection func(net.Addr) bool
```

**Comment by roz3x** [comment]
thanks for the suggestions ;  just a doubt ,  should we even quic-parse the packet if it is from a banned ip ?

**Comment by marten-seemann** [comment]
Summarizing the conclusion we arrived at back then (can't find where): Using a special error code here is dangerous, as the peer might act upon this error code, and avoid dialing us back for a prolonged period of time. The problem is that this error code is sent in an Initial packet, i.e. unencrypted and unauthenticated. Injecting a CONNECTION_CLOSE using that error code would thus be an easy way for an attacker to prevent two peers from connecting.

**Comment by marten-seemann** [comment]
Turns out we already have this! It's called `quic.Config.GetConfigForClient`. This callback gets passed a `quic.ClientHelloInfo`, which has a `RemoteAddr` field.

I'm going to close this issue, since there's no need to introduce another config option with exactly the same functionality. I'm not even sure if there's anything left to do documentation-wise:
```go
	// GetConfigForClient is called for incoming connections.
	// If the error is not nil, the connection attempt is refused.
	GetConfigForClient func(info *ClientHelloInfo) (*Config, error)
```
If anybody is interested in improving the documentation, I'd be happy to review a PR.
