### ISSUE TITLE
How do I get the current max content size of Datagram Frame?

### ISSUE THREAD

**Issue by immysec** [quic-go/quic-go#3222]
```go
func (s *session) SendMessage(p []byte) error {
	f := &wire.DatagramFrame{DataLenPresent: true}
	if protocol.ByteCount(len(p)) > f.MaxDataLen(s.peerParams.MaxDatagramFrameSize, s.version) {
		return errors.New("message too large")
	}
	f.Data = make([]byte, len(p))
	copy(f.Data, p)
	s.datagramQueue.AddAndWait(f)
	return nil
}
```

The API just only return "message too large" error if the size of `p` exceed  the ` f.MaxDataLen()`. Caller is unable to know the current allowed `MaxDataLen`.

**Comment by marten-seemann** [comment]
You don't, as there's no way to tell the current MTU, and the MTU may change at any point in the connection.

**Comment by ydnar** [comment]
I think for WebTransport, H3 Datagrams, or QUIC Datagrams, it might be a good idea to eventually expose this on a `quic.Session`.

The WebTransport API defines an application-readable `maxDatagramSize`, which is the effective payload MTU of a WT datagram (QUIC datagram minus H3 and WT framing overhead).
