### ISSUE TITLE
Any benefits to use go rpc framework over QUIC?

### ISSUE THREAD

**Issue by Jeffwan** [quic-go/quic-go#3506]
Hi, I am new to QUIC and investigating whether QUIC is beneficial to Golang rpc framework? 

Do you know any uses cases to adopt `quic-go` ask the building blocks for RPC framework? Could you also share some insights on the benefits to use RPC over QUIC? Not sure if anyone did benchmark on QUIC vs TCP vs HTTP2 comparison?

**Comment by Davincible** [comment]
@Jeffwan  Nice article on RPC and QUIC; https://www.theregister.com/2022/10/07/quic_tcp_replacement/

**Comment by marten-seemann** [comment]
Closing this issue, since it sounds like the question has been answered.
