### ISSUE TITLE
http3: use the http.Server.ErrorLog if set

### ISSUE THREAD

**Issue by cipriancraciun** [quic-go/quic-go#3548]
In a previous version, `v0.28` if I'm not mistaken, there was a possibility to set `http3.Server.Server.ErrorLog = log.New (...)`.  However now as the `http3.Server.Server` fields have been merged into `http3.Server`, the `ErrorLog` is missing.

There seems to be a private `logger util.Logger` field that can't be overriden, so perhaps making that public?

**Comment by marten-seemann** [comment]
I don't we ever exposed a way to set the logger in previous versions.

**Comment by cipriancraciun** [comment]
> I don't we ever exposed a way to set the logger in previous versions.

It might be, I don't remember how it used to behave.

However, having a way to customize the logging, would be nice though.  And by "customizing the logging" I mainly mean having at least a way to get the `string` that would otherwise go to the default Go logger, and allow the developer do something else with it (like for example prefix it with something, transform it, ignore it, etc.)

Perhaps even something as simple as exposing `http3.Server.SetLogger (*log.Logger)` and making sure that reaches the actual logging call:
https://github.com/lucas-clemente/quic-go/blob/62b82789c0cc8a9acf48ee516ce2dd303253f395/internal/utils/log.go#L93

**Comment by marten-seemann** [comment]
Doesn't sound unreasonable. Want to submit a PR?

**Comment by marten-seemann** [comment]
This could simply make use of the `http.Server.ErrorLog`, if set. No additional quic-go API needed.

**Comment by marten-seemann** [comment]
#4449 will close this issue. I still see the appeal of reusing the logger on the `http.Server`, but we'd still need a solution for the non-error log messages. Maybe the standard library will add an `slog.Logger` to the `http.Server` at some point? Then we could reuse that one.
