### ISSUE TITLE
http3: sniff HTTP Content Type from first Write, analogous to http.ResponseWriter

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#3573]
This should be pretty straightforward change which can mostly be copied from the standard library HTTP implementation. See https://github.com/caddyserver/caddy/issues/5096#issuecomment-1268784887 for more discussion and links to code.

**Comment by Glonee** [comment]
Hello @marten-seemann, does this issue still need help? If so, would you please take a look at my PR?
