### ISSUE TITLE
moving quic-go to its own org: quic-go/quic-go

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#3611]
### Goal

Consolidate all quic-go related repos in a single GitHub org.

This will effect to following repos:

- [https://github.com/lucas-clemente/quic-go](https://github.com/lucas-clemente/quic-go)
- [https://github.com/marten-seemann/webtransport-go](https://github.com/marten-seemann/webtransport-go)
- [https://github.com/marten-seemann/qpack](https://github.com/marten-seemann/qpack)
- [https://github.com/marten-seemann/qtls-go1-19](https://github.com/marten-seemann/qtls-go1-19)
- [https://github.com/marten-seemann/qtls-go1-18](https://github.com/marten-seemann/qtls-go1-18)

### How

I created a test repo in https://github.com/marten-seemann/testrepo, that had issues, PRs, a wiki, a release. [Transferring a repo](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository) is really uncomplicated, GitHub moves the entire repository incl. all issues, PR, Wiki etc. It also creates a 301 forwarding to the new location.

**Open Question**: How long is this forwarding kept alive? Will links to issues (for example) still be redirected in a year from now? Will old releases still be available indefinitely (even when not using the Go module proxy)?

The interaction with Go toolchain is less frictionless, since the `go.mod` contains the import path. This means that although all releases are moved to the new location, it won't be possible to use them, since the Go toolchain doesn't allow import `github.com/quic-go/quic-go`, if that release declares itself to be `github.com/lucas-clemente/quic-go`. This means we'll have to cut a new release there, just to update the module path.

### Checklist 

- [x]  create new GitHub org: [https://github.com/quic-go](https://github.com/quic-go)
- [x] create the last quic-go release here. Include a deprecation notice (right above the package declaration both in the `quic` and in the `http3` package), pointing users to `quic-go/quic-go`. IDEs and tools like `staticcheck` will surface this to the user, as soon as users update to that version (via `go get -u`).
- [x] move over all dependencies, and create new releases at the new location with the updated module path in the respective `go.mod` files
- [ ] create a quic-go release in quic-go/quic-go, with the updated module path in `go.mod`
- [x] update OSS-fuzz paths: https://github.com/google/oss-fuzz/tree/master/projects/quic-go

### Timeline

Unless we encounter any blockers, we'll move this month.
I'll leave this issue open for a bit to give users time to comment. Pinging @mholt, @bt90, @AudriusButkevicius, @kokes, @tobyxdd, @hareku, @zllovesuki.

@mholt and @Jorropo, I believe you have recent experience moving repos. Does my plan look reasonable? Did I forget anything?

**Comment by alextran1502** [comment]
Your plan looks good. I think the forwarding might be permanent. I've switched over for a few months, and Github still forwards https://github.com/alextran1502/immich to the org's repo

The only thing I would test is the go packages since it uses GitHub namespace in the `go.mod`. I am not sure how this will be handled.

**Comment by mholt** [comment]
Yeah, forwarding is permanent unless a new repo is created again in the same place.

We moved repos before Go modules but the Go module proxy, for all who use it (it is the default), should have the old versions cached at the old path. Not sure about GitHub releases. I suspect they will still be available though.

Otherwise, all importers will need to manually update their go.mod files to use the new path. This part does kind of suck but is easy enough. I guess this is why some people use vanity module paths.

The Caddy project is ready and willing to update to the new path. 😊

**Comment by Jorropo** [comment]
@marten-seemann I didn't get if you plan to write a forward stub declaration in this repo (like you did for `go-libp2p-core`).

This is somewhat important as this creates less friction in the transition period.
If you do not do this, a transitive consumer that imports both the new and old repos would see them compiled twice, with possibly incompatible types.

**Comment by marten-seemann** [comment]
Good point @Jorropo! I wish we could create these forwardings, but I'm not sure how that would work. The problem is that the alias need to be completed _before_ the repo is moved. That means that `lucas-clemente/quic-go` will need to import `quic-go/quic-go`.

**Comment by Jorropo** [comment]
@marten-seemann why ?
You can move `lucas-clemente/quic-go` -> `quic-go/quic-go`, create a new `lucas-clemente/quic-go` repush the old tree but with a new forward release.
It will be broken for the period between when you recreate it and it is repushed.

**Comment by marten-seemann** [comment]
> @marten-seemann why ?
> You can move lucas-clemente/quic-go -> quic-go/quic-go, create a new lucas-clemente/quic-go repush the old tree but with a new forward release.

As @mholt said in https://github.com/lucas-clemente/quic-go/issues/3611#issuecomment-1303670914, the 301 forwarding that GitHub creates when transferring a repo, will only exist as long as there's no new `lucas-clemente/quic-go` created. This is crucial, since we want links to issues and PRs to be forwarded.

**Comment by bt90** [comment]
@marten-seemann could you pin this issue for better visibility?

**Comment by marten-seemann** [comment]
Just ran another test: It is indeed possible to cut a patch release for a package under to old module name after having moved the repo. Those versions are also covered by the forwarding that GitHub introduces.

**Comment by marten-seemann** [comment]
This also means that this step doesn't make sense:
> * [ ]  create the last quic-go release here. Include a deprecation notice (right above the package declaration both in the `quic` and in the `http3` package), pointing users to `quic-go/quic-go`. IDEs and tools like `staticcheck` will surface this to the user, as soon as users update to that version (via `go get -u`).

`go get -u` will just download the latest version, even if it's in the new repo.

**Comment by marten-seemann** [comment]
As a test, I just moved qpack to quic-go: https://github.com/quic-go/qpack
Looks like everything worked out fine: https://github.com/lucas-clemente/quic-go/pull/3638

**Comment by zllovesuki** [comment]
Now that the repo is migrated, should we a cut a new release along with all the reduce allocs improvements?

**Comment by marten-seemann** [comment]
> This is the error when trying to get from the quic-go org:
> 
> ```
> go get github.com/quic-go/quic-go@latest
> go: github.com/quic-go/quic-go@v0.31.1: parsing go.mod:
>         module declares its path as: github.com/lucas-clemente/quic-go
>                 but was required as: github.com/quic-go/quic-go
> ```

That's expected. For all existing versions, you'll have to use the old import path. That should work fine, as GitHub will handle the forwarding.

> Now that the repo is migrated, should we a cut a new release along with all the reduce allocs improvements?

Yes, but I'd like to resolve #3674 first, and, if I can figure out a race-free way of doing so, #3653.

**Comment by marten-seemann** [comment]
It's done! v0.32.0 is out!

**Comment by bt90** [comment]
The latest Github release still points to v0.31.1

**Comment by marten-seemann** [comment]
I still had to write the release notes. It's here now: https://github.com/quic-go/quic-go/releases/tag/v0.32.0
