### ISSUE TITLE
Disabling QUIC-go retransmission

### ISSUE THREAD

**Issue by YRoelvink** [quic-go/quic-go#3679]
Hi,
I am actually working in a setup where I am encapsulating another data stream inside the QUIC stream, and this encapsulated stream has its own retransmission module implemented. However, I suspect that the two retransmission modules are interfering with each other / slowing each other down, so I would like to do some tests where one of the two is disabled. Due to the nature of the system, I cannot change / disable the retransmission module of the encapsulated stream, so I would like to see if I can boost the performance of my implementation by disabling the quic-go retransmission and letting the other data stream handle the retransmission for now. 

I tried removing calls to the retransmission module (i.e. all refrences to `queueretransmission` and `*sendStream.retransmissionQueue` in `send_stream.go`), but I noticed no performance increase for now. Do you know if I can easily check whether the retransmission in quic-go is correctly disabled now, and if not, where I could disable it? Thanks in advance!

_Originally posted by @YRoelvink in https://github.com/quic-go/quic-go/issues/3296#issuecomment-1375362606_

**Comment by marten-seemann** [comment]
There's no way to disable retransmissions for stream data, unless streams are reset. Please refer to RFC 9000 for the rules on how frames are retransmitted.

If you want to send unreliable data, that's what DATAGRAM frames (RFC 9221) are there for. quic-go exposes an API to send and receive datagram frames.

**Comment by YRoelvink** [comment]
Ok perfect, I will have a look at the datagrams frames in that case! Thanks a lot
