### ISSUE TITLE
InvalidVersionNegotiationPacket when quic-client version is v0.10.1 and server version is v0.18.0

### ISSUE THREAD

**Issue by vincentgoat** [quic-go/quic-go#3692]
Hi, Community
May I ask if there is a way to do the compatibility BTW quic-client which version is v0.10.1 and the server which version is v0.18.0?
I got this error on the client side: 
`2023/02/03 16:20:15 client 	Long Header{Type: Initial, DestConnectionID: 0xd593f990597455e4, SrcConnectionID: (empty), PacketNumber: 0x6, PacketNumberLen: 4, Version: gQUIC 44}`

`muxer error handling packet from 127.0.0.1:4242: error parsing header: InvalidVersionNegotiationPacket`

And this error on the server side: 
`2023/02/03 16:20:15 server Client offered version gQUIC 44, sending Version Negotiation
`

As of now, both quic-client and quic-server version is 0.10.1 and we gonna upgrade the quic version to support the function of verifying the client's tls certificates on the server side. But we got the compatibility problem as above. Thinking of the case that deployments that have existing deployments of quic-go client and server that cannot be updated all at the same time.
In addition, we now use golang 1.17.

Are there any suggestions to do the upgrading?

**Comment by marten-seemann** [comment]
The client is using a gQUIC version. I'd assume that the wire format of the version negotiation packet is not compatible. You could look that up in the gQUIC specification.

**Comment by vincentgoat** [comment]
quic-go client has a constraint version list and will be verified when dialing
```
func IsValidVersion(v VersionNumber) bool {
	return v == VersionTLS || IsSupportedVersion(SupportedVersions, v)
}
```

SupportedVersions are totally different BTW v0.10.1 and v0.18.0

**Comment by marten-seemann** [comment]
The format of the Version Negotiation Packet is not compatible, therefore you'll get an error when trying to parse a gQUIC VNP: https://docs.google.com/document/d/1WJvyZflAO2pq77yOLbp9NsGjC1CHetAXV8I0fQe-B_U/edit#heading=h.b3fur3s2n43j
