### ISSUE TITLE
Consider not blocking the compilation of higher go version

### ISSUE THREAD

**Issue by imroc** [quic-go/quic-go#3701]
## Motivation

When a go package like [req](https://github.com/imroc/req) depends on quic-go, its requirements for the go version must be the same as quic-go. For v0.31.0, it only supports go1.17 to go1.19.

Consider this scenario: when go1.20 is released, the user of req upgrades the go version to go1.20, but finds that the previous project cannot be compiled: 

```txt
# github.com/lucas-clemente/quic-go/internal/qtls
../../../go/pkg/mod/github.com/lucas-clemente/quic-go@v0.31.0/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.20 yet. For more details, please see https://github.com/lucas-clemente/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.20 yet. F...) as int value in variable declaration
```

Most users do not use the http3 function, that is, the quic-go dependency will not be used in practice, but this will also cause the project to fail to compile. So user need to upgrade req and quic-go to support Go1.20 even if http3 is not used.

## Proposal

Don't restrict the go version in this way(compilation phase): https://github.com/quic-go/quic-go/blob/v0.32.0/internal/qtls/go121.go#L5

Check go version in runtime, and panic if the version is not supported.

**Comment by marten-seemann** [comment]
Panicking at runtime seems strictly worse than catching the problem at compile time.
