### ISSUE TITLE
How to determine whether connection is available ？

### ISSUE THREAD

**Issue by MonkeyBrothers** [quic-go/quic-go#3714]
hello I am a beginner. 

`listener, err := quic.ListenAddr(addr, generateTLSConfig(), nil)`
`conn, err := listener.Accept(context.Background())`

I want to know how  if it is available according to the connection status.
Is there any method that can be called？

**Comment by marten-seemann** [comment]
What is your question?

**Comment by MonkeyBrothers** [comment]
@marten-seemann 
Thank you very much for your reply.

I want to determine whether connection is available before writing or receiving data every time.
I have multiple clients corresponding to one server application scenario.
I want to manage these connections on the server side, and then send data to each client in a loop.
But I don't know how I should manage these connections and determine whether each connection is available.

**Comment by MonkeyBrothers** [comment]
Just like using netty
Use map to manage channel in business
Send data Use “channel.isActive” to determine whether data can be sent
