### ISSUE TITLE
Multipath QUIC

### ISSUE THREAD

**Issue by Zhiyong-Tsang** [quic-go/quic-go#3717]
Hello, everyone! I want to reproduce the work about Deceuninck, and I followed the tutorial in the link--" https://multipath-quic.org/2017/12/09/artifacts-available.html". Unfortunately, I could not install the quic-go with go version 1.9.2, 1.13.6, and 1.19.6. The errors I have met seems about the dependency package. Does anybody successfully install it? Could you please tell me which version of quic-go and go? I really appreciate any help you can provide.

**Comment by marten-seemann** [comment]
You'll probably need to ask the authors of that project.

**Comment by Zhiyong-Tsang** [comment]
Ok, thanks!
