### ISSUE TITLE
http3: use a single UDPConn in RoundTripper

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#3718]
In principle, you only need _a single_ UDP socket for _all_ of your QUIC connections. That's because QUIC can demultiplex based on the QUIC Connection ID.
In quic-go, this is achieved by not using `quic.DialAddr` (which will create and manage a `net.UDPConn` for you), but using `quic.Dial`, which takes a `net.UDPConn` as an argument. In the HTTP/3 package, we could create a single `UDPConn` per `RoundTripper`, and use that for all outgoing requests.

_Originally posted by @marten-seemann in https://github.com/quic-go/quic-go/issues/3716#issuecomment-1437832124_

**Comment by marten-seemann** [comment]
@khasanovbi, would you be interested in contribution a patch?

**Comment by Glonee** [comment]
Do we have to create a single `UDPConn` per `RoundTripper`? This requires us to pass `UDPConn` to dialer, and I think the only way to do that without breaking extisting API is passing it via context (just like what I did in my PR #3720 ).
But I think we can go further, that all `RoundTripper` use the same `UDPConn`. We can do it by implmenting a simple dialer and let `RoundTripper.Dial` use it by default:
```go
var (
	dialOnce sync.Once
	oneConn  *net.UDPConn
)

func dialer(
	ctx context.Context,
	addr string,
	tlsCfg *tls.Config,
	cfg *quic.Config,
) (quic.EarlyConnection, error) {
	dialOnce.Do(func() {
		oneConn, _ = net.ListenUDP("udp", &net.UDPAddr{IP: net.IPv4zero, Port: 0})
	})
	if oneConn == nil {
		return quic.DialAddrEarlyContext(ctx, addr, tlsCfg, cfg)
	}
	udpAddr, err := net.ResolveUDPAddr("udp", addr)
	if err != nil {
		return nil, err
	}
	return quic.DialEarlyContext(ctx, oneConn, udpAddr, addr, tlsCfg, cfg)
}
```
