### ISSUE TITLE
use the `netip` types for addresses

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#3722]
The relatively new `netip` package promises allocation-free IP address handling. We should use it internally and in our APIs (unless a `net` type is needed to satisfy an interface). Note that this likely result in a few breaking API changes.

Unfortunately, this is now blocked on Go's new UDP API (https://github.com/quic-go/quic-go/issues/3563), as the current `x/net` API forces us to use the `net` package, and converting to `netip` provides little benefit. While we could do the breaking API changes right now, we might as well delay them until we can actually make use of the `netip` package.

**Comment by marten-seemann** [comment]
As a result of the discussion in https://github.com/quic-go/quic-go/issues/3727#issuecomment-1484482033, using `netip` in the API is not possible if we want to use `net.PacketConn`s, which is a feature that's used by some users of the library.
Internally, we should take care to use `netip` package whenever possible, but this will fall naturally out of using Go's new UDP API (#3563), should that ever become a reality.

**Comment by birneee** [comment]
Using netip.AddrPort instead of net.UDPAddr would also have the benefit of easier and probably also faster comparison of addresses. This will be especially become useful for features like connection migration or multipath, when addresses end up in some hashmap or similar.

**Comment by marten-seemann** [comment]
Unfortunately, this doesn't work with `net.PacketConn`s though, so it looks like we're stuck with `net.Addr`.
