### ISSUE TITLE
return a tls.CertificateVerificationError when verifying the certificate fails

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#3730]
This error was added in Go 1.20.

**Comment by marten-seemann** [comment]
The question is, how does a reasonable error API look like.
Currently, the `TransportError` contains an `ErrorMessage string`: https://github.com/quic-go/quic-go/blob/6d7280b7dc6c3535086d9faa83451704c9842bda/internal/qerr/errors.go#L15-L20

We could replace this with an `Err error`, which would allow seamless unwrapping of the error (and users to use standard Go error inspection functions like `errors.As`). For crypto errors, we'd just set whatever error we get from the TLS stack. For errors that we generate, we'd use `fmt.Errorf`.

However, this doesn't really make a lot of sense for errors that we receive from the peer. There, we only have the error code and the error message, and wrapping those in a Go error doesn't feel right. I'm wondering if there's a better error abstraction.

**Comment by MarcoPolo** [comment]
What about a way for an application to define the mapping/func from `(errorCode, errorMessage) -> error`. Then the application can create distinguished errors for certain error codes and handle them cleanly in their application logic. The fallback case can be a new Go error.

**Comment by marten-seemann** [comment]
I'm not sure how that would work? The more idiomatic way would be to allow the application to do error assertions / unwrap the underlying error, which is what #4015 does.
