### ISSUE TITLE
Send buffer errors in netstat

### ISSUE THREAD

**Issue by bt90** [quic-go/quic-go#3731]
While playing around with openspeedtest and caddy, I noticed that an HTTP/3 benchmark increases the number of `send buffer errors` in the netstat output. Interestingly, the number of `receive buffer errors` remains the same, despite benchmarking both down and upload.

To reproduce:

1. Start a larger download via HTTP/3
2. observe the output of:   
```
sudo netstat -u -s | grep "buffer errors"
```

sysctl config:

```
net.core.rmem_max = 2097152
```

I wonder if it's because we're just increasing the receive buffer?

**Comment by marten-seemann** [comment]
What's your send buffer size? What happens if you increase it?

**Comment by bt90** [comment]
I didn't change the default values of my Ubuntu 22.04 installation. `wmem_default` and `wmem_max` are both set to `212992`.

**Comment by bt90** [comment]
A bit offtopic but we could follow the defaults of wireguard-go.

https://github.com/WireGuard/wireguard-go/blob/6f895be10d741d138ec240d3c53acf3afde44b6c/conn/controlfns.go#L13-L18

https://github.com/WireGuard/wireguard-go/blob/6f895be10d741d138ec240d3c53acf3afde44b6c/conn/controlfns_linux.go#L23-L32

https://github.com/WireGuard/wireguard-go/blob/6f895be10d741d138ec240d3c53acf3afde44b6c/conn/controlfns_windows.go#L16-L21

**Comment by bt90** [comment]
@marten-seemann i can't replicate it anymore so the noticeable amount of errors was most likely not caused by quic-go.

But with maybe it's still worth testing with a larger write buffer with GSO in mind?

**Comment by marten-seemann** [comment]
@bt90 Would you mind rerunning your tests now that GSO is enabled by default? Does this still occur or can we close this issue?

**Comment by bt90** [comment]
No problems so far and we're also increasing both buffer sizes now.
