### ISSUE TITLE
Any way to build with `gotip`?

### ISSUE THREAD

**Issue by francislavoie** [quic-go/quic-go#3757]
Because of `qtls`, I'm not able to build Caddy with `gotip` to test some upcoming functionality in Go.

```
$ gotip build                                                                                
# github.com/quic-go/quic-go/internal/qtls
../../../../go/pkg/mod/github.com/quic-go/quic-go@v0.33.0/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
```

Is there any possible workaround to make builds work? Is my only option to fork `qtls` to hack in a fix to make the Go 1.20 qtls apply to Go 1.21 as well?

Semi-relatedly, this has been a point of friction with Caddy releases, users tend to want to try to build Caddy with the latest version of Go right away, but usually we need to update our `quic-go` dependency before they're able to do so, and sometimes (understandably) that isn't ready right away when Go releases.

Is there any reason that `qtls` can't be prepared well ahead of time to support the next Go version, possibly with a warning in place instead of an error, saying that the APIs are possibly subject to change?

**Comment by marten-seemann** [comment]
I hear you. qlts is a pain.

More context: https://github.com/quic-go/quic-go/issues/2727

But I have good news for you. If everything goes according to plan, we won’t need it any more for Go 1.21! crypto/tls is gaining a QUIC API (https://github.com/golang/go/issues/44886), and with a little bit of luck, we’ll even get this extended to support 0-RTT (which would be a requirement for quic-go).

**Comment by marten-seemann** [comment]
Almost:
1. The branch linked from the issue needs to be merged. 
2. Then there’ll be a separate CL for the 0-RTT API.
3. Once that is merged, I’ll integrate it into quic-go. I already have a branch.
