### ISSUE TITLE
Help regarding new implementation design

### ISSUE THREAD

**Issue by RM07** [quic-go/quic-go#3768]
I recently learnt about QUIC protocol and came across this quic-go repository on github. As a project I am currently working on a project with the flow like this.
1) TCP client connection is initiated and all the required information of connection is saved.
2) Now a QUIC client connection is initiated for fetching some big data from the server and that connection is broken in between.
3) Now client connection should be shifted to TCP to resume fetching the data but we want to initiate this connection without a three way handshake by using the previous TCP connection details saved in 1st step.
I am not finding much documentation to implement this and some help and discussion would be greatly appreciated.
Eagerly looking forward to your response

**Comment by marten-seemann** [comment]
This doesn't seem related to QUIC itself, but rather something you can build _on top_ of TCP and QUIC.

**Comment by RM07** [comment]
@marten-seemann  , any comments on this?, looking forward to your response.
