### ISSUE TITLE
Information about rejected clients

### ISSUE THREAD

**Issue by sebtig** [quic-go/quic-go#3776]
Hi!

Picking up the idea of [Issue #2558 ](https://github.com/quic-go/quic-go/issues/2558) I would like to get some information about rejected clients on udp / tls level (bad attempts, invalid ca, ...) In order to minimize public exposition of my servers, I use a custom wrapper for ufw to block any suspicious client as soon as possible.

Kind regards

**Comment by marten-seemann** [comment]
Not sure what your question is.

**Comment by sebtig** [comment]
Regular clients use certs that are signed by my custom CA (and are accepted to connect)
And when I try to establish a connection (e.g. using a client that does not load the signed certs) I get a client side error like "ALPN negotiation failed. Server didn't offer any protocols" or, if I specify a valid []string for NextProtos, I get 'CRYPTO_ERROR 0x12a (remote): tls: bad certificate'

But what about the server side? Probably I missed something, but I was expecting to get an error from my 

```
for {

	conn, err := s.listener.Accept(context.Background())
	if err != nil {
		...
	}
	go handleConnection()
}

```
loop. Something like 'A client [10.1.2.3] has tried to connect with invalid certificates' or just 'A client [10.1.2.3] does not seem to be a quic-client at all'.

Do you see a chance to handle these kinds of errors on the server side?

**Comment by marten-seemann** [comment]
These errors are handled, but not surfaced, on the server side. This behavior is consistent with a crypto/tls server.
