### ISSUE TITLE
How to properly enable 0-RTT?

### ISSUE THREAD

**Issue by ShivanshVij** [quic-go/quic-go#3792]
I've got a site using quic-go deployed here: https://rust-shivanshvij.scale.fun and I've enabled 0-RTT using the following code:

```go
packetConn, err := net.ListenUDP("udp", udpAddr)
if err != nil {
  return err
}

h3Listener, err := quic.ListenEarly(packetConn, tlsConfig, &quic.Config{
  Allow0RTT:                func(_ net.Addr) bool { return true },
  RequireAddressValidation: func(_ net.Addr) bool { return false },
})
if err != nil {
  _ = packetConn.Close()
  return err
}

h3Server := &http3.Server{
  Handler: http.HandlerFunc(http3Handler),
}

err = h3Server.ServeListener(h3Listener)
...
```

This is the same implementation as seen here: https://github.com/caddyserver/caddy/blob/1c9ea0113d007d57bb8f793ebe7a64a3dcad7bc7/listeners.go#L444 

I know that the HTTP/3 part is working correctly because when I hit this site with my browser I see that the protocol shows `h3`:

<img width="1422" alt="Screenshot 2023-04-26 at 8 38 54 PM" src="https://user-images.githubusercontent.com/27162109/234731020-7c8b6ea9-23db-4a9c-97fb-5521352ef2cb.png">

That being said, I don't think 0-RTT is working as expected. The test from SSL Labs (https://www.ssllabs.com/ssltest/analyze.html?d=rust-shivanshvij.scale.fun&hideResults=on) finds that 0-RTT is disabled:
 
<img width="1422" alt="Screenshot 2023-04-26 at 8 40 10 PM" src="https://user-images.githubusercontent.com/27162109/234731162-6dedeca3-dd3f-4605-b0e9-157f43d9fbaa.png">

and the same result is seen with the `sslyze` python package:

<img width="556" alt="Screenshot 2023-04-26 at 8 41 23 PM" src="https://user-images.githubusercontent.com/27162109/234731268-e097afa0-7a78-426a-bb89-17d62be7bdc2.png">

**Comment by marten-seemann** [comment]
Sorry for the delayed response here. I'm surprised you're relying on these tools test for 0-RTT. It looks like `sslyze` [doesn't even speak QUIC](https://github.com/search?q=repo%3Anabla-c0d3%2Fsslyze%20quic&type=code), and I'm not sure if SSLabs does.

If you actually want to check for 0-RTT support, have a look what Chrome does, and record a qlog to see if 0-RTT packets are sent.
