### ISSUE TITLE
use SO_RCVBUFFORCE to increase receive buffer size

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#3795]
> SO_RCVBUFFORCE (since Linux 2.6.14): Using this socket option, a privileged (CAP_NET_ADMIN) process can perform the same task as SO_RCVBUF, but the rmem_max limit can be overridden.

**Comment by MarcoPolo** [comment]
I'm interested in picking this up. 🧑‍🏭

**Comment by otbutz** [comment]
@marten-seemann could you add a Linux section to https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes which explains the `CAP_NET_ADMIN` exception?

**Comment by marten-seemann** [comment]
@otbutz Can you suggest some text?

**Comment by otbutz** [comment]
Do we need a section for Windows?
