### ISSUE TITLE
use a ring buffer for the frame queue in the framer

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#3826]
The framer uses a slice of stream IDs, containing an (ordered) list of the streams that have data to send:
https://github.com/quic-go/quic-go/blob/e9fea086134e61073d443ea1ac0ec256b88e4864/framer.go#L31

Using a slice here is problematic, as for every packet we send (assuming it contains one STREAM frame), we consume and append one element to the slice. It therefore leads to regular allocations in the data send path.

This allocation is responsible for more than 10% of the runtime of `AppendStreamFrames`:
<img width="937" alt="image" src="https://github.com/quic-go/quic-go/assets/1478487/01c2d507-105d-4517-bb58-a275d91f85c5">

Instead, we should use a ring buffer. It can start with a fairly small capacity (4 maybe?) and double that capacity once this is not enough. In this case, the maximum capacity is limited by the number of concurrent streams, so the ring buffer would not have to deal with this.

I imagine that it would make sense to implement a generic ring buffer and use that one in the framer.

**Comment by Glonee** [comment]
https://github.com/golang/go/blob/e4e8f9b8ffff9d1bcbaaf4b98307d0b88c26678f/src/net/http/transport.go#L1264-L1303
Here is a efficient queue implemention in the standard library. It is similar to ringbuffer but the implemention is much simpler. Maybe we can implement a generic version and use it?

**Comment by SahibYar** [comment]
@marten-seemann quick question, which tool did you use for cyclomatic complexity runtime analysis shown in the screenshot ?
