### ISSUE TITLE
save the RTT with the session ticket, for non-0-RTT tickets

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#3853]
For 0-RTT session tickets, we save the RTT in the session ticket: https://github.com/quic-go/quic-go/blob/cb3453db2508eedf4ea3ce49f86bbe029de5c1c9/internal/handshake/crypto_setup.go#L483-L489

We could do that as well for non-0-RTT tickets, allowing for a faster session resumption. This makes sense to implement once we have the new crypto/tls API (#2727).

**Comment by marten-seemann** [comment]
Blocked on the new 0-RTT API (mostly to avoid merge conflicts). Once we have this, this would be a good first issue.

**Comment by tanghaowillow** [comment]
Hi @marten-seemann, is there anyone working on this?

**Comment by marten-seemann** [comment]
Not that I'm aware of. Want to submit a PR? Happy to review :)

**Comment by tanghaowillow** [comment]
Thanks for the fast reply! I'll have a try this week.

**Comment by tanghaowillow** [comment]
Hi @marten-seemann , I have made it work for go 1.21 but I find it is hard to implement for go 1.20 due to the current api provided by qtls-go1-20. Should I submit a PR to the qtls-go1-20 package for this?

**Comment by marten-seemann** [comment]
No need to. We don't need to optimize for old versions. Of course, we need to make sure that both are still interoperable though.
