### ISSUE TITLE
timeout: handshake did not complete in time

### ISSUE THREAD

**Issue by guodoliu** [quic-go/quic-go#3858]
we met this issue recently, after grab the packet, we found that the serverHello frame seems lost and the client side hangs in sending initial packet and server side hangs in sending initial packet with only ack frame.
the qlog is as below:
**client side:**

[INFO 10:37:49 上午] 2023/05/23 10:37:49 muxer Increased receive buffer size to 2048 kiB

[INFO 10:37:49 上午] 2023/05/23 10:37:49 Activating reading of ECN bits for IPv6.

[INFO 10:37:49 上午] 2023/05/23 10:37:49 Activating reading of packet info bits for IPv6.

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client Starting new connection to 10.174.143.41 ([::]:60014 -> 10.174.143.41:33000), source connection ID ae351b38, destination connection ID 6807ed426bb4a04bbe47bf5145477c2a142857c3, version v1

[INFO 10:37:49 上午] 2023/05/23 10:37:49 muxer Adding connection ID ae351b38.

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client Not doing 0-RTT.

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client Sending a keep-alive PING to keep the connection alive.

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client -> Sending packet 0 (1252 bytes) for connection 6807ed426bb4a04bbe47bf5145477c2a142857c3, Initial

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	Long Header{Type: Initial, DestConnectionID: 6807ed426bb4a04bbe47bf5145477c2a142857c3, SrcConnectionID: ae351b38, Token: (empty), PacketNumber: 0, PacketNumberLen: 2, Length: 1218, Version: v1}

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	-> &wire.CryptoFrame{Offset: 0, Data length: 275, Offset + Data length: 275}

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client Loss detection alarm for Initial fired in PTO mode. PTO count: 1

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client -> Sending packet 1 (1252 bytes) for connection 6807ed426bb4a04bbe47bf5145477c2a142857c3, Initial

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	Long Header{Type: Initial, DestConnectionID: 6807ed426bb4a04bbe47bf5145477c2a142857c3, SrcConnectionID: ae351b38, Token: (empty), PacketNumber: 1, PacketNumberLen: 2, Length: 1218, Version: v1}

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	-> &wire.CryptoFrame{Offset: 0, Data length: 275, Offset + Data length: 275}

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client -> Sending packet 2 (1252 bytes) for connection 6807ed426bb4a04bbe47bf5145477c2a142857c3, Initial

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	Long Header{Type: Initial, DestConnectionID: 6807ed426bb4a04bbe47bf5145477c2a142857c3, SrcConnectionID: ae351b38, Token: (empty), PacketNumber: 2, PacketNumberLen: 2, Length: 1218, Version: v1}

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	-> &wire.CryptoFrame{Offset: 0, Data length: 275, Offset + Data length: 275}

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client <- Reading packet 1 (41 bytes) for connection ae351b38, Initial

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	Long Header{Type: Initial, DestConnectionID: ae351b38, SrcConnectionID: 1831888e, Token: (empty), PacketNumber: 1, PacketNumberLen: 2, Length: 23, Version: v1}

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client Received first packet. Switching destination connection ID to: 1831888e

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	<- &wire.AckFrame{LargestAcked: 2, LowestAcked: 0, DelayTime: 0s}

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	newly acked packets (3): [0 1 2]

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	updated RTT: 33.491084ms (σ: 16.745542ms)

[INFO 10:37:49 上午] 2023/05/23 10:37:49 new window on packet acked: 4006400

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client Sending a keep-alive PING to keep the connection alive.

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client -> Sending packet 3 (1252 bytes) for connection 6807ed426bb4a04bbe47bf5145477c2a142857c3, Initial

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	Long Header{Type: Initial, DestConnectionID: 1831888e, SrcConnectionID: ae351b38, Token: (empty), PacketNumber: 3, PacketNumberLen: 2, Length: 1234, Version: v1}

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	-> &wire.PingFrame{}

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client Queueing packet (905 bytes) for later decryption

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client Queueing packet (905 bytes) for later decryption

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client <- Reading packet 4 (41 bytes) for connection ae351b38, Initial

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	Long Header{Type: Initial, DestConnectionID: ae351b38, SrcConnectionID: 1831888e, Token: (empty), PacketNumber: 4, PacketNumberLen: 2, Length: 23, Version: v1}

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	<- &wire.AckFrame{LargestAcked: 3, LowestAcked: 0, DelayTime: 0s}

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	newly acked packets (1): [3]

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	updated RTT: 36.607ms (σ: 18.791ms)

[INFO 10:37:49 上午] 2023/05/23 10:37:49 new window on packet acked: 4006400

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client Sending a keep-alive PING to keep the connection alive.

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client -> Sending packet 4 (1252 bytes) for connection 6807ed426bb4a04bbe47bf5145477c2a142857c3, Initial

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	Long Header{Type: Initial, DestConnectionID: 1831888e, SrcConnectionID: ae351b38, Token: (empty), PacketNumber: 4, PacketNumberLen: 2, Length: 1234, Version: v1}

[INFO 10:37:49 上午] 2023/05/23 10:37:49 client 	-> &wire.PingFrame{}

[INFO 10:37:50 上午] 2023/05/23 10:37:50 client <- Reading packet 5 (41 bytes) for connection ae351b38, Initial

[INFO 10:37:50 上午] 2023/05/23 10:37:50 client 	Long Header{Type: Initial, DestConnectionID: ae351b38, SrcConnectionID: 1831888e, Token: (empty), PacketNumber: 5, PacketNumberLen: 2, Length: 23, Version: v1}

[INFO 10:37:50 上午] 2023/05/23 10:37:50 client 	<- &wire.AckFrame{LargestAcked: 4, LowestAcked: 0, DelayTime: 0s}

[INFO 10:37:50 上午] 2023/05/23 10:37:50 client 	newly acked packets (1): [4]

[INFO 10:37:50 上午] 2023/05/23 10:37:50 client 	updated RTT: 40.962ms (σ: 22.805ms)

[INFO 10:37:50 上午] 2023/05/23 10:37:50 new window on packet acked: 4006400

[INFO 10:37:50 上午] 2023/05/23 10:37:50 client Sending a keep-alive PING to keep the connection alive.

[INFO 10:37:51 上午] 2023/05/23 10:37:51 muxer Tracking 1 connection IDs and 0 reset tokens.

[INFO 10:37:51 上午] 2023/05/23 10:37:51 client Queueing packet (905 bytes) for later decryption

[INFO 10:37:51 上午] 2023/05/23 10:37:51 client Queueing packet (905 bytes) for later decryption

[INFO 10:37:51 上午] 2023/05/23 10:37:51 client -> Sending packet 5 (1252 bytes) for connection 6807ed426bb4a04bbe47bf5145477c2a142857c3, Initial

[INFO 10:37:51 上午] 2023/05/23 10:37:51 client 	Long Header{Type: Initial, DestConnectionID: 1831888e, SrcConnectionID: ae351b38, Token: (empty), PacketNumber: 5, PacketNumberLen: 2, Length: 1234, Version: v1}

[INFO 10:37:51 上午] 2023/05/23 10:37:51 client 	-> &wire.PingFrame{}

[INFO 10:37:51 上午] 2023/05/23 10:37:51 client <- Reading packet 8 (41 bytes) for connection ae351b38, Initial

[INFO 10:37:51 上午] 2023/05/23 10:37:51 client 	Long Header{Type: Initial, DestConnectionID: ae351b38, SrcConnectionID: 1831888e, Token: (empty), PacketNumber: 8, PacketNumberLen: 2, Length: 23, Version: v1}

[INFO 10:37:51 上午] 2023/05/23 10:37:51 client 	<- &wire.AckFrame{LargestAcked: 5, LowestAcked: 0, DelayTime: 0s}

[INFO 10:37:51 上午] 2023/05/23 10:37:51 client 	newly acked packets (1): [5]

[INFO 10:37:51 上午] 2023/05/23 10:37:51 client 	updated RTT: 43.12ms (σ: 21.419ms)

[INFO 10:37:51 上午] 2023/05/23 10:37:51 new window on packet acked: 4006400

[INFO 10:37:51 上午] 2023/05/23 10:37:51 client Sending a keep-alive PING to keep the connection alive.

[INFO 10:37:53 上午] 2023/05/23 10:37:53 muxer Tracking 1 connection IDs and 0 reset tokens.

[INFO 10:37:53 上午] 2023/05/23 10:37:53 client -> Sending packet 6 (1252 bytes) for connection 6807ed426bb4a04bbe47bf5145477c2a142857c3, Initial

[INFO 10:37:53 上午] 2023/05/23 10:37:53 client 	Long Header{Type: Initial, DestConnectionID: 1831888e, SrcConnectionID: ae351b38, Token: (empty), PacketNumber: 6, PacketNumberLen: 2, Length: 1234, Version: v1}

[INFO 10:37:53 上午] 2023/05/23 10:37:53 client 	-> &wire.PingFrame{}

[INFO 10:37:53 上午] 2023/05/23 10:37:53 client <- Reading packet 9 (41 bytes) for connection ae351b38, Initial

[INFO 10:37:53 上午] 2023/05/23 10:37:53 client 	Long Header{Type: Initial, DestConnectionID: ae351b38, SrcConnectionID: 1831888e, Token: (empty), PacketNumber: 9, PacketNumberLen: 2, Length: 23, Version: v1}

[INFO 10:37:53 上午] 2023/05/23 10:37:53 client 	<- &wire.AckFrame{LargestAcked: 6, LowestAcked: 0, DelayTime: 0s}

[INFO 10:37:53 上午] 2023/05/23 10:37:53 client 	newly acked packets (1): [6]

[INFO 10:37:53 上午] 2023/05/23 10:37:53 client 	updated RTT: 45.314ms (σ: 20.453ms)

[INFO 10:37:53 上午] 2023/05/23 10:37:53 new window on packet acked: 4006400

[INFO 10:37:53 上午] 2023/05/23 10:37:53 client Sending a keep-alive PING to keep the connection alive.

[INFO 10:37:55 上午] 2023/05/23 10:37:55 muxer Tracking 1 connection IDs and 0 reset tokens.

[INFO 10:37:57 上午] 2023/05/23 10:37:57 muxer Tracking 1 connection IDs and 0 reset tokens.

[INFO 10:37:57 上午] 2023/05/23 10:37:57 client -> Sending packet 7 (1252 bytes) for connection 6807ed426bb4a04bbe47bf5145477c2a142857c3, Initial

[INFO 10:37:57 上午] 2023/05/23 10:37:57 client 	Long Header{Type: Initial, DestConnectionID: 1831888e, SrcConnectionID: ae351b38, Token: (empty), PacketNumber: 7, PacketNumberLen: 2, Length: 1234, Version: v1}

[INFO 10:37:57 上午] 2023/05/23 10:37:57 client 	-> &wire.PingFrame{}

[INFO 10:37:57 上午] 2023/05/23 10:37:57 client <- Reading packet 12 (41 bytes) for connection ae351b38, Initial

[INFO 10:37:57 上午] 2023/05/23 10:37:57 client 	Long Header{Type: Initial, DestConnectionID: ae351b38, SrcConnectionID: 1831888e, Token: (empty), PacketNumber: 12, PacketNumberLen: 2, Length: 23, Version: v1}

[INFO 10:37:57 上午] 2023/05/23 10:37:57 client 	<- &wire.AckFrame{LargestAcked: 7, LowestAcked: 0, DelayTime: 0s}

[INFO 10:37:57 上午] 2023/05/23 10:37:57 client 	newly acked packets (1): [7]

[INFO 10:37:57 上午] 2023/05/23 10:37:57 client 	updated RTT: 47.173ms (σ: 19.059ms)

[INFO 10:37:57 上午] 2023/05/23 10:37:57 new window on packet acked: 4006400

[INFO 10:37:57 上午] 2023/05/23 10:37:57 client Sending a keep-alive PING to keep the connection alive.

[INFO 10:37:57 上午] 2023/05/23 10:37:57 client Queueing packet (905 bytes) for later decryption

[INFO 10:37:57 上午] 2023/05/23 10:37:57 client Queueing packet (905 bytes) for later decryption

[INFO 10:37:59 上午] 2023/05/23 10:37:59 muxer Tracking 1 connection IDs and 0 reset tokens.

[INFO 10:37:59 上午] bsync run for 10.008474s

[INFO 10:37:59 上午] 2023/05/23 10:37:59 client Destroying connection: timeout: handshake did not complete in time

[INFO 10:37:59 上午] 2023/05/23 10:37:59 muxer Removing connection ID ae351b38.

[INFO 10:37:59 上午] 2023/05/23 10:37:59 client Connection 6807ed426bb4a04bbe47bf5145477c2a142857c3 closed.

[INFO 10:37:59 上午] Error: dial: timeout: handshake did not complete in time

[INFO 10:37:59 上午] exec rsync command time cost: 10.024784s

[ERROR 10:37:59 上午] sync files failed, reason: kotlin.Unit

**the server side:**
2023/05/24 17:15:29 server <- Received Initial packet.
2023/05/24 17:15:29 server Changing connection ID to 73ab38c7.
2023/05/24 17:15:29 muxer Adding connection IDs be71cf0f17fe768cf528a3efa578b35ca139 and 73ab38c7 for a new connection.
2023/05/24 17:15:29 server <- Reading packet 0 (1252 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Initial
2023/05/24 17:15:29 server      Long Header{Type: Initial, DestConnectionID: be71cf0f17fe768cf528a3efa578b35ca139, SrcConnectionID: fc99e048, Token: (empty), PacketNumber: 0, PacketNumberLen: 2, Length: 1220, Version: v1}
2023/05/24 17:15:29 server      <- &wire.CryptoFrame{Offset: 0, Data length: 273, Offset + Data length: 273}
2023/05/24 17:15:29 server Received ClientHello message (273 bytes, encryption level: Initial)
2023/05/24 17:15:29 server Installed Handshake Read keys (using TLS_CHACHA20_POLY1305_SHA256)
2023/05/24 17:15:29 server Installed Handshake Write keys (using TLS_CHACHA20_POLY1305_SHA256)
2023/05/24 17:15:29 server Processed Transport Parameters: &wire.TransportParameters{OriginalDestinationConnectionID: (empty), InitialSourceConnectionID: fc99e048, InitialMaxStreamDataBidiLocal: 4194304, InitialMaxStreamDataBidiRemote: 4194304, InitialMaxStreamDataUni: 4194304, InitialMaxData: 786432, MaxBidiStreamNum: 100, MaxUniStreamNum: 100, MaxIdleTimeout: 30s, AckDelayExponent: 3, MaxAckDelay: 26ms, ActiveConnectionIDLimit: 4}
2023/05/24 17:15:29 muxer Adding connection ID 9ae36a8a.
2023/05/24 17:15:29 muxer Adding connection ID 2bbc1d4f.
2023/05/24 17:15:29 muxer Adding connection ID c734b900.
2023/05/24 17:15:29 server Installed 1-RTT Write keys (using TLS_CHACHA20_POLY1305_SHA256)
2023/05/24 17:15:29 server      Queueing ACK because the first packet should be acknowledged.
2023/05/24 17:15:29 server -> Sending coalesced packet (3 parts, 1252 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139
2023/05/24 17:15:29 server      Long Header{Type: Initial, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, Token: (empty), PacketNumber: 0, PacketNumberLen: 2, Length: 237, Version: v1}
2023/05/24 17:15:29 server      -> &wire.AckFrame{LargestAcked: 0, LowestAcked: 0, DelayTime: 0s}
2023/05/24 17:15:29 server      -> &wire.CryptoFrame{Offset: 0, Data length: 90, Offset + Data length: 90}
2023/05/24 17:15:29 server      Long Header{Type: Handshake, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, PacketNumber: 0, PacketNumberLen: 2, Length: 885, Version: v1}
2023/05/24 17:15:29 server      -> &wire.CryptoFrame{Offset: 0, Data length: 863, Offset + Data length: 863}
2023/05/24 17:15:29 server      Short Header{DestConnectionID: fc99e048, PacketNumber: 0, PacketNumberLen: 2, KeyPhase: 0}
2023/05/24 17:15:29 server      -> &wire.NewConnectionIDFrame{SequenceNumber: 3, ConnectionID: c734b900, StatelessResetToken: 0x7eb5d8211abc035b952ae9dc2357f31b}
2023/05/24 17:15:29 server      -> &wire.NewConnectionIDFrame{SequenceNumber: 2, ConnectionID: 2bbc1d4f, StatelessResetToken: 0x7bc73aa10ac10ec7131eb9d136889544}
2023/05/24 17:15:29 server      -> &wire.NewConnectionIDFrame{SequenceNumber: 1, ConnectionID: 9ae36a8a, StatelessResetToken: 0x62d4213fff5ba27200d4f3a46f736ddb}
2023/05/24 17:15:29 server <- Reading packet 1 (1252 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Initial
2023/05/24 17:15:29 server      Long Header{Type: Initial, DestConnectionID: be71cf0f17fe768cf528a3efa578b35ca139, SrcConnectionID: fc99e048, Token: (empty), PacketNumber: 1, PacketNumberLen: 2, Length: 1220, Version: v1}
2023/05/24 17:15:29 server      <- &wire.CryptoFrame{Offset: 0, Data length: 273, Offset + Data length: 273}
2023/05/24 17:15:29 server      Setting ACK timer to max ack delay: 25ms
2023/05/24 17:15:29 server <- Reading packet 2 (1252 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Initial
2023/05/24 17:15:29 server      Long Header{Type: Initial, DestConnectionID: be71cf0f17fe768cf528a3efa578b35ca139, SrcConnectionID: fc99e048, Token: (empty), PacketNumber: 2, PacketNumberLen: 2, Length: 1220, Version: v1}
2023/05/24 17:15:29 server      <- &wire.CryptoFrame{Offset: 0, Data length: 273, Offset + Data length: 273}
2023/05/24 17:15:29 server      Queueing ACK because packet 2 packets were received after the last ACK (using initial threshold: 2).
2023/05/24 17:15:29 server -> Sending packet 1 (41 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Initial
2023/05/24 17:15:29 server      Long Header{Type: Initial, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, Token: (empty), PacketNumber: 1, PacketNumberLen: 2, Length: 23, Version: v1}
2023/05/24 17:15:29 server      -> &wire.AckFrame{LargestAcked: 2, LowestAcked: 0, DelayTime: 0s}
2023/05/24 17:15:29 server Loss detection alarm for Initial fired in PTO mode. PTO count: 1
2023/05/24 17:15:29 server -> Sending packet 2 (1252 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Initial
2023/05/24 17:15:29 server      Long Header{Type: Initial, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, Token: (empty), PacketNumber: 2, PacketNumberLen: 2, Length: 1234, Version: v1}
2023/05/24 17:15:29 server      -> &wire.CryptoFrame{Offset: 0, Data length: 90, Offset + Data length: 90}
2023/05/24 17:15:29 server -> Sending packet 3 (1252 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Initial
2023/05/24 17:15:29 server      Long Header{Type: Initial, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, Token: (empty), PacketNumber: 3, PacketNumberLen: 2, Length: 1234, Version: v1}
2023/05/24 17:15:29 server      -> &wire.CryptoFrame{Offset: 0, Data length: 90, Offset + Data length: 90}
2023/05/24 17:15:29 server Loss detection alarm for Handshake fired in PTO mode. PTO count: 2
2023/05/24 17:15:29 server -> Sending packet 1 (902 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Handshake
2023/05/24 17:15:29 server      Long Header{Type: Handshake, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, PacketNumber: 1, PacketNumberLen: 2, Length: 885, Version: v1}
2023/05/24 17:15:29 server      -> &wire.CryptoFrame{Offset: 0, Data length: 863, Offset + Data length: 863}
2023/05/24 17:15:29 server -> Sending packet 2 (902 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Handshake
2023/05/24 17:15:29 server      Long Header{Type: Handshake, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, PacketNumber: 2, PacketNumberLen: 2, Length: 885, Version: v1}
2023/05/24 17:15:29 server      -> &wire.CryptoFrame{Offset: 0, Data length: 863, Offset + Data length: 863}
2023/05/24 17:15:29 server <- Reading packet 3 (1252 bytes) for connection 73ab38c7, Initial
2023/05/24 17:15:29 server      Long Header{Type: Initial, DestConnectionID: 73ab38c7, SrcConnectionID: fc99e048, Token: (empty), PacketNumber: 3, PacketNumberLen: 2, Length: 1234, Version: v1}
2023/05/24 17:15:29 server      <- &wire.PingFrame{}
2023/05/24 17:15:29 server      Setting ACK timer to max ack delay: 25ms
2023/05/24 17:15:29 server Sending ACK because the ACK timer expired.
2023/05/24 17:15:29 server -> Sending packet 4 (41 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Initial
2023/05/24 17:15:29 server      Long Header{Type: Initial, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, Token: (empty), PacketNumber: 4, PacketNumberLen: 2, Length: 23, Version: v1}
2023/05/24 17:15:29 server      -> &wire.AckFrame{LargestAcked: 3, LowestAcked: 0, DelayTime: 0s}
2023/05/24 17:15:29 muxer Tracking 5 connection IDs and 0 reset tokens.
2023/05/24 17:15:30 server <- Reading packet 4 (1252 bytes) for connection 73ab38c7, Initial
2023/05/24 17:15:30 server      Long Header{Type: Initial, DestConnectionID: 73ab38c7, SrcConnectionID: fc99e048, Token: (empty), PacketNumber: 4, PacketNumberLen: 2, Length: 1234, Version: v1}
2023/05/24 17:15:30 server      <- &wire.PingFrame{}
2023/05/24 17:15:30 server      Setting ACK timer to max ack delay: 25ms
2023/05/24 17:15:30 server Sending ACK because the ACK timer expired.
2023/05/24 17:15:30 server -> Sending packet 5 (41 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Initial
2023/05/24 17:15:30 server      Long Header{Type: Initial, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, Token: (empty), PacketNumber: 5, PacketNumberLen: 2, Length: 23, Version: v1}
2023/05/24 17:15:30 server      -> &wire.AckFrame{LargestAcked: 4, LowestAcked: 0, DelayTime: 0s}
2023/05/24 17:15:30 server Loss detection alarm for Initial fired in PTO mode. PTO count: 3
2023/05/24 17:15:30 server -> Sending packet 6 (1252 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Initial
2023/05/24 17:15:30 server      Long Header{Type: Initial, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, Token: (empty), PacketNumber: 6, PacketNumberLen: 2, Length: 1234, Version: v1}
2023/05/24 17:15:30 server      -> &wire.CryptoFrame{Offset: 0, Data length: 90, Offset + Data length: 90}
2023/05/24 17:15:30 server -> Sending packet 7 (1252 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Initial
2023/05/24 17:15:30 server      Long Header{Type: Initial, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, Token: (empty), PacketNumber: 7, PacketNumberLen: 2, Length: 1234, Version: v1}
2023/05/24 17:15:30 server      -> &wire.CryptoFrame{Offset: 0, Data length: 90, Offset + Data length: 90}
2023/05/24 17:15:31 server <- Reading packet 5 (1252 bytes) for connection 73ab38c7, Initial
2023/05/24 17:15:31 server      Long Header{Type: Initial, DestConnectionID: 73ab38c7, SrcConnectionID: fc99e048, Token: (empty), PacketNumber: 5, PacketNumberLen: 2, Length: 1234, Version: v1}
2023/05/24 17:15:31 server      <- &wire.PingFrame{}
2023/05/24 17:15:31 server      Setting ACK timer to max ack delay: 25ms
2023/05/24 17:15:31 server Sending ACK because the ACK timer expired.
2023/05/24 17:15:31 server -> Sending packet 8 (41 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Initial
2023/05/24 17:15:31 server      Long Header{Type: Initial, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, Token: (empty), PacketNumber: 8, PacketNumberLen: 2, Length: 23, Version: v1}
2023/05/24 17:15:31 server      -> &wire.AckFrame{LargestAcked: 5, LowestAcked: 0, DelayTime: 0s}
2023/05/24 17:15:31 server Loss detection alarm for Handshake fired in PTO mode. PTO count: 4
2023/05/24 17:15:31 server -> Sending packet 3 (902 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Handshake
2023/05/24 17:15:31 server      Long Header{Type: Handshake, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, PacketNumber: 3, PacketNumberLen: 2, Length: 885, Version: v1}
2023/05/24 17:15:31 server      -> &wire.CryptoFrame{Offset: 0, Data length: 863, Offset + Data length: 863}
2023/05/24 17:15:31 server -> Sending packet 4 (902 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Handshake
2023/05/24 17:15:31 server      Long Header{Type: Handshake, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, PacketNumber: 4, PacketNumberLen: 2, Length: 885, Version: v1}
2023/05/24 17:15:31 server      -> &wire.CryptoFrame{Offset: 0, Data length: 863, Offset + Data length: 863}
2023/05/24 17:15:31 muxer Tracking 5 connection IDs and 0 reset tokens.
2023/05/24 17:15:33 server <- Reading packet 6 (1252 bytes) for connection 73ab38c7, Initial
2023/05/24 17:15:33 server      Long Header{Type: Initial, DestConnectionID: 73ab38c7, SrcConnectionID: fc99e048, Token: (empty), PacketNumber: 6, PacketNumberLen: 2, Length: 1234, Version: v1}
2023/05/24 17:15:33 server      <- &wire.PingFrame{}
2023/05/24 17:15:33 server      Setting ACK timer to max ack delay: 25ms
2023/05/24 17:15:33 server Sending ACK because the ACK timer expired.
2023/05/24 17:15:33 server -> Sending packet 9 (41 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Initial
2023/05/24 17:15:33 server      Long Header{Type: Initial, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, Token: (empty), PacketNumber: 9, PacketNumberLen: 2, Length: 23, Version: v1}
2023/05/24 17:15:33 server      -> &wire.AckFrame{LargestAcked: 6, LowestAcked: 0, DelayTime: 0s}
2023/05/24 17:15:33 server Loss detection alarm for Initial fired in PTO mode. PTO count: 5
2023/05/24 17:15:33 server -> Sending packet 10 (1252 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Initial
2023/05/24 17:15:33 server      Long Header{Type: Initial, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, Token: (empty), PacketNumber: 10, PacketNumberLen: 2, Length: 1234, Version: v1}
2023/05/24 17:15:33 server      -> &wire.CryptoFrame{Offset: 0, Data length: 90, Offset + Data length: 90}
2023/05/24 17:15:33 server -> Sending packet 11 (1252 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Initial
2023/05/24 17:15:33 server      Long Header{Type: Initial, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, Token: (empty), PacketNumber: 11, PacketNumberLen: 2, Length: 1234, Version: v1}
2023/05/24 17:15:33 server      -> &wire.CryptoFrame{Offset: 0, Data length: 90, Offset + Data length: 90}
2023/05/24 17:15:33 muxer Tracking 5 connection IDs and 0 reset tokens.
2023/05/24 17:15:35 muxer Tracking 5 connection IDs and 0 reset tokens.
2023/05/24 17:15:37 server <- Reading packet 7 (1252 bytes) for connection 73ab38c7, Initial
2023/05/24 17:15:37 server      Long Header{Type: Initial, DestConnectionID: 73ab38c7, SrcConnectionID: fc99e048, Token: (empty), PacketNumber: 7, PacketNumberLen: 2, Length: 1234, Version: v1}
2023/05/24 17:15:37 server      <- &wire.PingFrame{}
2023/05/24 17:15:37 server      Setting ACK timer to max ack delay: 25ms
2023/05/24 17:15:37 server Sending ACK because the ACK timer expired.
2023/05/24 17:15:37 server -> Sending packet 12 (41 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Initial
2023/05/24 17:15:37 server      Long Header{Type: Initial, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, Token: (empty), PacketNumber: 12, PacketNumberLen: 2, Length: 23, Version: v1}
2023/05/24 17:15:37 server      -> &wire.AckFrame{LargestAcked: 7, LowestAcked: 0, DelayTime: 0s}
2023/05/24 17:15:37 server Loss detection alarm for Handshake fired in PTO mode. PTO count: 6
2023/05/24 17:15:37 server -> Sending packet 5 (902 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Handshake
2023/05/24 17:15:37 server      Long Header{Type: Handshake, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, PacketNumber: 5, PacketNumberLen: 2, Length: 885, Version: v1}
2023/05/24 17:15:37 server      -> &wire.CryptoFrame{Offset: 0, Data length: 863, Offset + Data length: 863}
2023/05/24 17:15:37 server -> Sending packet 6 (902 bytes) for connection be71cf0f17fe768cf528a3efa578b35ca139, Handshake
2023/05/24 17:15:37 server      Long Header{Type: Handshake, DestConnectionID: fc99e048, SrcConnectionID: 73ab38c7, PacketNumber: 6, PacketNumberLen: 2, Length: 885, Version: v1}
2023/05/24 17:15:37 server      -> &wire.CryptoFrame{Offset: 0, Data length: 863, Offset + Data length: 863}
2023/05/24 17:15:37 muxer Tracking 5 connection IDs and 0 reset tokens.
2023/05/24 17:15:39 server Destroying connection: timeout: handshake did not complete in time
2023/05/24 17:15:39 muxer Removing connection ID be71cf0f17fe768cf528a3efa578b35ca139.
2023/05/24 17:15:39 muxer Removing connection ID 73ab38c7.
2023/05/24 17:15:39 muxer Removing connection ID 9ae36a8a.
2023/05/24 17:15:39 muxer Removing connection ID 2bbc1d4f.
2023/05/24 17:15:39 muxer Removing connection ID c734b900.
2023/05/24 17:15:39 server Connection be71cf0f17fe768cf528a3efa578b35ca139 closed.
2023/05/24 17:15:39 muxer Tracking 0 connection IDs and 0 reset tokens.

**Comment by guodoliu** [comment]
@marten-seemann but from the qlog, it seems happened, not sure my quic-go version is lower or others

**Comment by guodoliu** [comment]
![fuprSijmPx](https://github.com/quic-go/quic-go/assets/12164402/a5cfe883-7a44-4639-8a57-04313ad7d2a5)
it seems the serverHello did not retransmit

**Comment by marten-seemann** [comment]
As I said, the integration test that drops every third packet works, so I'm not at all worried that the retransmission doesn't work.

If you want to debug the failure, feel free to record a qlog and look at what's going on in [qvis](https://qvis.quictools.info/#/files).

**Comment by guodoliu** [comment]
@marten-seemann  thanks for your suggestion, i have tried it.  the qvis result is shown below:
![sqmCYkCd1t](https://github.com/quic-go/quic-go/assets/12164402/fae7c211-ed23-42ef-9854-803acb824a25)

from the sequence diagram, you can see that the first initial packet with ack0 and crypo frame(include serverHello message) lost, and when the client retransmit the initial packet, the server side only responded with initial packet which only include ack frame, no serverHello message

**Comment by guodoliu** [comment]
@marten-seemann thanks for your suggestion, i will have a try

**Comment by guodoliu** [comment]
@marten-seemann from the qvis and qlog, i found an interesting issue, that the server side record the crypto frame in the initial packet to send, but from tcpdump caught, there was no such packet.

**Comment by marten-seemann** [comment]
> As I said, the integration test that drops every third packet works, so I'm not at all worried that the retransmission doesn't work.

If you think there's an issue here, please provide a test case that demonstrates that.
