### ISSUE TITLE
v0.35.0 broke http3.RoundTripper and servername from url logic

### ISSUE THREAD

**Issue by kgersen** [quic-go/quic-go#3865]
Since v0.35.0 we have to manually set `tls.Config.ServerName` for any http3 connections to work.
This broke the backward compatibility with stdlib and can lead to numerous issues because we have to keep in sync `ServerName` in `tls.Config` and the url in the `http.Request` albeit these are in completely separated levels in the net/http API logic.

the cultrip is here: [client.go/newClient()](https://github.com/quic-go/quic-go/commit/d683b841c4aa8b8b1434ebd27cebc43be7c2ba16#diff-4b667feae66c9d46b21b9ecc19e8958cf4472d162ce0a47ac3e8386af8bbd8cfL217)

**Comment by marten-seemann** [comment]
Can you explain how this breaks compatibility with the standard library? `tls.Config.ServerName` is the field that's used to verify the server name when using crypto/tls.

**Comment by kgersen** [comment]
it's basic `net/http` usage when using stdlib like it was done before 0.35.0.
even the quic-go example is now broken, try:
`go run example/client/main.go https://google.com`

We never set explicitly `tls.Config.ServerName` unless we're doing tricky stuff:

        client := &http.Client{
	        Transport: default or http3.RoundTripper,
        }
        //then for instance:
        resp, err := client.Get("http://example.com")
        resp2, err2 := client.Get("http://google.com")
        resp3, err3 := client.Get("http://github.com")

the problem is that `tls.Config.ServerName` is bound to client thru transport but a client can process different requests with different urls. 
with v0.35.0 we have to do:

        //then for instance:
        client.Transport.(*http3.RoundTripper).TLSClientConfig.ServerName="example.com"
        resp, err := client.Get("https://example.com")
        client.Transport.(*http3.RoundTripper).TLSClientConfig.ServerName="google.com"
        resp2, err2 := client.Get("https://google.com")
        client.Transport.(*http3.RoundTripper).TLSClientConfig.ServerName="github.com"
        resp3, err3 := client.Get("https://github.com")

or use 3 different clients, etc
This is just impracticable and even worst when using goroutines.

**Comment by marten-seemann** [comment]
I see, this is indeed not optimal. Thank you for the detailed example.

How does the http/2 package solve this? They need to set the `tls.Config.ServerName` somehow, don't they? Maybe that's something that should happen inside the http3 package?

**Comment by marten-seemann** [comment]
Before v0.35 this was done in the quic package, not the http3 package.

Do you want to submit a patch to apply a similar logic in the http3 package?

**Comment by marten-seemann** [comment]
I don’t know, I’m not aware of any HTTP/3 plans of the Go team. Which is a shame, since that would be so much more useful than rewriting an entire QUIC stack from scratch…

That said, applying logic from the http2 package for http3 seems like the correct thing to do here.
