### ISSUE TITLE
Stream Prioritization implementation

### ISSUE THREAD

**Issue by SahibYar** [quic-go/quic-go#3870]
I recently started studying about QUIC, and when I was reading https://datatracker.ietf.org/doc/html/rfc9000#name-stream-prioritization I found that [AddActiveStream in framer.go](https://github.com/quic-go/quic-go/blob/master/framer.go#L84) does not implements any logic for prioritizing streams.

RFC9000 says 
> QUIC does not provide a mechanism for exchanging prioritization information. Instead, it relies on receiving priority information from the application.
A QUIC implementation SHOULD provide ways in which an application can indicate the relative priority of streams. An implementation uses information provided by the application to determine how to allocate resources to active streams.

and  in https://datatracker.ietf.org/doc/html/rfc9000#name-sending-stream-states

> An implementation might choose to defer allocating a stream ID to a stream until it sends the first STREAM frame and enters this state, which can allow for better stream prioritization.

Please guide me if I am missing something here, or can we add Stream Prioritization in Feature Backlog ?

**Comment by marten-seemann** [comment]
See #437 and #3470.
