### ISSUE TITLE
CRYPTO_ERROR 0x150

### ISSUE THREAD

**Issue by codersx** [quic-go/quic-go#3872]
Hello, I am getting an error like this. 

> client Starting new connection to  ([::]:62448 -> 2.19.193.106:443), source connection ID (empty), destination connection ID f416f6787b49aa02f4, version v1
> client Peer closed connection with error: CRYPTO_ERROR 0x150 (remote): 200:TLS handshake failure (ENCRYPTION_INITIAL) 80: internal error
> client Connection f416f6787b49aa02f4 closed.

**Comment by marten-seemann** [comment]
As the error says, that means that the TLS stack encountered an internal error and closed the connection.

You'll need debug logs from the remote node if you want to figure out why.
