### ISSUE TITLE
Question: can long header packets be routed over a separate Conn?

### ISSUE THREAD

**Issue by eenblam** [quic-go/quic-go#3891]
There's been some recent research ([QUICstep](https://arxiv.org/abs/2304.01073)) into leveraging QUIC's connection migration to evade a network censor. The [implementation](https://github.com/inspire-group/quicstep/blob/main/client/wg0.conf#L13) provided for the paper is neat in its simplicity, but it presumes the availability of a Wireguard tunnel, which may not be realistic in heavily censored environments.

While quic-go doesn't support connection migration, my understanding is that this is more of a concern for the server, not the client. (Perhaps I am wrong?) If this is the case, then it would be cool if quic-go provided a viable interface for this kind of behavior. And I don't mean, "provide a narrow implementation of QUICstep" so much as "make it possible for downstream projects to do this kind of thing."

For example, if `setupTransport()` were exported, then users could implement their own version of `DialAddr()` to pass an arbitrary `net.PacketConn` to `SetupTransport()`.

This would allow users to do something like this:

```go
type ProxyClient struct {
        net.UDPConn
}

func (pc *ProxyClient) WriteTo(p []byte, addr net.Addr) (int, error) {
        hdr, _, _, err := wire.ParsePacket(p) // hdr, data, rest, err
        if err != nil { // Short header
                return pc.UDPConn.WriteTo(p, addr)
        } else { // Long header
                // Send long header over some slower, but censorship-resistant channel
                return len(p), nil
        }
        return pc.UDPConn.WriteTo(p, addr)
}                                                         

func (pc *ProxyClient) WriteMsgUDP(b, oob []byte, addr *net.UDPAddr) (int, int, error) {
    // (Similar)
}
```

What I'm less confident about is how to properly hook into quic-go's packet read flow. The above actually breaks down for `ReadFrom()` and `ReadMsgUDP()`, I believe due to `wrapConn()` unpacking the underlying `rawConn` via `rawConn, err := conn.SyscallConn()`. I'm not sure if there's an easy way to work around that.

Any feedback on how best to approach this (even if a fork is required) would be appreciated!

**Comment by eenblam** [comment]
Ah, my mistake - the read behavior I'm seeing is specifically:

* `transport.init()` calls `wrapConn()`, which wraps our `net.PacketConn` inside an `*oobConn`, let's say `c`, which implements `rawConn.ReadPacket()`
* `transport.listen()` then reads by calling `c.ReadPacket()`
* `c.ReadPacket()` calls `c.batchConn.ReadBatch(...)` instead of `c.OOBCapablePacketConn.Read[From|MsgUDP]()`

I was assuming (from comments in the code) that ReadMsgUDP would be called. Perhaps there's a less obvious code-path (e.g an implementation of `net.RawConn.Read()`) where this would eventually be the case, but I otherwise don't see a straightforward way to hook into the read flow at present.

**Comment by marten-seemann** [comment]
From a quick glance through the paper, I wish I had the authors' optimism that a censor wouldn't block migrated connections (i.e. connections for which it hasn't seen the handshake) once this solution becomes widely enough deployed.

That said, I believe the connection migration API suggested in #3990 would enable the implementation of QUICStep, if `ProbePath` is called right after completion of the handshake.
