### ISSUE TITLE
http3 - when closing, http3.Server.Serve returns quic.ErrServerClosed instead of http.ErrServerClosed

### ISSUE THREAD

**Issue by kgersen** [quic-go/quic-go#3898]
The returned error for `http3.Server.Serve`(...) is `quic.ErrServerClosed` in case of a normal shutdown/close. 
It should be `http.ErrServerClosed` instead. 
see method [serveConn](https://github.com/quic-go/quic-go/blob/master/http3/server.go#L276) (some return paths already use `http.ErrServerClosed`).

**Comment by marten-seemann** [comment]
Is that incorrect? You can have a closed QUIC server, while the HTTP/3 server is still running.

**Comment by kgersen** [comment]
what is a "QUIC server" when working at HTTP/3 api level ? Do we need to know about such 'quic' stuff at this level ?
The http3 package tries to reproduce the same API as the `net/http` package. 

With `net/http`, when we use `ListenAndServeTLS `or just `ServeTLS` and the call ends, it means the server stopped. As per the documentation:

> ServeTLS always returns a non-nil error. After Shutdown or Close, the returned error is ErrServerClosed.
source: https://pkg.go.dev/net/http#Server.ServeTLS

So when `http3.Server.Serve`(...) ends, if the returned error is `quic.ErrServerClosed` what is the meaning of this ?

If we have existing code that use net/http and check for `http.ErrServerClosed`, when we switch or add http/3 we must add a special case to check for `quic.ErrServerClosed` which is confusing (which is what we're currently doing now).

**Comment by marten-seemann** [comment]
Should we replace the error if `s.closed == true`?
