### ISSUE TITLE
Codecov shows uncovered code, as integrationtests are not considered. 

### ISSUE THREAD

**Issue by SahibYar** [quic-go/quic-go#3899]
I noticed that Codecov is showing regular decline in code coverage but it is not correct, as `integrationtests` are not considered in Codecov. This can be a good first issue. 

### Questions:
1. What is the minimum threshold coverage for `quic-go` ? 
2. Does the maintainer will configure Codecov accordingly ? or may be I can raise a PR by creating/copying few test functions to increase the code coverage

### Example:

Codecov shows this code is not covered
<img width="1616" alt="image" src="https://github.com/quic-go/quic-go/assets/16621871/197b78b9-9970-42ec-8149-6e2f2af1df76">

but actually this is covered in integration tests
<img width="920" alt="image" src="https://github.com/quic-go/quic-go/assets/16621871/7683d266-c50f-4392-b62a-273259752fad">

**Comment by marten-seemann** [comment]
There's no minimum threshold. Integration tests are not covered on purpose, we only want to measure unit test coverage.
