### ISSUE TITLE
add a context to ReceiveMessage()

### ISSUE THREAD

**Issue by lukas-wr** [quic-go/quic-go#3913]
Hi,
Is there a way to set a timeout on message?

```go
rvcd, err := conn.ReceiveMessage()
```

I set a timeout per connection (MaxIdleTimeout) and it works very well. But if the client is alive and just hasn't sent the message yet, the server will wait indefinitely.
```go
		&quic.Config{
			EnableDatagrams:      true,
			KeepAlivePeriod:      2 * time.Second,
			HandshakeIdleTimeout: 2 * time.Second,
			MaxIdleTimeout:       3 * time.Second,
		},
```

**Comment by marten-seemann** [comment]
Adding a context to `ReceiveMessage` sounds reasonable. Want to submit a patch?
