### ISSUE TITLE
example for QUIC server.

### ISSUE THREAD

**Issue by kehiy** [quic-go/quic-go#3916]
add a example to implement a simple QUIC server using go-quic in README.md
there is no resources to learn start working with this package...
or just add a simple doc.

**Comment by SahibYar** [comment]
have you seen this ?
https://github.com/quic-go/quic-go/tree/master/example

**Comment by kehiy** [comment]
> have you seen this ? https://github.com/quic-go/quic-go/tree/master/example
> 
> And these https://github.com/quic-go/quic-go/tree/master#running-a-server https://github.com/quic-go/quic-go/tree/master#running-a-client

Thank you!

**Comment by kehiy** [comment]
> Thank you for the pointers@SahibYar!
> 
> I'm going to close this issue, since we have plenty of documentation (just rewrote large parts of it this month!).

we are waiting for this. :heart_eyes:
