### ISSUE TITLE
Still complaining about UDP receive buffer size even though net.core.rmem_max has been increased

### ISSUE THREAD

**Issue by timkgh** [quic-go/quic-go#3923]
quic-go v0.35.1 still complains about the UDP receive buffer size on Ubuntu 22.04.2 LTS with kernel 5.19.0-45-generic even though:

```
> sysctl net.core.rmem_max
net.core.rmem_max = 2500000
```

`2023/06/26 11:44:13 failed to sufficiently increase send buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details.`

This is running [dnsproxy](https://github.com/AdguardTeam/dnsproxy) straight up on the host, not in a container.

**Comment by jfgiorgi** [comment]
The error is about the send buffer `net.core.wmem_max` not the receive buffer.

The help page should be updated.

**Comment by marten-seemann** [comment]
Thank you @jfgiorgi! I updated the wiki page: https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes

**Comment by timkgh** [comment]
That was it. Thank you.
