### ISSUE TITLE
android cronet and android grpc+quic

### ISSUE THREAD

**Issue by vtolstov** [quic-go/quic-go#3925]
hi, i'm try to use android grpc client with quic (cronet)
but it fails to connect. 
I have a test golang grpc+quic server and it works fine with golang grpc+quic client.
Do you know what alpn i need to specify on server side to support android grpc+quic clients?

**Comment by otbutz** [comment]
I though that gRPC over QUIC isn't formalized yet? But it's almost certainly blocked by #2266

**Comment by marten-seemann** [comment]
The ALPN is the same on the client and server side, you'll need to use whatever the client uses. 

@otbutz is probably right that HTTP trailers would be a requirement to make this work though. Help on #2266 would be highly appreciated!
