### ISSUE TITLE
Make quic-go more STUN friendly

### ISSUE THREAD

**Issue by bt90** [quic-go/quic-go#3929]
The QUIC protocol is ideal for P2P applications which was a major factor in the adoption of quic-go for syncthing and libp2p.

As already discussed during the design phase of the new connection establishment API(see https://github.com/quic-go/quic-go/issues/3727#issuecomment-1477371806) syncthing and probably others need a better way to integrate STUN.

While it's easy to pass an existing PacketConn in order to send non-QUIC data, there's noch such mechanism yet to receive non-QUIC data.

With added GSO support in v0.36.0 and GRO on the horizon, solutions like https://github.com/AudriusButkevicius/pfilter/ are becoming less viable.

see also https://github.com/syncthing/syncthing/issues/8930

**Comment by marten-seemann** [comment]
Related discussion: https://github.com/quic-go/quic-go/issues/3727#issuecomment-1477409433. Let's continue the discussion here, now that we have the new `Transport`. 

Pinging @AudriusButkevicius @calmh @ydnar @zllovesuki @tobyxdd, who were all involved in that discussion.

The QUIC packet header was designed to make it possible to demultiplex with common protocols: https://github.com/quicwg/base-drafts/issues/426. We introduced the "QUIC bit" (0x40), which is set to 1 in both Short Header and Long Header packets: https://github.com/quicwg/base-drafts/issues/426. While this is not a version-independent property, it holds for both QUIC v1 and QUIC v2.

We could make it possible for users of a `Transport` to get access to packets that don't have the QUIC bit set. Would that solve your use case?

---

I can see two ways this could be implemented:
1. Add a `Transport.ReadNonQUICPacketFrom(p []byte) (int, net.Addr, error)` method (suggestions for a better name would be appreciated). Internally, this method would read packets from a channel. After the first call to this function, the `listen` Go routine would add non-QUIC packets to this channel (so we only create the channel if know that there's actually a consumer), dropping them if the channel overflows.
2. Add a callback to the the `Transport`: `HandleNonQUICPacket(b []byte, net.Addr)`. If set, the `listen` Go routine would call this callback with non-QUIC packets. It's the applications responsibility to process the packet quickly and not block the run loop.

Tradeoffs:
* (1) is arguably the more idiomatic API
* (1) requires an additional copy into the user-provided buffer
* (2) doesn't require a copy, but wouldn't allow us to reuse the buffer, effectively leading to an extra allocation for every non-QUIC packet

Given these tradeoffs, I'm leaning towards (1). Thoughts? Anything else we should consider here?

**Comment by AudriusButkevicius** [comment]
What about providing a net.PacketConn, that also supports writing etc, that writes to the real transport, and a config option in the transport to adjust the buffer size?
```
t := Transport {
   NonQuicPacketBufferSize: 1 << 20,
}
conn := t.GetNonQicPacketConn()
```


Both of the proposed APIs still require you to keep a handle on the write side of things, so this would solve that.

**Comment by marten-seemann** [comment]
Would this allow us to drop the `OptimizeConn` function? One thing you wouldn't be able to do with the new API is have a way to _only_ inject packets (but not read packets), but maybe we can live with that?

**Comment by ydnar** [comment]
What if handling non-QUIC packets was the responsibility of the caller, via their own `net.PacketConn` implementation?

This package could provide a helper `func IsQUIC(b []byte)` to ease that process.

**Comment by ydnar** [comment]
Or this package could provide a `PacketConn` type that wraps/implements `net.PacketConn` plus `ReadQUICFrom()` that `Transport` would use if present.

**Comment by bt90** [comment]
If we only look at the STUN use case, both approaches would work. The question is if someone would want to demultiplex a protocol with more traffic. The first proposal might drop packets if the channel overflows.

You also mentioned that the second proposal suffers from more allocations because quic-go can't reuse the buffer. Wouldn't it be better to split the burden of buffer reuse and allow the non-QUIC side to provide its own buffer?

**Comment by marten-seemann** [comment]
> You also mentioned that the second proposal suffers from more allocations because quic-go can't reuse the buffer. Wouldn't it be better to split the burden of buffer reuse and allow the non-QUIC side to provide its own buffer?

How would the API look like?

**Comment by bt90** [comment]
I've no real insight on the internals of quic-go and I'm not a go developer but you're reusing buffers by pooling them? Can't we use a dedicated pool or a second pooled buffer for non-QUIC consumers and transfer the content to that buffer? At least if the intention is to avoid concurrent access.

**Comment by marten-seemann** [comment]
I don't really want to expose quic-go's buffer pool to the outside world. If we want to make pooling possible, the user needs to be able to pass the buffer into quic-go.

> The first proposal might drop packets if the channel overflows.

To be honest, this is probably not as bad. There's a lot of places in the networking stack where packets are dropped when a queue overflows, this would just be one more.

**Comment by ydnar** [comment]
> What about providing a net.PacketConn, that also supports writing etc, that writes to the real transport, and a config option in the transport to adjust the buffer size?
> 
> ```
> 
> t := Transport {
> 
>    NonQuicPacketBufferSize: 1 << 20,
> 
> }
> 
> conn := t.GetNonQicPacketConn()
> 
> ```

This is probably the most sane proposal. I'd bikeshed it to `(*Transport).UnknownPacketConn` or `(*Transport).OtherPacketConn`, but it makes sense for multiplexed reads/writes. 

If a caller grabs this PacketConn, would Transport implicitly start a server?

**Comment by marten-seemann** [comment]
> If a caller grabs this PacketConn, would Transport implicitly start a server?

There's no need to start a server, all we need to do is start listening on the connection.

I'm wondering if we can find an API that fixed the problem I described in https://github.com/quic-go/quic-go/issues/3911#issuecomment-1610361132 (the last point about the `WriteTo` method).

**Comment by marten-seemann** [comment]
#3992 is a draft implementation of (1) without any configuration option for the buffer size.

**Comment by bt90** [comment]
@marten-seemann any ETA for the next release?

**Comment by marten-seemann** [comment]
Some time next week probably. The milestone is almost done: https://github.com/quic-go/quic-go/milestone/20

Any reason to release early? Are you waiting for this release?

**Comment by bt90** [comment]
I think the syncthing maintainers are in no hurry, but it wouldn't hurt to have a release that works with go 1.21 and avoids the minefield of having to adapt the current packet filtering to the GSO changes.

**Comment by calmh** [comment]
No rush on my part. With this merged we can do our change with the dependency pointing at `main`, and we can just point it at a real quic-go release before *we* release.

**Comment by calmh** [comment]
Thanks for all the work!

**Comment by marten-seemann** [comment]
For anyone still subscribed to this issue, there's a proposal to change this API to allow for custom non-QUIC packet detection logic: https://github.com/quic-go/quic-go/pull/4668#issuecomment-2456634134
