### ISSUE TITLE
old link in error message on failed increase of send buffer size

### ISSUE THREAD

**Issue by t-hofmann** [quic-go/quic-go#3930]
The link in the error message points to the old location:

"failed to sufficiently increase send buffer size (was: 208 kiB, wanted: 2048 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size for details."

There the new location is mentioned:
https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes

**Comment by marten-seemann** [comment]
#3924
