### ISSUE TITLE
Caddy and quic warns about UDB Buffer Sizes - Windows ?

### ISSUE THREAD

**Issue by wazerstar** [quic-go/quic-go#3932]
So I'm getting this warning on Windows 

2023/06/28 09:52:58.329 ←[34mINFO←[0m connection doesn’t allow setting of send buffer size. Not a *net.UDPConn?

I made a thread at caddy forum

https://caddy.community/t/beta-v2-7-0-beta-2-warns-send-buffer-size-during-startup/20326

The warning provides a link
https://github.com/quic-go/quic-go/wiki/UDP-Receive-Buffer-Size

So I read the link and in the link that quic refers to has changed URL, no biggie, there's a alternative link in that link.

It does not mention anything about the windows system and how to change the udp buffer sizes ?
It does not mention anything about the windows system and how to check what the values are?

I found these value on the net, added them to the system, rebooted and ran caddy again.. quic still gives a warning about it, tho I read it as it cannot change the settings if needed but what if its changed now and how do I check if its indeed fixed?

Registry file I created and saved as a file.reg and ran.

```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\AFD\Parameters]
"DefaultReceiveWindow"=dword:00250000
"DefaultSendWindow"=dword:00250000
```

**Comment by marten-seemann** [comment]
You're running into this line here: https://github.com/quic-go/quic-go/blob/da298d09e159fd545a3a90bd54771aabfe9e9162/sys_conn_buffers.go#L15-L18

There's nothing you can do regarding the receive buffers if the connection doesn't expose the `SetReadBuffer` method. This is a bug on Caddy's side by not providing a *net.UDPConn (but probably a wrapped one that doesn't expose that method).

**Comment by wazerstar** [comment]
> You're running into this line here:
> 
> https://github.com/quic-go/quic-go/blob/da298d09e159fd545a3a90bd54771aabfe9e9162/sys_conn_buffers.go#L15-L18
> 
> There's nothing you can do regarding the receive buffers if the connection doesn't expose the `SetReadBuffer` method. This is a bug on Caddy's side by not providing a `*net.UDPConn` (but probably a wrapped one that doesn't expose that method).

Okay I will refer this to the dev's at caddy forum.

**Comment by mholt** [comment]
Thanks for the heads-up.

That's strange, we actually do implement that method here:

https://github.com/caddyserver/caddy/blob/119e8794bcbda80ca337c1bb6164718e1490cc4f/listeners.go#L672-L700

I will have to see why the type assertion is failing. Maybe we need pointer receivers?

**Comment by jpds** [comment]
I also observed this error with the Caddy beta in a FreeBSD jail (which had the recommended `sysctl` setting configured on the host box). Will verify if the incoming PRs resolves this (or if it's a jail restriction).

**Comment by mholt** [comment]
Haven't had a chance to test it myself, but it should be fixed now with @WeidiDeng's recent PR that was just merged.

**Comment by jpds** [comment]
Deployed - error has gone away on FreeBSD :+1:

**Comment by mholt** [comment]
Weidi's a wizard.
