### ISSUE TITLE
use connected UDP sockets

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#3937]
It would be nice if we could use connected UDP sockets (see this excellent CloudFlare blog post: https://blog.cloudflare.com/everything-you-ever-wanted-to-know-about-udp-sockets-but-were-afraid-to-ask-part-1/) to send packets. This will allow us to reduce the cost of the route lookup in the `sendmsg` path. It might also allow us to accurately determine if GSO is supported (#3911).

Here's how it could work:
* The transport listens on an unconnected UDP socket (opened with reuseport), and uses this socket to send out Retry packets, Version Negotiation packets, etc.
* Once we accept a connection, we open a connected UDP socket on top of the unconnected. We then enable GSO on that socket.

Open questions:
* How do we make sure that the connected socket doesn't receive any packets. It would be nice if all packets would still be received by the `Transport.listen` Go routine. eBPF?
* What happens if there are multiple QUIC connections on the same 4-tuple? 2 options:
     * Don't use a connected socket for all but the first QUIC connection.
     * Keep a map of sockets by 4-tuple, and reuse the socket for all of them.
* Are we ok with the increased fd usage? Using a single fd for all QUIC connections was a really nice property.

**Comment by joliveirinha** [comment]
Another point to add here, imo, is the fact how the kernel tracks outgoing UDP connections and the limits it imposes on the open file descriptors. 
You can read more about it here: https://blog.cloudflare.com/how-to-stop-running-out-of-ephemeral-ports-and-start-to-love-long-lived-connections/ (another good blog post :) )

But in summary, another good advantage of unconnected socket is that we can theorically have a lot of open QUIC connections, while with connected sockets we are restricted to the epheremal port range. 
This is even more concerning if you take into consideration the server side, which may be running other software that is sharing that "space".

**Comment by marten-seemann** [comment]
After speaking with a number of implementers of other QUIC stacks at IETF 117, it seems like the fact that it's not possible to have a receive-only socket (without doing eBPF) has prevented most implementations from adoption this approach. The use of GSO also reduces the per-packet lookup cost, since the entire batch is sent to the same remote address.

**Comment by zhuoxikai** [comment]
Hi! I want to use connected udp sockets in quic-go and try to modify the source code. I can`t understand what meaning of `it seems like the fact that it's not possible to have a receive-only socket (without doing eBPF) has prevented most implementations from adoption this approach`.  can you explain it ? and why you give up implement the connected udp sockets?  Thanks.
