### ISSUE TITLE
compile failed: no qtls.Alert in v0.36.1

### ISSUE THREAD

**Issue by iwind** [quic-go/quic-go#3938]
After upgrade to latest tag v0.36.1, go120.go can not compile, some qtls.* types can not find in github.com/quic-go/qtls-go1-20 v0.3.0 (latest tag):

type (
   Alert = qtls.Alert
   CipherSuiteTLS13 = qtls.CipherSuiteTLS13
  ConnectionState = qtls.ConnectionStateWith0RTT
  ConnectionState = qtls.ConnectionStateWith0RTT
  ...
)

may be you should publish latest qtls-go1-20 to fix the issue.

**Comment by marten-seemann** [comment]
Maybe you should use the search. This is the 4th time someone has opened this issue.
