### ISSUE TITLE
Will there be a way to close the local listener created by the customized RoundTripper.Dial ASAP?

### ISSUE THREAD

**Issue by lifenjoiner** [quic-go/quic-go#3945]
QUIC self created is closed ASAP, while other staled may persist until having triggered some errors or after being replaced by a new instance for a while.
https://github.com/quic-go/quic-go/blob/0fe21c7d6fc29a1f493a751ea524c3c9428f9848/transport.go#L250-L257

**Comment by marten-seemann** [comment]
I don't understand the problem. What are you suggesting?

**Comment by lifenjoiner** [comment]
Not a bug. But prefer to:
having a way to close the `udpConn` created by user defined `Dial` of a `RoundTripper`, like those created by `DialAddrEarly`/`DialAddr`.

Why?
I tested [http3 clients](https://github.com/DNSCrypt/dnscrypt-proxy/blob/a352a3035c99d583b82029bd96653ae75572e3b1/dnscrypt-proxy/xtransport.go#L260-L295), which wrapped the `RoundTripper` as a normal http client.
We prefer the client to be reused, and manages its connections by itself: close the unusable connections in time.
In fact, when I added a logger at [when the connection is closed](https://github.com/quic-go/quic-go/blob/0fe21c7d6fc29a1f493a751ea524c3c9428f9848/client.go#L228-L229), I saw the `udpConn` persists in consonance with the above code. Not like TCP, the connection is partially closed, leaving the `udpConn` listening.
The http3 client is staled, and we must instantiate a new one. So, I would like to close the `udpConn` ASAP, like using the default `RoundTripper`.

In the other hand, if the `udpConn` is created outside the `RoundTripper`, users would prefer the keep it listening.

**Comment by marten-seemann** [comment]
I’m sorry, I still having a lot of problems parsing your post., so I don’t really understand what you’re asking for.

You can always close the `RoundTripper` yourself, it has a `Close` method.

**Comment by lifenjoiner** [comment]
Normally, Yes.

I guess this is in the same scenario where a http3 client acts as a proxy, like https://github.com/quic-go/quic-go/pull/3943. We can reproduce it by the same example.
In these scenarios, monitor and close the `RoundTripper` is not easy.

I don't have short examples. For now, only the [dnscrypt-proxy](https://github.com/DNSCrypt/dnscrypt-proxy/blob/a352a3035c99d583b82029bd96653ae75572e3b1/dnscrypt-proxy/xtransport.go#L260-L298).
To reproduce:
1. You need to compile the latest codes, which uses the latest quic-go.
2. Config it with: [http3 = true](https://github.com/DNSCrypt/dnscrypt-proxy/blob/a352a3035c99d583b82029bd96653ae75572e3b1/dnscrypt-proxy/example-dnscrypt-proxy.toml#L104), turn of [cache](https://github.com/DNSCrypt/dnscrypt-proxy/blob/a352a3035c99d583b82029bd96653ae75572e3b1/dnscrypt-proxy/example-dnscrypt-proxy.toml#L405), and specify only DoH3 upstream servers by [server_names](https://github.com/DNSCrypt/dnscrypt-proxy/blob/a352a3035c99d583b82029bd96653ae75572e3b1/dnscrypt-proxy/example-dnscrypt-proxy.toml#L32). You may change the default listening [port](https://github.com/DNSCrypt/dnscrypt-proxy/blob/a352a3035c99d583b82029bd96653ae75572e3b1/dnscrypt-proxy/example-dnscrypt-proxy.toml#L42), if it is not available.
3. For reference, there are 3 DoH3 servers on my side: ams-doh-nl, doh-crypto-sx and sth-doh-se.
4. Set `QUIC_GO_LOG_LEVEL=info`.
5. Run the dnscrypt-proxy.
6. Query some domains and test.
7. When there is "[Connection %s closed](https://github.com/quic-go/quic-go/blob/de8d7a32b88688b9f85ccdab2f6e1a11bbeaa410/connection.go#L691)" after a query succeeded with a server:
7.1. you can observe it with some other tool and see the corresponding port listening persists, for this;
7.2 and the next query on that server will be `NETWORK_ERROR` for https://github.com/quic-go/quic-go/pull/3943.

**Comment by marten-seemann** [comment]
I still don't understand this issue. If you think there's a bug, we'll need a short reproducer. Please feel free to open a new issue.
