### ISSUE TITLE
Using OptimizeConn will cause future SetWriteBuffer calls to fail

### ISSUE THREAD

**Issue by MarcoPolo** [quic-go/quic-go#3947]
The transport code docs say (https://github.com/MarcoPolo/quic-go/blob/master/transport.go#L33)

> 	// Calling WriteTo is only valid on the connection returned by OptimizeConn.

My understanding is that means if I want to use this packet conn for `WriteTo` later I need to manually call `OptimizeConn` on the conn before giving it to the `Transport`. However, if I do that the Transport fails to set the SendBuffer size and logs the error:

> connection doesn't allow setting of send buffer size. Not a *net.UDPConn?. See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.

This is probably because the returned connection from `OptimizeConn` doesn't implement the correct interface (e.g. `SyscallConn` or `SetWriteBuffer` methods). Maybe it would make sense to set the buffer sizes earlier as part of OptimizeConn?

While I'm here, it would be nice if `OptimizeConn` returned a concrete type that implements `PacketConn`. That way I can keep a reference to `OptimizedConn` and only use that for my `WriteTo` calls. Since otherwise I just have a `PacketConn` that is unclear whether or not it is safe to `WriteTo` to.

**Comment by MarcoPolo** [comment]
If we agree on a solution, I'm happy to take up the fix.

**Comment by marten-seemann** [comment]
> Maybe it would make sense to set the buffer sizes earlier as part of OptimizeConn?

Agreed, this makes sense.

Alternatively, we could get rid of `OptimizeConn` altogether, and instead add a `WriteTo` method to the `Transport`. You'd then set your `net.PacketConn` on the `Transport`, the `Transport` would enable all the optimizations it wants. From that point on, it's invalid to call _any_ methods on the connection. In case you want to send packets yourself, you need to call `Transport.WriteTo`. This would integrate somewhat nicely with how we would read non-QUIC packets from the connection (https://github.com/quic-go/quic-go/issues/3929).

**Comment by MarcoPolo** [comment]
> Alternatively, we could get rid of OptimizeConn altogether, and instead add a WriteTo method to the Transport

I think that makes sense to me.

I'm assuming it's not safe for a caller to use `Transport.Conn` directly. Should there be a comment to that effect? Or maybe make it private (would require a constructor).

**Comment by marten-seemann** [comment]
> I'm assuming it's not safe for a caller to use `Transport.Conn` directly. Should there be a comment to that effect? Or maybe make it private (would require a constructor).

It's not modified, there's a separate (unexported) `conn` field that the transport uses: https://github.com/quic-go/quic-go/blob/f97c9bf88cd10ea6738a7f7e69c7da56f5f820b5/transport.go#L75

This API is modeled after the `http.Server` in the standard library. Not sure if that's actually the best solution, a constructor, which would then take a `TransportConfig` struct, would be an alternative. It was an easy way to avoid introducing yet another config struct, so that's what we went with for now.

**Comment by MarcoPolo** [comment]
> It's not modified, there's a separate (unexported) conn field that the transport uses:

As a user, should I use `Transport.Conn.WriteTo` or should I maintain my own reference to the underlying packet conn (after calling OptimizeConn) and call `pConn.WriteTo`? It's unclear from the docs that I can use `Transport.Conn.WriteTo` directly (it won't be modified).

**Comment by marten-seemann** [comment]
It doesn’t make any difference, since the `Transport.Conn` is not modified.

That said, I think we should change the API for the next release. `OptimizeConn` shouldn’t be necessary any more, if we add a `Transport.WriteTo`:
```go
// WriteTo sends a packet on the connection handled by this Transport.
func (*Transport) WriteTo(b []byte, addr net.Addr) (int, error)
```
