### ISSUE TITLE
caddy with modified quic-go

### ISSUE THREAD

**Issue by MardenSSS** [quic-go/quic-go#3976]
Caddy now uses the quic-go source library to support HTTP3 services by default. Now I want to modify some content of quic-go and run the modified quic-go in caddy. How should I do it? Can you give me some help?

**Comment by Glonee** [comment]
Fork quic-go, modify it, and modify caddy's source code to import your modefied version.

**Comment by marten-seemann** [comment]
What @Glonee said.
