### ISSUE TITLE
Content-Length on HTTP/3 responses

### ISSUE THREAD

**Issue by semihalev** [quic-go/quic-go#3986]
The standart `net/http` library adds `Content-Length` header automatically. Are there any reason to set this manually?

**Comment by marten-seemann** [comment]
See https://github.com/quic-go/quic-go/pull/3954.

**Comment by marten-seemann** [comment]
To add some more context: If I understand correctly, this code in the standard library only works if the response is small. For larger responses, it still makes sense to manually set it (or really, if you know the size, set it).

**Comment by semihalev** [comment]
Yes. If It's under the 2kB, adds auto. Its about chunk size. If under the chunk size adding auto.

**Comment by semihalev** [comment]
Both HTTP/1 and HTTP/2 add this auto. I think good idea add this for HTTP/3 too.
