### ISSUE TITLE
Simplify the http3 client caching key rule

### ISSUE THREAD

**Issue by chaosmatrix** [quic-go/quic-go#3996]
https://github.com/quic-go/quic-go/blob/469a6153b6798780bf90e8be37f197d0fcb18af2/http3/request_writer.go#L216-L235

```go
func authorityAddr(req *http.Request) (addr string) {
	if req == nil || req.URL == nil {
		return ""
	}
	return req.URL.Scheme + ":" + req.URL.Host
}
```

The reasons are:
1. use `scheme` + `hostname` + `port`(or default by scheme)  (+ `proxy` if support) can associate a http3 request to a quic connection
2. we don't need to care about the `hostname` is valid ascii or fqdn, it just needs to be a non-empty string
3. a simple benchmark result show that the performance gain is : `114.1 ns/op` -> `17.62 ns/op`
4. the most important thing is the code is more concise

**Comment by marten-seemann** [comment]
It's not only used as a cache key though, it's also used as an input to `quic.DialAddr`.
