### ISSUE TITLE
optional feature: avoid sending Initial ACK frame after seeing Handshake packets from server

### ISSUE THREAD

**Issue by gaukas** [quic-go/quic-go#4007]
An `Initial` packet containing only `ACK, PADDING` frames is always being sent by the client, even if the server sends the `CRYPTO` frame containing the ServerHello in an `Initial` packet followed by a `Handshake` packet as coalesced, inside one single UDP datagram instead (e.g., Caddy). 

Other QUIC client implementations including Firefox and Chrome will only send `Initial` `ACK` frames only if the server responded ServerHello in `Initial` packet space with no `Handshake` packets in the same UDP datagram.

I wonder if is this an intended behavior for quic-go with a specific reason or not? Thanks for your time. 

----

Related RFC section: 

> [4.9.1. ](https://datatracker.ietf.org/doc/html/rfc9001#section-4.9.1)[Discarding Initial Keys](https://datatracker.ietf.org/doc/html/rfc9001#name-discarding-initial-keys)
> Packets protected with Initial secrets ([Section 5.2](https://datatracker.ietf.org/doc/html/rfc9001#initial-secrets)) are not authenticated, meaning that an attacker could spoof packets with the intent to disrupt a connection. To limit these attacks, Initial packet protection keys are discarded more aggressively than other keys.
> 
> The successful use of Handshake packets indicates that no more Initial packets need to be exchanged, as these keys can only be produced after receiving all CRYPTO frames from Initial packets. Thus, a client MUST discard Initial keys when it first sends a Handshake packet and a server MUST discard Initial keys when it first successfully processes a Handshake packet. Endpoints MUST NOT send Initial packets after this point.
> 
> This results in abandoning loss recovery state for the Initial encryption level and ignoring any outstanding Initial packets.

**Comment by gaukas** [comment]
In the case where this `Initial` packet is considered unexpected, it neither breaks the quic connection nor is essential to the quic connection. The communication could be established normally with or without this packet. 

Essentially this `Initial ACK` has no effect when a server is not responding in `Initial` packet space.

**Comment by gaukas** [comment]
Code to replicate this behavior is attached. 

```go
package main

import (
	"context"
	"crypto/tls"
	"net"
	"time"

	"github.com/quic-go/quic-go"
)

func main() {
	udpLaddr, err := net.ResolveUDPAddr("udp4", ":0")
	if err != nil {
		panic(err)
	}

	udpConn, err := net.ListenUDP("udp4", udpLaddr)
	if err != nil {
		panic(err)
	}

	udpRaddr, err := net.ResolveUDPAddr("udp4", "quic.tlsfingerprint.io:443")
	if err != nil {
		panic(err)
	}

	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second) // 3s handshake timeout
	defer cancel()
	_, err = quic.Dial(ctx, udpConn, udpRaddr, &tls.Config{
		ServerName: "quic.tlsfingerprint.io",
	}, &quic.Config{})
	if err != nil {
		panic(err)
	}

	select {}
}
```

![image](https://github.com/quic-go/quic-go/assets/9084527/b7c661db-d5ee-4faa-b610-e851c1a62706)

**Comment by gaukas** [comment]
Some quick experiments showed that neither Firefox nor Google Chrome (presumably Chromium) sends this `Initial ACK` frame, unless the server sends its ServerHello in `Initial` packet space (`www.google.com` does this).

![image](https://github.com/quic-go/quic-go/assets/9084527/ddb02807-be07-42d4-a6ad-706af7d26e65)
![image](https://github.com/quic-go/quic-go/assets/9084527/b0566bf9-0eee-4d27-b6c9-e7b790a76c54)

**Comment by marten-seemann** [comment]
Are you sure the server didn't send an Initial packet as part of a coalesced packet? It's not possible to send an ACK if there's nothing to acknowledge.

**Comment by gaukas** [comment]
@marten-seemann I think you are right. The server DOES send an Initial Packet as part of the coalesced packet. 

Are you aware of any compelling reason for these well-known implementations to be not ACKing to the InitialPacket?

**Comment by gaukas** [comment]
For your reference: The first packet received from the server is made of two packets, one in `Initial` with ServerHello and one in `Handshake` with EncryptedExtensions. 

And thank you for responding so quickly!

**Comment by marten-seemann** [comment]
RFC 9001 says:
> a client MUST discard Initial keys when it first sends a Handshake packet and a server MUST discard Initial keys when it first successfully processes a Handshake packet

The only purpose of this ACK is therefore to allow the server to generate an RTT measurement.

**Comment by gaukas** [comment]
Just before this line: 

> The successful use of Handshake packets indicates that no more Initial packets need to be exchanged, as these keys can only be produced after receiving all CRYPTO frames from Initial packets.

I would interpret this as "once client sees a `Handshake` packet from the server, no more Initial packet needs to be sent (and therefore dropping the ACK)". Perhaps we could make this an optional configurable feature? 

What's your opinion on this?

**Comment by marten-seemann** [comment]
That's not correct. See the sentence that I quoted, which exactly specifies when Initial keys are dropped.

**Comment by gaukas** [comment]
I understand what you were saying, the initial keys are dropped (so no more Initial Keys CAN be sent) exactly after successfully sending a Handshake packet. 

However, I would interpret "no more Initial packets need to be exchanged" as "you MAY, but you don't have to exchange any initial packets". It is weaker than "a client MUST discard Initial keys". And this also aligns with what we see from modern web browsers.

**Comment by marten-seemann** [comment]
> "you MAY, but you don't have to exchange any initial packets".

That's correct, and exactly what we're doing. As I mentioned above, giving the server the chance to generate an RTT measurement has value, which is why we send this ACK.

**Comment by gaukas** [comment]
Would you welcome a PR adding a switch to turn off this behavior?

**Comment by marten-seemann** [comment]
Why would you want to make this configurable? I see no advantage in not sending an ACK.

**Comment by gaukas** [comment]
It is more of a fingerprint-ability issue. Like uTLS, we are also creating an experimental uQUIC which is based on quic-go to prevent [QUIC fingerprinting](https://quic.tlsfingerprint.io/) as demanded by censorship circumvention community. 

Therefore we would like to be able to at least replicate all plaintext communications, i.e., everything sent in `Initial` packet space. 

If you don't feel it would be a useful addition, we would keep this feature solely in uQUIC.

**Comment by marten-seemann** [comment]
I see, thanks for adding some context here.

What's the reasoning behind not sending the ACK in Chrome and Firefox?

**Comment by gaukas** [comment]
> reasoning behind not sending the ACK in Chrome and Firefox? 

Unfortunately I don't have an answer for that, it could be just one of their standard-compliant nuances which contributes to their special fingerprints.

**Comment by marten-seemann** [comment]
I'm going to close this issue. There are tons of fingerprinting opportunities in a QUIC stack: frame ordering, transport parameter ordering, greasing values used, just to name a few that apply to the very first packet sent. There's a lot more after that.

quic-go has never tried to hide its identity, and replicating Chrome's / Firefox's behavior in all details what be massive endeavor (and a moving target).
