### ISSUE TITLE
Support for custom tls.Config with ListenAndServe function?

### ISSUE THREAD

**Issue by Thelolguy1** [quic-go/quic-go#4010]
Hello, I have an unusual use-case of this library in which I need to operate a HTTP3 server with custom certificate checking (i.e. InsecureSkipVerify and VerifyPeerCertificate). 

Unfortunately, it seems that the ListenAndServe [function](https://github.com/quic-go/quic-go/blob/v0.31.1/http3/server.go#L691) cannot be operated with a custom tls.Config, and using the functions under the Server type would not supply the necessary TCP listeners either. 

Currently, [my workaround](https://github.com/Thelolguy1/phome/blob/af85bf675eb2d7dfbad713417167ca4010c938bc/phomeCore/Connection.go#L40) is to modify the standalone ListenAndServe function to take my own tls.Config settings and listen to the appropriate TCP and UDP ports as necessary.

Is this correct and safe, or is there a better alternative?

**Comment by Glonee** [comment]
You can create a `http3.Server`. It has a `ListenAndServe` method that you want.

**Comment by Thelolguy1** [comment]
As far as I can tell, that only sets up listeners for UDP, which would only be half of what the standalone function does.

**Comment by marten-seemann** [comment]
For the TCP part, you can use the standard library. The top-level functions are only convenience wrappers anyway.

**Comment by Glonee** [comment]
A sample example
```go
h3server := http3.Server{
	Handler:   handler,
	TLSConfig: tlsCfg,
}
server := http.Server{
	Handler: http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		h3server.SetQuicHeaders(w.Header())
		h3server.Handler.ServeHTTP(w, r)
	}),
	TLSConfig: h3server.TLSConfig,
}
go func() {
	server.ListenAndServeTLS("", "")
}()
h3server.ListenAndServe()
```

**Comment by Thelolguy1** [comment]
Much appreciated @Glonee, thank you.

**Comment by Thelolguy1** [comment]
@Glonee Out of curiosity, would you happen to know why your example throws
`WARNING: Could not save SSL session data for socket 3`
when connecting with wget?
