### ISSUE TITLE
Alt-Svc: add the ability to fully specify <alt-authority> (not only the port)

### ISSUE THREAD

**Issue by oliverpool** [quic-go/quic-go#4024]
Currently the [`Alt-Svc` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Alt-Svc) only contains the port (eg `h3=":443"; ma=2592000`):
https://github.com/quic-go/quic-go/blob/05db808f72b9183653cfce97d6c235108bb18ee6/http3/server.go#L368

**It would be nice to be able to specify a host as well.**

**Usecase**: I want to have an http3 server listening only on IPv6 (while http2 is served on IPv6, with an IPv4 fallback using [snid](https://www.agwa.name/blog/post/using_sni_proxying_and_ipv6_to_share_port_443)): `h3="[::1]:443"; ma=2592000`

**Possible implementation**: add an optional `AltAuthority` string field (and deprecate the `Port` field) on the `Server` struct.

**Comment by marten-seemann** [comment]
That seems like a pretty niche use case. Why do you want to do that?

In most deployment, the Alt-Svc solution is being replaced by signaling these capabilities in DNS. Would that work for your use case?

**Comment by oliverpool** [comment]
> Why do you want to do that?

I want to host multiple services on a single machine. Each service gets a unique IPv6 (so they can listen to all the ports they want), but have to share the IPv4 (where [snid](https://www.agwa.name/blog/post/using_sni_proxying_and_ipv6_to_share_port_443) is forwarding the traffic to the right service). I guess this can only work for TCP connections.

> Alt-Svc solution is being replaced by signaling these capabilities in DNS

I didn't know about that, thanks for pointing it out!
Finding how widely it is supported in quite confusing, however:
- the links of https://serverfault.com/a/1075524 appear stalled (Chrome 2021 "I will be updating this thread with a heads up before any significant experiment rollout steps." - Firefox "Depends on other issues")
- according to https://github.com/Fyrd/caniuse/issues/6091#issuecomment-982898862 it was shipped in Chrome 96 and Firefox 92

**Comment by oliverpool** [comment]
The HTTPS record is not supported by my DNS provider…

Anyway witting the AltSvc myself is not hard to write myself (especially since I only intend to support h3), so I am closing this issue.

FYI curl does not support my usecase as well https://github.com/curl/curl/issues/11737
