### ISSUE TITLE
about golang 1.21.0 error

### ISSUE THREAD

**Issue by xfengw** [quic-go/quic-go#4028]
# github.com/libp2p/go-libp2p/p2p/transport/quicreuse
C:\Users\Windows\go\pkg\mod\github.com\libp2p\go-libp2p@v0.29.0\p2p\transport\quicreuse\config.go:20:45: undefined: quic.VersionDraft29
C:\Users\Windows\go\pkg\mod\github.com\libp2p\go-libp2p@v0.29.0\p2p\transport\quicreuse\connmgr.go:186:22: undefined: quic.VersionDraft29
C:\Users\Windows\go\pkg\mod\github.com\libp2p\go-libp2p@v0.29.0\p2p\transport\quicreuse\connmgr.go:187:49: undefined: quic.VersionDraft29
C:\Users\Windows\go\pkg\mod\github.com\libp2p\go-libp2p@v0.29.0\p2p\transport\quicreuse\connmgr.go:255:14: undefined: quic.OptimizeConn
C:\Users\Windows\go\pkg\mod\github.com\libp2p\go-libp2p@v0.29.0\p2p\transport\quicreuse\listener.go:49:50: undefined: quic.VersionDraft29
C:\Users\Windows\go\pkg\mod\github.com\libp2p\go-libp2p@v0.29.0\p2p\transport\quicreuse\listener.go:92:53: conn.ConnectionState().TLS.ConnectionState undefined (type tls.ConnectionState has no field or method ConnectionState)
C:\Users\Windows\go\pkg\mod\github.com\libp2p\go-libp2p@v0.29.0\p2p\transport\quicreuse\quic_multiaddr.go:23:12: undefined: quic.VersionDraft29
C:\Users\Windows\go\pkg\mod\github.com\libp2p\go-libp2p@v0.29.0\p2p\transport\quicreuse\quic_multiaddr.go:38:19: undefined: quic.VersionDraft29

**Comment by marten-seemann** [comment]
Please stop the spam, @xfengw!
