### ISSUE TITLE
Possibly using the wrong `.SessionTicketsDisabled` field

### ISSUE THREAD

**Issue by MarcoPolo** [quic-go/quic-go#4029]
It seems like we're only using the `.SessionTicketsDisabled` field from the [initial tls.Config](https://github.com/quic-go/quic-go/blob/master/internal/handshake/crypto_setup.go#L359), but we should perhaps be using the field from the tls.Config we get for a specific client if we have  tls.Config.GetConfigForClient set. This would allow the server to support session tickets generally, but disable them for certain clients.

That said, I'm not sure if that's actually useful though. So it might also be okay if this wasn't supported.

I took a quick look at what would be required to change this, and I'm not sure it would be easy. The tls.Config for a specific client seems internal to `crypto/tls`.

**Comment by marten-seemann** [comment]
You're right. The only "clean" option would be wrapping `GetConfigForClient` and keeping track of which config is actually in use, which would add a lot of complexity.
This check should probably be performed inside the standard library, and I've opened https://github.com/golang/go/issues/62032 for that.

For now, quic-go can do an error assertion, so this error doesn't end up closing the connection.
