### ISSUE TITLE
CRYPTO_ERROR 0x12a (local): tls: failed to verify certificate: x509: cannot validate certificate for <IP>

### ISSUE THREAD

**Issue by folbricht** [quic-go/quic-go#4049]
In v0.38.1 (and a few versions before), the library doesn't set the ServerName in the tls.Config automatically anymore possibly leading to a failure to validate remote certs if those don't have IP SANs.

All calls to `setTLSConfigServerName(tlsConf *tls.Config, addr net.Addr, host string)` provide a blank host as transport.dial sets it to `""` in all cases like so `t.dial(ctx, addr, "", tlsConf, conf, false)`. This means that setTLSConfigServerName will set tls.Config.Servername to an IP address.

A workaround is to set set the ServerName in the tls.Config before calling Dial(). Was this change intentional?

**Comment by marten-seemann** [comment]
What’s your setup? Why do you need an empty server name?

**Comment by marten-seemann** [comment]
The logic was introduced intentionally, since crypto/tls only saves the session ticket if a ServerName is set. Arguably, this might be something that needs to be fixed in crypto/tls, but I believe the logic we introduced is equivalent to what crypto/TLS does when dialing in TCP.

**Comment by folbricht** [comment]
I was relying on the default behavior, like when a blank tls.Config is used to Dial, the hostname in the connection would become the Servername in the tls.Config. But I suppose in the new function signature `quic.DialEarly(ctx, udpConn, udpAddr, tlsConfig, config)` there isn't really a way to provide a hostname anymore so quic-go doesn't have a way to set it by default.

**Comment by folbricht** [comment]
`tls.Dial()` takes a dial address and uses that as ServerName if none is set already, while `tls.Conn()` does not. So the current way quic-go does it is similar to the latter. I'll update the client code to ensure it sets a name.
