### ISSUE TITLE
saving the datagram size in the session tickets breaks 0-RTT tests

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#4058]
After merging #4013, the 0-RTT datagram integration test takes 30s. The test still passes, but clearly there's something going wrong there.
I haven't debugged this, but this looks very much like we're running into a connection timeout somewhere.

@tanghaowillow, could you help debug and fix this?

**Comment by tanghaowillow** [comment]
@marten-seemann  OK, I'll have a look at this.
