### ISSUE TITLE
How to specify the source port number when a client wants to Dial to server

### ISSUE THREAD

**Issue by lakhalouahid** [quic-go/quic-go#4074]
I wonder if there is a way to specify the source port number for the function quic.Dial. I know that using the `net` package has a function called `DialUDP` allowing to specify the source port number when connecting to a server.

**Comment by marten-seemann** [comment]
You can construct a Transport with a UPDConn that you created yourself.

**Comment by lakhalouahid** [comment]
Thanks @marten-seemann for the feedback.
I tried to create a transport from UDPConn. But i didn't know how to do it properly because `transport.Dial` return the error: `INTERNAL_ERROR (local): write udp 127.0.0.1:44746->127.0.0.1:59951: use of WriteTo with pre-connected connection`
This is the part the code, i did use:

```
	tConn, err := net.DialUDP("udp", lAddr, rAddr)
	if err != nil {
		sugar.Debug("Could not create UDP connection: %v", err)
	}

	transport := &quic.Transport{Conn: tConn}

	conn, err = transport.Dial(ctx, rAddr, tlsConfig, quicConfig)
	if err != nil {
		sugar.Debug("Connect to quic server failed: ", err)
	}
```

**Comment by marten-seemann** [comment]
It’s all explained in the README.

**Comment by lakhalouahid** [comment]
Thanks @marten-seemann again. Actually, i did check the README, and i did just find a implementation for the server. But, i need to specify source port of the client. When defining the server, no client is connected to server so the transfer of net.UDPConn to quic.Connection will work, but how about the client if he already connected. And the problem, is that internally the function writeTo is called instead of write.

**Comment by marten-seemann** [comment]
Use ListenUDP instead of DialUDP. Just like it says in literally the first paragraph of the README.

**Comment by lakhalouahid** [comment]
Solved. Thank you @marten-seemann.
