### ISSUE TITLE
Hello, can you help me find out what causes the timeout: no recent network activity error?

### ISSUE THREAD

**Issue by P0larisiiiiii** [quic-go/quic-go#4075]
Hello, can you help me find out what causes the timeout: no recent network activity error?

I made sure that the server side is running normally. I am a beginner. This is the file I tried to write using echo.go. Please help me find out what is wrong.

package main

import (
	"context"
	"crypto/tls"
	"encoding/json"
	"fmt"

	"github.com/quic-go/quic-go"
	"io"
	"log"
	"time"
)

type MyData struct {
	HostName  string `json:"HostName"`
	Ip string `json:"Ip"`
	Port int `json:"Port"`
	DeadLine int `json:"DeadLine"`
}
var n int

func main() {

	data := MyData{
		HostName:"fjningde",
		Ip:"27.156.185.55",
		Port:15030,
		DeadLine:125,
	}
	tlsConf := &tls.Config{
		InsecureSkipVerify: true,
		//NextProtos:         []string{"crypto-setup"},
	}

	JsonData, err := json.Marshal(data)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf(string(JsonData))

	conn, err := quic.DialAddr(context.Background(),"127.0.0.1:6121",tlsConf,nil)
	if err != nil {
		fmt.Println(err)
		return
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()
	Stream, err := conn.OpenStreamSync(ctx)
	if err != nil {
		fmt.Println(err)
		return
	}

	n, err = Stream.Write([]byte(JsonData))
	if err != nil {
		fmt.Println(err)
		fmt.Println("write.err,10")
		return
	}
	fmt.Println("Bytes written:",n)

	buf := make([]byte, len(JsonData))
	_, err = io.ReadFull(Stream, buf)
	if err != nil {
		fmt.Println(err)

	}
	fmt.Printf("Client: Got '%s'\n", buf)

}

Return information after running:
{"HostName":"fjningde","Ip":"27.156.185.55","Port":15030,"DeadLine":125}Bytes written: 72
timeout: no recent network activity
Client: Got ''

**Comment by P0larisiiiiii** [comment]
I ensure that the data is not transmitted to the server. This is a proxy node reporting method. If the report is successful, someone will connect to the listening port of this server.

**Comment by P0larisiiiiii** [comment]
Also when I try to set the server to quic-go-master/example/main.go, NextProtos: []string{"h3"},
The same problem and error also occurred.

**Comment by P0larisiiiiii** [comment]
This is a screenshot of the packet capture I tried
121.40.106.52 is the server

[](url)
![QQ图片20230910201833](https://github.com/quic-go/quic-go/assets/134470493/506f3e2e-b518-467f-967e-5a9b04b13077)

**Comment by marten-seemann** [comment]
timeout: no recent network activity is a network timeout, meaning that the other peer didn't send any packets. Could be that they crashed, or some kind of connectivity issue.

**Comment by P0larisiiiiii** [comment]
Does this represent anything wrong with my code. Such a message was indeed transmitted to the server
