### ISSUE TITLE
Possible context leak in EarlyConnection.HandshakeComplete()

### ISSUE THREAD

**Issue by IrineSistiana** [quic-go/quic-go#4094]
Hi there,

Thanks for the great project.

In our project we found that some goroutines hang forever in EarlyConnection.NextConnection(). The EarlyConnection was created by quic.DialEarly, nothing special. No 0RTT data (We haven't implemented it yet.) So the code is simple like this:

```go
ec, err := quic.DialEarly(...)
// error handling
c := ec.NextConnection()
```

Sorry for not providing reproduction code. We can't reproduce it easily either.

We debug the code a bit. Think it might be because:

The handshake context is from context.Background(), so it has no timeout.

https://github.com/quic-go/quic-go/blob/9010cfd2bbc9da8c16a839a4b9494bfe3b6b9d41/connection.go#L483

The only way to cancel the handshake context is to call

https://github.com/quic-go/quic-go/blob/9010cfd2bbc9da8c16a839a4b9494bfe3b6b9d41/connection.go#L725-L726

from

https://github.com/quic-go/quic-go/blob/9010cfd2bbc9da8c16a839a4b9494bfe3b6b9d41/connection.go#L1282-L1285

It seems that if the subsequent handshake is never completed (due to network loss, etc...), the handshake context will never be canceled, the NextConnection() will block forever.

**Comment by marten-seemann** [comment]
> In our project we found that some goroutines hang forever in EarlyConnection.NextConnection(). The EarlyConnection was created by quic.Dial, nothing special. No 0RTT data (We haven't implemented it yet.

Why are you using `DialEarly` and `NextConnection` if you're not using 0-RTT?

**Comment by IrineSistiana** [comment]
This is a work around.  I'm using quic-go to implement a dns over quic client. Initially I used Dial. When I use my client to connect to a public dns server, there is a probability that the OpenStream() returns quic.Err0RTTRejected. When this happens, Dial() a new connection using the same Transport and calling OpenStream() on the new connection still returns this error, for a period of time. I can't say why I got this quic.Err0RTTRejected error. I guess it was because of a bug in the server side. But I find that NextConnection() can reset the connection state. So I use it as a workaround for now. Then I find that NextConnection() may never return.

**Comment by marten-seemann** [comment]
@IrineSistiana I think you're right. I haven't managed to reproduce it - it's actually really hard to make the handshake fail after 0-RTT rejection: 0-RTT rejection requires the EncryptedExtension TLS message to have been received, and it's usually bundled with the entirety of the server's first flight (including the Finished message). We also can't use a giant certificate and drop part of it, since the certificate isn't sent on the resumed connection.

What we should do is also block on the connection context, and maybe allow the user to pass in a context as well.
