### ISSUE TITLE
Usage of Address Validation Tokens and 0-RTT on Chromium-based devices

### ISSUE THREAD

**Issue by John-Athan** [quic-go/quic-go#4095]
This issue was originally opened as a [Caddy issue](https://github.com/caddyserver/caddy/issues/5822), however it likely fits better in here because Caddy just plugs into quic-go for all HTTP/3-related functionality.

I am currently running a very basic caddy server (Version 2.7.4) that serves static files from a directory:
```
<my-domain> {
    root * ./www
    templates
    encode zstd gzip
    file_server
}
```
HTTP/3 is working, and I see it being used across all clients that support it.

However I would like to make use of the 0-RTT functionality enabled in [Version 2.7.3](https://github.com/caddyserver/caddy/releases/tag/v2.7.3)
```
Significant HTTP/3 performance improvements (upstream in quic-go) including enabling 0-RTT. Caddy users should notice significantly better throughput for HTTP/3. Thanks for the fantastic work, @marten-seemann!
```

This version of Caddy uses quic-go version 0.37.1 and should therefore support 0-RTT.
I can only see 0-RTT being used by clients using the Firefox browser, though. Chromium-based clients will not try to send 0-RTT data for some reason. They will always do a full 1-RTT handshake before sending data, even when they could definitely use the 0-RTT packet type.

I also observed that, even though address validation tokens are sent after each successful reconnect, only Firefox uses these tokens during the next reconnect. Chromium-based browsers do not use the token at all.
Those same browsers are definitely capable of sending address validation tokens and 0-RTT packets because they will use them on other websites (e.g. fonts.google.com) without problems.

Is there something I am overlooking? Is QUIC's 0-RTT not supported on Chromium-based browsers yet? 
I would be happy to provide more information if needed, or if you point me into the right direction to get this working :)

**Comment by John-Athan** [comment]
Correction: 0-RTT works with recent versions of caddy (v2.7.4) and quic-go (>v0.37.5). Sorry for the confusion.
However, while after each successful connection establishment, a NEW_TOKEN frame containing an address validation token is sent, that token is not used inside the initial packet of a subsequent connection, even when 0-RTT packets are sent alongside.

**Comment by marten-seemann** [comment]
Sounds like a Chromium bug, right? I’m not sure how Chromium handles tokens, might be worth capturing a packet trace when it connects to google.com or YouTube.

**Comment by John-Athan** [comment]
I thought so too, but was not sure. After a bit of debugging, the issue is clear.

Chromium (or Quiche, more precisely) throws away tokens if they arrive before it gets a crypto frame containing a NewSessionTicket. It works as follows:
* Upon arrival of a NEW_TOKEN frame, the token [gets stored alongside its associated server ID](https://github.com/google/quiche/blob/39539964f9d5b173c01de08c0f13063f6b120a45/quiche/quic/core/crypto/quic_client_session_cache.cc#L119) (i.e. a combination of host and port) inside a cache that holds TLS sessions.
* When a new session ticket arrives, the session [gets added to the cache entry for the associated server](https://github.com/quic-go/quic-go/blob/4a046185b7d5275fd70504d2d630d10e731dbcc6/connection.go#L760)
* This new session does not specify the same QUIC transport parameters and is therefore assumed to be related to another, more recent session. The old cache entry (containing the token) [gets removed and a new entry without the token is inserted](https://github.com/google/quiche/blob/39539964f9d5b173c01de08c0f13063f6b120a45/quiche/quic/core/crypto/quic_client_session_cache.cc#L65).

I am not quite sure if this behavior is intentional or not. It seems weird though.

quic-go currently always sends the token first: https://github.com/quic-go/quic-go/blob/4a046185b7d5275fd70504d2d630d10e731dbcc6/connection.go#L760
If the NewSessionTicket is sent before the NEW_TOKEN frame, Quiche uses the token without issues.

AFAIK, a client should be able to use tokens independent of the TLS session ticket, therefore I will open an issue in the Quiche project.

**Comment by marten-seemann** [comment]
Interesting debugging! This does indeed sound like a Quiche issue. Can you post the link to the issue here?

**Comment by marten-seemann** [comment]
Thanks for opening the issue in Google Quiche! Is there anything left to do on the quic-go side, or should we close this issue?
