### ISSUE TITLE
http3: HEAD method should not have a body

### ISSUE THREAD

**Issue by sanyo0714** [quic-go/quic-go#4097]
![image](https://github.com/quic-go/quic-go/assets/14814461/932a17d1-ba39-403e-a2e7-1e029c9cae88)

fix like http lib @ go/src/net/http/server.go line 377
![image](https://github.com/quic-go/quic-go/assets/14814461/d68b8ddf-e1f5-44cd-844c-c6f84d66fd33)

**Comment by marten-seemann** [comment]
Want to submit a patch?

**Comment by Glonee** [comment]
I believe there are two ways to implement this.
1. Implement it within `responseWriter.Write` similar to the standard library. This would require us to introduce a new field in `responseWriter` to let `Write` know if the request method is `HEAD`.
2. Implement it in `Server.handleRequest`. In this approach, we would provide a wrapped `responseWriter` that discards all write operations to `ServeHTTP` when the request method is `HEAD`.

**Comment by marten-seemann** [comment]
Maybe I'm missing something, but why does the HTTP library need to do anything here at all? Isn't it a bug in the application if it answers a `HEAD` request with a body?

**Comment by Glonee** [comment]
https://cs.opensource.google/go/go/+/ebe91d11051ac5e9ecf1bdacc1bcdfbe7bcbafa7
Maybe this would help

**Comment by marten-seemann** [comment]
That's indeed a very helpful writeup. Thanks for finding it!

@Glonee Want to submit a fix? No particular preference on (1) or (2), both seem reasonable at first glance.
