### ISSUE TITLE
Incorrect ecnIPv4DataLen on FreeBSD

### ISSUE THREAD

**Issue by peterjeremy** [quic-go/quic-go#4106]
#4059 added ECN support for Darwin (MacOS), FreeBSD and Linux but incorrectly configured `ecnIPv4DataLen` on FreeBSD.  Whilst `4` is the correct length for use with setsockopt(2), when used as a `sendmsg` control message, the length should be `1`.  I can't find this documented anywhere but https://cgit.freebsd.org/src/tree/sys/netinet/udp_usrreq.c#n1144 shows that it checks for a length of 1.

A fix is [sys_conn_helper_freebsd.txt](https://github.com/quic-go/quic-go/files/12786989/sys_conn_helper_freebsd.txt)

**Comment by marten-seemann** [comment]
@peterjeremy Have you tried it out on a FreeBSD machine with your patch? Would you mind submitting a PR?
