### ISSUE TITLE
Is it possible to share packetConn between http3.Server and http3.RoundTripper

### ISSUE THREAD

**Issue by Dieken** [quic-go/quic-go#4113]
According to quic-go/http3 document:

https://pkg.go.dev/github.com/quic-go/quic-go/http3#RoundTripper
[func (s *Server) Serve(conn net.PacketConn) error](https://pkg.go.dev/github.com/quic-go/quic-go/http3#Server.Serve)

Seems I can create a `net.PacketConn` and share it with `http3.Server` and `http3.RoundTripper` by providing `RoundTripper.Dial`, is it possible and supported?

I need the server and client share same local port for UDP based firewall hole punching:

1. server A listens on `:1234` on machine A
2. server B listens on `:1234` on machine B
3. client A on machine A binds to `:1234` too and continuously queries "/ping" to server B
4. client B on machine B binds to `:1234` too and continuously queries "/ping" to server A
5. due to step 3 and step 4, the firewall allows UDP flow between "machineA:1234" and "machineB:1234", both client A and client B will succeed after some retries.

**Comment by marten-seemann** [comment]
It's possible, it's a bit subtle though. You need to first create a `quic.Transport`, then set up a `http3.Server` with a listener from that transport. You can then set the `Dial` function on the `http3.RoundTripper`. We might want to document this better somewhere.

**Comment by Dieken** [comment]
Thank you very much, I tried the flow it does work!

**Comment by marten-seemann** [comment]
Great! Thanks for reporting.

I’ll keep the issue open, so we can track adding some documentation.

**Comment by marten-seemann** [comment]
I'm writing up a comprehensive README for the http3 package, and this will be explained in one section. PR incoming.
