### ISSUE TITLE
Enabling Datagrams support causes unexpected behavior.

### ISSUE THREAD

**Issue by karthikgbbristol** [quic-go/quic-go#4137]
I have the following code to establish a QUIC Connection
```
func (t *Tunnel) establishQuicSession(address string, tlsConfig *tls.Config, quicConfig *quic.Config) error {
	var err error
	t.conn, err = quic.DialAddr(t.ctx, address, tlsConfig, quicConfig)
	if err != nil {
		return err
	}
	log.Println("Supports datagarms:", t.conn.ConnectionState().SupportsDatagrams)

	return nil
}
func buildQuicConfig() *quic.Config {
	return &quic.Config{
		MaxIdleTimeout:  MaxIdleTimeout * time.Minute,
		EnableDatagrams: true,
	}
}

```

After that, I call SendMessage on the connection to send a random byte array.
`err = t.conn.SendMessage(data) `

Then, I open a stream (this is the very first OpenStreamSync call) and write some data using stream.write

```
t.stream, err = t.conn.OpenStreamSync(t.ctx)
if err != nil {
println("Failed to open stream")
return err
}
packet, err := getHandshake()
if err != nil {
return err
}
_, err = t.stream.Write(packet)
```

I then read the response using

``` 
responseBuffer := make([]byte, 4096) // Adjust buffer size as needed.
readn, err := t.stream.Read(responseBuffer)
if err != nil {
return nil, err
}

receivedData := responseBuffer[:readn]
return decode(receivedData)
```

This works when EnableDatagrams is false.
When it's set to true, I get the following error from the server (I don't have control of it)
`stream 0 canceled by remote with error code 0`

I am a newbie to QUIC. Is what I am doing wrong? If so how can it work when `EnableDatagrams` is `false` There is a Python implementation using qh3 that does the same sequence, and it works. So it's unlikely an issue with the server. 
Any thought much appreciated

**Comment by marten-seemann** [comment]
Not sure how to make sense of this. What you could do is record a qlog and look at what’s going on on the wire.

**Comment by karthikgbbristol** [comment]
Ok I'll try but given my application needs to read datagrams at a high throughput, quic-go is probably not the most suitable? I'll try with another library.

**Comment by marten-seemann** [comment]
#3766 is the tracking issue for datagram performance. It’s true that currently datagram performance is not the best, but it shouldn’t be too hard to improve it quite significantly, once we start work on resolving that issue.

**Comment by marten-seemann** [comment]
Closing since there's nothing actionable to do here.

Improving datagram support is on the roadmap for the next release: https://github.com/quic-go/quic-go/milestone/24.
