### ISSUE TITLE
用quic做内网穿透然后实现WEB转发。当下载文件限速后，其他流数据会卡住阻塞

### ISSUE THREAD

**Issue by dotqi** [quic-go/quic-go#4140]
现在的想法是用quic做内网穿透然后实现WEB转发。浏览器访问服务器8080时转发终端80端口。
现发现一个问题，下载转发的1G大文件，如果下载工具限速100KB时，会造成其他人的访问全部卡住。如果不限制下载速度，其他访问不会卡住。
个人感觉就像是一个流被限速。别的流也发生停顿一样。
以下为代码部分

`package main

import (
	"context"
	"crypto/rand"
	"crypto/rsa"
	"crypto/tls"
	"crypto/x509"
	"encoding/pem"
	"io"
	"log"
	"math/big"
	"net"
	"time"
	"github.com/lucas-clemente/quic-go"
)

const addr = "127.0.0.1:4242"
var sconn quic.Connection
func main() {
	go QuicServer()
	go QuicClient()
	err := NetServer()
	log.Println("NetServer", err)
}

// 端口代理
func NetServer() error {
	listener, err := net.Listen("tcp", ":8080")
	if err != nil {
		return err
	}
	log.Println("lister :8080")
	for {
		conn, ex := listener.Accept()
		if ex != nil {
			log.Println(ex)
		}
		log.Println("new conn", conn)
		if stream, err := sconn.OpenStreamSync(context.Background()); err != nil {
			log.Println("open stream error ", err)
		} else {
			go StreamToConn(stream, conn)
			go ConnToStream(conn, stream)
		}
	}
}

// 流拷贝
func ConnToStream(conn net.Conn, stream quic.Stream) {
	log.Println("ConnToStream", stream.StreamID())
	defer conn.Close()
	defer stream.Close()
	n, ex := io.Copy(stream, conn)
	log.Println(n, ex)
}

// 流拷贝
func StreamToConn(stream quic.Stream, conn net.Conn) {
	log.Println("StreamToConn io copy", stream.StreamID())
	defer conn.Close()
	defer stream.Close()
	n, ex := io.Copy(conn, stream)
	log.Println(n, ex)
}

// Quic服务
func QuicServer() error {
	listener, err := quic.ListenAddr(addr, generateTLSConfig(), config())
	if err != nil {
		return err
	}
	for {
		conn, err := listener.Accept(context.Background())
		if err != nil {
			log.Println(err)
			panic(err)
		}
		sconn = conn
		log.Println("new quic conn", sconn)
	}
}

// Quic终端
func QuicClient() error {
	tlsConf := &tls.Config{
		InsecureSkipVerify: true,
		NextProtos:         []string{"quic-echo-example"},
	}
	conn, err := quic.DialAddr(addr, tlsConf, config())
	if err != nil {
		return err
	}
	for {
		stream, ex := conn.AcceptStream(context.Background())
		if err != nil {
			log.Println(ex)
			panic(ex)
		}
		log.Println("accept stream", stream.StreamID())
		if remote, err := net.Dial("tcp", "127.0.0.1:80"); err != nil {
			log.Println("open web error", err)
		} else {
			go StreamToConn(stream, remote)
			go ConnToStream(remote, stream)
		}
	}
}

func config() *quic.Config {
	return &quic.Config{
		MaxIdleTimeout:  time.Second * 30,
		KeepAlivePeriod: time.Second * 10,
	}
}

// Setup a bare-bones TLS config for the server
func generateTLSConfig() *tls.Config {
	key, err := rsa.GenerateKey(rand.Reader, 1024)
	if err != nil {
		panic(err)
	}
	template := x509.Certificate{SerialNumber: big.NewInt(1)}
	certDER, err := x509.CreateCertificate(rand.Reader, &template, &template, &key.PublicKey, key)
	if err != nil {
		panic(err)
	}
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(key)})
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certDER})
	tlsCert, err := tls.X509KeyPair(certPEM, keyPEM)
	if err != nil {
		panic(err)
	}
	return &tls.Config{
		Certificates: []tls.Certificate{tlsCert},
		NextProtos:   []string{"quic-echo-example"},
	}
}
`

**Comment by marten-seemann** [comment]
Sorry, I don’t speak Chinese.

**Comment by dotqi** [comment]
The current idea is to use Quic for intranet penetration and then achieve web forwarding. When the browser accesses the server 8080, it forwards the terminal 80 port.

We have discovered an issue where downloading and forwarding 1GB files can cause other people's access to be blocked if the download tool has a speed limit of 100KB. If the download speed is not limited, other access will not get stuck.

Personally, it feels like a stream is limited in speed. Other streams are also blocked.
