### ISSUE TITLE
How to achieve 0RTT

### ISSUE THREAD

**Issue by LLL2000L** [quic-go/quic-go#4149]
Hello, why can't I achieve 0RTT in Wireshark even though I set listener, err := tr.Listen(tlsConf, &quic.Config{Allow0RTT: true}) on the server side and conn, err := tr.DialEarly(context.Background(), server, tlsConfDial, nil) on the client side? Is there any specific reason or how should I set it up? I am using quic-go version v0.38.1. I'm looking forward to your answer. Thank you!

**Comment by marten-seemann** [comment]
You need to use `ListenEarly`, as described in the documentation.
