### ISSUE TITLE
Wireshark cannot capture 0RTT

### ISSUE THREAD

**Issue by LLL2000L** [quic-go/quic-go#4151]
Hello, why can't I capture 0-RTT in Wireshark even though I wrote the code like this? The code mainly includes a server and a client. The server listens for 0-RTT using listener, err := tr.ListenEarly(tlsConf, &quic.Config{Allow0RTT: true}), and the client dials using conn, err := tr.DialEarly(context.Background(), server, tlsConfDial, nil). Then, conn.CloseWithError(0x42, "error 0x42 occurred") is executed to close the client, and a subsequent connection is made to verify if 0-RTT is implemented. However, the result is that Wireshark does not capture 0-RTT, and the subsequent connection still goes through the initialization process. I am new to QUIC, so please let me know if there is anything wrong with my practice. I am looking forward to your response. Thank you.
The main code is as follows
**server：**
```
	tr := quic.Transport{
		Conn: udpConn,
	}
	listener, err := tr.ListenEarly(tlsConf, &quic.Config{Allow0RTT: true})
	if err != nil {
		fmt.Printf("failed: %s\n", err)
		return
	}
	for {
		conn, err := listener.Accept(context.Background())
		if err != nil {
			fmt.Printf("failed connect: %s\n", err)
			continue
		}
         }
```
**client：**
```
        tr := quic.Transport{
		Conn: udpConn,
	}
	conn, err := tr.DialEarly(context.Background(), server, tlsConfDial, nil)
	if err != nil {
		fmt.Printf("failed: %s\n", err)
		panic(err)
	}
	conn.CloseWithError(0x42, "error 0x42 occurred")
	rconn, err := tr.DialEarly(context.Background(), server, tlsConfDial, nil)
	rconn.CloseWithError(0x42, "error 0x42 occurred")
```

**Comment by marten-seemann** [comment]
0-RTT requires resuming a previous connection. Please familiarize yourself with the RFC before asking questions here.
