### ISSUE TITLE
quic bidistream benchmark shows  bidistream would reduce send and recv packet rate

### ISSUE THREAD

**Issue by someview** [quic-go/quic-go#4153]
I have tried test some basic performance of quic-go.[ benchmark code repo](https://github.com/someview/quic-benchmark)
client and server have 5000 quicConn, every conn has a bidistream. client and server try send echo message to each other. the result like this:
```
server recv quic conn: 5000 routines: 15004
时间: 2023-11-03 02:55:12.052984912 +0000 UTC m=+29.587906872 send: 10498914 recv: 1122116 rate: 581051
时间: 2023-11-03 02:55:31.98341189 +0000 UTC m=+49.518333843 send: 8492597 recv: 3900576 rate: 619658
时间: 2023-11-03 02:55:51.983165842 +0000 UTC m=+69.518087817 send: 1351984 recv: 2086911 rate: 171944
时间: 2023-11-03 02:56:11.983503104 +0000 UTC m=+89.518425077 send: 796151 recv: 1340636 rate: 106839
时间: 2023-11-03 02:56:31.983448972 +0000 UTC m=+109.518370954 send: 530037 recv: 869042 rate: 69953

``` 
why bidistream  becomes slow, is there some limit about bidistream or the same ip traffic.

**Comment by marten-seemann** [comment]
Streams don’t reduce their send rate, unless blocked by flow control. The connection might reduce the send rate due to congestion control.

I don’t know what you’re benchmarking here, but having thousands of connections between the same nodes doesn’t seem to be very useful. I’m happy to engage with actual issues, but “I created an unrealistic setup and things are slow maybe” is not one of them.

**Comment by someview** [comment]
> Streams don’t reduce their send rate, unless blocked by flow control. The connection might reduce the send rate due to congestion control.
> 
> I don’t know what you’re benchmarking here, but having thousands of connections between the same nodes doesn’t seem to be very useful. I’m happy to engage with actual issues, but “I created an unrealistic setup and things are slow maybe” is not one of them.

My Purpose was to test the ability of a  quic server to handle packets. Performance is expected to vary with the number of clients because three go routines are created for each quic long connection, and memory consumption is expected to vary, especially we use quicserver as long term connection. Is there some benchmark result or suggestion?

**Comment by someview** [comment]
> Streams don’t reduce their send rate, unless blocked by flow control. The connection might reduce the send rate due to congestion control.
> 
> I don’t know what you’re benchmarking here, but having thousands of connections between the same nodes doesn’t seem to be very useful. I’m happy to engage with actual issues, but “I created an unrealistic setup and things are slow maybe” is not one of them.

We need to ensure the impact of a large number of quic long connections on system performance。
