### ISSUE TITLE
INTERNAL_ERROR

### ISSUE THREAD

**Issue by heixiaoma** [quic-go/quic-go#4164]
I used quic-go on an arm64 phone without any issues in version 0.39, but after updating to v4.0, I encountered an INTERNAL_ERROR(local) error

**Comment by marten-seemann** [comment]
Any more details?

**Comment by heixiaoma** [comment]
> Any more details?

![image](https://github.com/quic-go/quic-go/assets/10923974/2f2cd8fc-70cd-4146-b96a-8584ba74639d)

**Comment by heixiaoma** [comment]
> Any more details?
![4091699606035_ pic](https://github.com/quic-go/quic-go/assets/10923974/bd58cd26-77b8-40af-bcac-a583f1047bdb)
![4101699606037_ pic](https://github.com/quic-go/quic-go/assets/10923974/30094d02-20c6-4f96-9e0b-02cf3ac86a0a)


![4081699606034_ pic](https://github.com/quic-go/quic-go/assets/10923974/feaf50d6-151a-40c0-82cb-08538448b4cb)

**Comment by heixiaoma** [comment]
I believe this is due to issues caused by the previous version iteration, as this error has also been observed on other Ubuntu systems. According to the version release notes, it was supposed to be fixed, but it seems to have introduced a new bug instead.

**Comment by heixiaoma** [comment]
> Any more details?

I believe this is due to issues caused by the previous version iteration, as this error has also been observed on other Ubuntu systems. According to the version release notes, it was supposed to be fixed, but it seems to have introduced a new bug instead.
