### ISSUE TITLE
Extremely slow transfer speeds on Android (1-2Kb/s)

### ISSUE THREAD

**Issue by digitalhurricane-io** [quic-go/quic-go#4169]
On some android devices, I'm seeing extremely low transfer speeds and packet loss. The issue occurs whether client and server are on the same LAN or the server is running in the cloud.

The client opens a connection with the server, then opens a stream, then starts sending bytes. The client frequently pauses it's sending. I've seen up to a 7 second pause.

The client is compiled for android using gomobile bind.

I am using the latest version of the library (v0.40.0) however the issue was also occurring on v0.38.1 but I just got around to making a minimal reproduction.

go version:
go1.21.1 linux/amd64

Here is the minimal repo:
https://github.com/digitalhurricane-io/slow-quic-speed-repro

Unfortunately, in order to actually reproduce the issue, you would need an affected Android device. I'm using a Redmi Note 8 Pro.

There are a lot of qlog files you can look at though in the qlog directory.

I'm happy to help debug this issue more. If you don't have time to look into this at the moment, if you could just point me in the right direction I would appreciate it.

**Comment by marten-seemann** [comment]
I looked at a few qlogs, and can't find anything suspicious except for quite a few duplicates. I tweaked the `dropped_packet` event to include the packet number in #4171, but I doubt that this will help us debug this any furhter.

As far as I can see, you're only recording qlogs on the server (that is the receiver here). Could you record a qlog on the sender side as well? One possible explanation for the behavior could be that the client is running into the congestion window for some reason, and fails to recover, but we'll need the client's qlogs to confirm this.

**Comment by digitalhurricane-io** [comment]
Thanks for taking a look.

I ran it again on the LAN. I updated the repo. This time there is only output from 1 run in the log directory.

I bumped the buffer size on the sender (android client) to 32,000 up from 1,000 and the issue is much more pronounced. The buffer on the receiver (server) remains the same at 32,000.

In the log directory there are qlogs, app logs, and cpu profiles for both client and server.

It took 247.5 seconds to transfer 3125 Kb

**Comment by marten-seemann** [comment]
I took a look at the qlogs in qvis. It seems like you're experiencing horrendous rates of packet loss. The packet loss is consistent between both endpoints (i.e. the packets that the client believes are lost were actually never received by the server).

Every packet loss collapses your congestion window further, which is why the transfer rate is so slow. The RTT is also all over the place, further messing with your congestion controller: 
<img width="1389" alt="image" src="https://github.com/quic-go/quic-go/assets/1478487/e8423b29-459b-4223-9a3e-445198481d27">

**Comment by digitalhurricane-io** [comment]
I created a minimal UDP client server and did see a lot of packet loss. Sometimes I'd receive 10,000/10,000 packets. Sometimes I would only receive 100/10,000 packets.

I kinda had the belief that UDP was a solved problem so I figured the issue must have been QUIC. Further research shows that there are quite a few posts online about certain Android devices suffering huge amounts of UDP packet loss.

This issue can be closed. Thanks again!

**Comment by marten-seemann** [comment]
> I kinda had the belief that UDP was a solved problem so I figured the issue must have been QUIC. Further research shows that there are quite a few posts online about certain Android devices suffering huge amounts of UDP packet loss.

Very interesting. You would think that this would be a solved problem, now that everyone is using QUIC. Thanks for researching!
