### ISSUE TITLE
0-RTT data

### ISSUE THREAD

**Issue by kvasilye** [quic-go/quic-go#4173]
Hello,

First, thank you for developing this library!

This is a question, not an issue - I am very interested in using 0-RTT data, but unable to make it work despite using the `Early` functions and setting `Allow0RTT: true` in `quic.Config` structs.

Server:

```go
func handleQuicConnection(conn quic.EarlyConnection) {
	for {
		stream, err := conn.AcceptStream(context.Background())
		if err != nil {
			if errors.Is(err, quic.ErrServerClosed) {
				break
			}
			log.Printf("Cannot accept QUIC stream: %s\n", err)
			break
		}
		if stream != nil {
			log.Printf("Accepted QUIC stream: %d\n", stream.StreamID())
			// Read and write from / to the stream
			handleQuicStream(stream)
		}
	}
}

// Somewhere in main
	quicConfig := quic.Config{
		Allow0RTT: true,
	}

	quicListen, err := quic.ListenAddrEarly(fmt.Sprintf(":%d", PORT_TLS),
		tlsConfigQuic, &quicConfig)
	go func() {
		for {
			conn, err := quicListen.Accept(context.Background())
			if err != nil {
				if errors.Is(err, quic.ErrServerClosed) {
					break
				}
				log.Printf("Cannot accept quic connection: %s\n", err)
			}
			if conn != nil {
				state := conn.ConnectionState()
				log.Printf("Accepted QUIC connection from %v, 0rtt = %v, proto = %s\n",
					conn.RemoteAddr(),
					state.Used0RTT,
					state.TLS.NegotiatedProtocol))
				go handleQuicConnection(conn)
			}
		}
	}()
```

Client code:

```go
	quicConfig := quic.Config{
		Allow0RTT: true,
	}

	conn, err := quic.DialAddrEarly(ctx1, ADDR, &tlsConfig, &quicConfig)
	if err != nil {
		log.Fatalf("Cannot connect: %s\n", err)
	}
	defer func() {
		_ = conn.CloseWithError(1, "graceful close")
	}()

	stream, err := conn.OpenStream()
	if err != nil {
		log.Fatalf("Cannot open new stream: %s\n", err)
	}
	defer func() {
		_ = stream.Close()
	}()

	// Write to stream
	stream.Write ....

	// Read the server's response
	stream.Read ...

```

The logging on the server side always prints something like

Accepted QUIC connection from 98.47.233.209:54564, **0rtt = false**

What am I missing?

I'm running library version v0.40.0 on Linux x64 (server) and MacOS M1 (client), Go version is 1.20.11

I also tried the MS QUIC library on the client (Android) and despite following MS's instructions for sending 0-RTT data, I'm also getting **0rtt = false** logging from my server.

Thank you in advance!

**Comment by marten-seemann** [comment]
0-RTT only works on resumed connections, not on the first connection you make.

**Comment by kvasilye** [comment]
Ah! Thanks, does it mean that - on the client - I need to save a ticket from a non 0-rtt connection, then disconnect, and reconnect using a resumption ticket? How long are tickets good for?

**Comment by marten-seemann** [comment]
Correct. No special API. Just use a `tls.ClientSessionCache` as you would when doing TLS session resumption. Tickets are valid for 7 days.
