### ISSUE TITLE
QUIC performance protocol support

### ISSUE THREAD

**Issue by bt90** [quic-go/quic-go#4176]
I stumbled upon this protocol, proposed by the MsQuic developers:

* SecNetPerf (MsQuic implementation): https://github.com/microsoft/msquic/tree/main/src/perf#secured-network-performance-testing
* IETF draft: https://datatracker.ietf.org/doc/html/draft-banks-quic-performance-00

The tailscale developers used it in their latest [blog post](https://tailscale.com/blog/quic-udp-throughput/) to benchmark QUIC throughput.

**Comment by marten-seemann** [comment]
Have you seen https://github.com/quic-go/perf?
