### ISSUE TITLE
How to catch a connection break ?

### ISSUE THREAD

**Issue by AoAnima** [quic-go/quic-go#4177]
why, when the connection is broken, for example, the server crashes, neither the stream nor the connection gives errors? 
How to catch a connection break ?
The error appears only after some time, packets continue to be sent to the stream

if you start the client and the server, and then close the server in an emergency, the client continues to send data
```

func clinet() {
	log.Println("clinet")
	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()


	config := &quic.Config{
		KeepAlivePeriod: 10 * time.Second,
	}
	tlsconfig, err := КлиентскийТлсКонфиг()
	if err != nil {
		log.Fatal(err)
	}

	session, err := quic.DialAddr(ctx, "localhost:4242", tlsconfig, config)
	if err != nil {
		log.Fatal(err)
	}


	stream, err := session.OpenStream()
	if nerr, ok := err.(net.Error); ok && nerr.Timeout() {
		log.Fatal(err)
	}
	ticker := time.NewTicker(10 * time.Second)
	for range ticker.C {
		_, err = stream.Write([]byte("Hello, World!"))
	
		if err != nil {
			log.Println("Error writing to stream:", err)
			return
		}
	}
}

func server() {
	log.Println("server")


	config, err := tlsConfig()
	if err != nil {
		log.Println(err)
	}

	listener, err := quic.ListenAddr("localhost:4242", config, nil)
	if err != nil {
		log.Fatal(err)
	}


	session, err := listener.Accept(context.Background())
	if err != nil {
		log.Fatal(err)
	}


	stream, err := session.AcceptStream(context.Background())
	if err != nil {
		log.Fatal(err)
	}

	// Читайте данные из потока в цикле
	buf := make([]byte, 1024)
	for {
		n, err := stream.Read(buf)
		if err != nil {

			log.Println("Stream closed by client")
			break

		}
		log.Printf("Received: %s", buf[:n])
	}
}

func tlsConfig () (*tls.Config, error) {
	caCert, err := os.ReadFile("cert/ca.crt")
	if err != nil {
		return nil, err
	}

	caCertPool := x509.NewCertPool()
	caCertPool.AppendCertsFromPEM(caCert)
	

	cert, err := tls.LoadX509KeyPair("cert/server.crt", "cert/server.key")
	if err != nil {
		log.Fatal(err)
	}

	return &tls.Config{
		// InsecureSkipVerify: true,
		RootCAs: caCertPool,
		Certificates: []tls.Certificate{cert},
		// NextProtos:   []string{"h3", "quic", "websocket"},
		NextProtos: []string{"h3", "quic", "websocket"},
	}, nil
}
```

**Comment by heixiaoma** [comment]
UDP - это неконнекторованный протокол, и после разрыва соединения можно проверять только через механизм контроля пульса, работает ли соединение, поэтому проверка подключения на EOF возможна только после того, как превышено время контроля пульса.

**Comment by heixiaoma** [comment]
UDP is an unconnected protocol, and after one party disconnects, only the heartbeat mechanism can be used to check whether the connection is smooth. Therefore, checking whether the connection is EOF can only be done after exceeding the heartbeat time.

**Comment by AoAnima** [comment]
> UDP - это неконнекторованный протокол, и после разрыва соединения можно проверять только через механизм контроля пульса, работает ли соединение, поэтому проверка подключения на EOF возможна только после того, как превышено время контроля пульса.

Что за механизм контроля пульса ?

**Comment by AoAnima** [comment]
> UDP is an unconnected protocol, and after one party disconnects, only the heartbeat mechanism can be used to check whether the connection is smooth. Therefore, checking whether the connection is EOF can only be done after exceeding the heartbeat time.

What does it mean? Write a simple example please what do you mean

**Comment by heixiaoma** [comment]
The code can be translated into English as follows:
`q := &quic.Config{
    // Maximum idle time before reconnecting
    MaxIdleTimeout:        time.Duration(20) * time.Second,
    MaxIncomingStreams:    1000000,
    MaxIncomingUniStreams: 1000000,
    // Send heartbeat packets when idle
    KeepAlivePeriod: time.Duration(5) * time.Second,
}

go func() {
    for {
        stream, err := conn.AcceptStream(context.Background())
        if err != nil {
            call(err.Error())
            handler.ChannelInactive(stream)
            return
        }
        go func() {
            reader := bufio.NewReader(stream)
            // Pitfall: Multiple packets issue, need to repeatedly read and unpack
            for {
                decode, e := Protol.Decode(reader)
                if e != nil {
                    handler.ChannelInactive(stream)
                    return
                }
                if decode != nil {
                    handler.ChannelRead(stream, decode)
                }
            }
        }()
    }
}()
`

For example, there is a heartbeat mechanism here that sends a heartbeat packet every 5 seconds. If the server shuts down, after 5 seconds, it will result in an EOF error in the QUIC stream, causing errors when reading data or accepting streams. It does not provide real-time detection of disconnections.

**Comment by marten-seemann** [comment]
@AoAnima Is right. How would you know if the remote node has suddenly died? The only thing you can do is keep resending packets (which quic-go does for you), and eventually give up when you don't hear back. That's called the idle timeout.
