### ISSUE TITLE
ecn bug

### ISSUE THREAD

**Issue by heixiaoma** [quic-go/quic-go#4178]
Currently, I am using the gomobile library to compile into an AAR package for use in Android. Specifically, version 0.39 works fine on my Android phone. However, when I upgraded to version 0.4, I encountered the "sendmsg: invalid argument" issue. Fortunately, I was able to resolve this problem by using the code os.Setenv("QUIC_GO_DISABLE_ECN", "true"). I suspect there might be compatibility issues with ECN in version 0.4, but I am unsure how to express it precisely.

**Comment by tobyxdd** [comment]
I can confirm this. My project has seen a lot of users getting "sendmsg: invalid argument" caused by ECN. I guess we should have ECN detection, something similar to `isGSOSupported`?

**Comment by heixiaoma** [comment]
![IMG_3031](https://github.com/quic-go/quic-go/assets/10923974/e474d9f8-c7bd-415c-9866-b1c6f143e273)
I set environment variables based on error messages, prioritizing ecn and then gso. If there is a failure, a reconnection will be attempted. This should be considered compatible for now.

**Comment by marten-seemann** [comment]
@heixiaoma You shouldn't need the QUIC_GO_DISABLE_GSO code path. quic-go does that automatically now. Also note that these environment variables shouldn't be set dynamically, as they won't apply to old connections.

> I can confirm this. My project has seen a lot of users getting "sendmsg: invalid argument" caused by ECN. I guess we should have ECN detection, something similar to isGSOSupported?

I'm not opposed to that. However, ideally I'd like this to be more specific than just matching an `invalid argument` error code. Going forward, we'll probably set more and not less cmsgs to enable various socket optimizations, so it would be really valuable if we could tell them apart. Any idea?

**Comment by heixiaoma** [comment]
> @heixiaoma You shouldn't need the QUIC_GO_DISABLE_GSO code path. quic-go does that automatically now. Also note that these environment variables shouldn't be set dynamically, as they won't apply to old connections.
> 
> > I can confirm this. My project has seen a lot of users getting "sendmsg: invalid argument" caused by ECN. I guess we should have ECN detection, something similar to isGSOSupported?
> 
> I'm not opposed to that. However, ideally I'd like this to be more specific than just matching an `invalid argument` error code. Going forward, we'll probably set more and not less cmsgs to enable various socket optimizations, so it would be really valuable if we could tell them apart. Any idea?

"You're right. Currently, it seems like this is the only solution. If there are specific error messages or ways to check if Ecn is supported in order to configure it, that would be even better."

**Comment by joliveirinha** [comment]
adding some extra data point to this.

I was able to reproduce this problem as well while running on a docker within a synology NAS.
Seems like the detection for ECN support is not working properly. 

Disabling it manually via the ENV variable fixed the problem.
