### ISSUE TITLE
Some packets cannot be decrypted

### ISSUE THREAD

**Issue by pullundertin** [quic-go/quic-go#4185]
when running example client and server provided in quic-go/example there are two issues:

1. some of the pakets cannot be decrypted (see pictures). Handshake and Traffic keys for both sides are beeing tracked on client-side

<img width="1382" alt="Screenshot 2023-11-28 at 21 59 12" src="https://github.com/quic-go/quic-go/assets/112107884/d836189e-00a8-48c5-b64f-8b2f21f4cdaf">
<img width="1117" alt="Screenshot 2023-11-28 at 21 59 37" src="https://github.com/quic-go/quic-go/assets/112107884/0d13dfbc-0a16-4c2f-89ab-4bcee1f06219">

2. when downloading files greater than 1MByte some delays in the range of several seconds occure. this phenomen especially happens when packets could not be decrypted as far as i observed. 

<img width="1409" alt="Screenshot 2023-11-28 at 22 09 52" src="https://github.com/quic-go/quic-go/assets/112107884/7a932532-02e2-4b6b-bb66-07b37434b623">

**Comment by marten-seemann** [comment]
What does the qlog show? Are packets getting dropped because they can't be decrypted? This could be a Wireshark issue as well, I heard they're struggling with GSO sometimes.

**Comment by marten-seemann** [comment]
I can't see any problem from the qlog:
<img width="1196" alt="image" src="https://github.com/quic-go/quic-go/assets/1478487/c5d6e65c-0f80-4dde-9de6-f64f792ec33e">

The vast majority of the ACKs received have only have a single range, meaning that there are no missing packets. If there really were undecryptable packets, those would be missing, and the ACK frame would have a lot more ranges.

I suspect that what you're seeing here is Wireshark not dealing with GSO correctly, see https://gitlab.com/wireshark/wireshark/-/issues/19109 for more details.
