### ISSUE TITLE
add a app level crypto flag option to quic config

### ISSUE THREAD

**Issue by someview** [quic-go/quic-go#4187]
now  tls is now built into the quic protocol, but quic is also multi-layered.
can quic-go offer a crypto flag for the quic protocol process to offer more  flexibile for application:
eg: app_level_crpto bool flag to set the 1RTT packet and 0 RTT packet.

**Comment by someview** [comment]
> now tls is now built into the quic protocol, but quic is also multi-layered. can quic-go offer a crypto flag for the quic protocol process to offer more flexibile for application: eg: app_level_crpto bool flag to set the 1RTT packet and 0 RTT packet.

Now we find some quic protocol implement offer the feature. eg xquic. Even this is not RFC standard, From the perspective of layered design，it is still appropriate.

**Comment by someview** [comment]
> I don’t understand your proposal. What are you trying to do?

We are looking for a way to use quic without tls, but this is not quic protocol standard.  However, quic protocol with tls built in can be seperated different part. In the process of implementing the quic protocol, each part is optional, which will give more flexibility.

I have investigated several implementations of the quic protocol and found that some implementations are implemented in a layered form that allows for more flexibility in the application.
eg:https://github.com/cloudflare/quiche.  async event mode, expose some event like stream reset,  Quic-based protocols can be developed, such as http3.
https://github.com/alibaba/xquic  make  app level encryption optional.

I propose that quic-go can provide more flexibility, even if these features are not required to be included in the quic protocol specification.

**Comment by marten-seemann** [comment]
This was discussed in https://github.com/quic-go/quic-go/issues/2868, among others.
