### ISSUE TITLE
Enable and set destination for qlog output via QLOGDIR environment variable

### ISSUE THREAD

**Issue by birneee** [quic-go/quic-go#4189]
I ask myself if quic-go itself should act automatically on the [QLOGDIR](https://www.ietf.org/archive/id/draft-ietf-quic-qlog-main-schema-07.html#name-set-file-output-destination.
) environment variable, and enable qlog output, or if this has to be manually enabled/implemented by the application, which is using `quic-go`.

I think this behavior should be similar to `QUIC_GO_LOG_LEVEL`, so it would unify debugging for all applications using quic-go.

If an application developer wants to disable it, an option `IgnoreQlogDir` could be added to `quic.Config`. 
Something similar could then also be added for `QUIC_GO_LOG_LEVEL`.

**Comment by marten-seemann** [comment]
Would that be in addition to the tracer configuration? I'm a bit hesitant to make this make this a default, but on the other hand, it's mentioned in the draft.

I don't think we need any `quic.Config` option though. If you don't want qlogs, don't set the env.

**Comment by birneee** [comment]
I think it is fine to have two ways to enable qlogs.
The QLOGDIR variable is for enabling the default behavior.
But if the application needs more control over the qlog, the tracer configuration should be the way to go.

**Comment by marten-seemann** [comment]
Writing up a little bit more clearly what we already discussed on https://github.com/quic-go/quic-go/pull/4201.

We could introduce a `qlog.DefaultTracer` (suggestions for a better name highly appreciated) that is a `func(context.Context, logging.Perspective, ConnectionID) *logging.ConnectionTracer` (i.e. the exact type needed for `quic.Config.Tracer`).

It would do exactly what you suggested: read the directory from the QLOGDIR env, and if set create the directory and dump qlogs into that directory. Enabling qlogs would then be super simple, just use:
```go
quic.Config{
    Tracer: qlog.DefaultTracer,
}
```

I believe this would cover a lot of simple use cases, while still keeping the flexibility to configure your own tracing callback if you need something more sophisticated.

@birneee What do you think? Want to raise a PR?
