### ISSUE TITLE
drop support for Go 1.20

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#4194]
We're planning to drop support for Go 1.20 as soon as the first Go 1.22 prerelease (beta? rc?) ships. This is a bit ahead of our usual [release policy](https://github.com/quic-go/quic-go#release-policy), but it will allow dropping the qtls dependency, and simplify the handshake package quite a bit.

v0.41.0 will be released before Go 1.20 is dropped.

Please speak up here if this change causes any trouble for your use case!

**Comment by marten-seemann** [comment]
https://cupogo.dev/episodes/go-1-22rc1-next-week-show-analytics-year-in-review-and-chat-with-jon-bodner-author-of-learning-go-2nd-ed claims that RC1 will ship on Dec 19th.

**Comment by Letgamer** [comment]
go1.22rc1 was released on 19th: https://groups.google.com/g/golang-announce/c/FIUY9kd7fc0
Can you roughly say how long it will take to release an updated version?

**Comment by marten-seemann** [comment]
@Letgamer Can you explain why you need a release? quic-go should be forwards-compatible with new Go versions.

**Comment by Letgamer** [comment]
I got a Dockerfile building a cloudflared container and I have to set golang:1.20-alpine and cannot use 1.21 or higher because then the build fails with the following in the logs:
`vendor/github.com/quic-go/quic-go/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration`

Dockerfile:
```
# Stage 1: Build container

# Use a specific Golang version and Alpine Linux as the base image
FROM --platform=linux/amd64 golang:alpine AS build

# Set the working directory for the build
WORKDIR /src

# Install necessary dependencies for building
RUN apk --no-cache add git build-base curl jq

# Fetch the latest release version using GitHub API
RUN VERSION=$(curl -s https://api.github.com/repos/cloudflare/cloudflared/releases/latest | jq -r .tag_name) \
    && git clone https://github.com/cloudflare/cloudflared --depth=1 --branch ${VERSION} .

# Build the cloudflared binary for Linux amd64
RUN GO111MODULE=on CGO_ENABLED=0 GOOS=linux GOARCH=amd64 make cloudflared

# Stage 3: Runtime container
FROM alpine

# Set the working directory in the new image
WORKDIR /

# Copy the built cloudflared binary and required files
COPY --from=build /src/cloudflared .
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/

# Copy curl binary from a docker image
COPY --from=ghcr.io/tarampampam/curl /bin/curl /bin/curl

# Set environment variable for the cloudflared origin certificate
ENV TUNNEL_ORIGIN_CERT=/etc/cloudflared/cert.pem

# Specify the entry point and default command for the container
ENTRYPOINT ["/cloudflared", "--no-autoupdate"]
CMD ["version"]
```

**Comment by marten-seemann** [comment]
Looks like it’s using a super outdated version of quic-go. We’ve had 1.21 support for ages now.

**Comment by Letgamer** [comment]
Thanks for the answer, this than needs to be fixed in Cloudflared👍

**Comment by marten-seemann** [comment]
Change of plans: it doesn't seem like we have enough new features for a v0.41 release at this point, only some minor bug fixes and a few small additions to the http3 package. We might delay v0.41 for a bit longer.
