### ISSUE TITLE
Use something like  `LocalAddr` to select outbound IP with multiple network interfaces

### ISSUE THREAD

**Issue by bmwaechter** [quic-go/quic-go#4197]
Hi and thanks for the awesome project!

I have an client that is using a `&http3.RoundTripper` that is working well, however we have recently hit a case where we have a system with multiple network interfaces and need to be able to specify which interface to use for your connection. 

in a stock roundTripper we might do something like 

```golang
transport := &http.Transport{
    IdleConnTimeout: 60 * time.Second,
    DialContext: (&net.Dialer{
        Timeout:   30 * time.Second,
        LocalAddr: localAddr,
    }).DialContext,
}
```

however i have not bee able to see a straight-forward way to string something like this together using a custom dial function, unless I am missing something. 

If not possible is this something that seems reasonable to add?  Any guidance would be appreciated here.

**Comment by marten-seemann** [comment]
Hi @bmwaechter! Thanks for the detailed description.

The `http3.RoundTripper` allows you to set your own `Dial` function. If you're able to construct a `quic.Transport` that only listens on one interface, you should be able to use the `DialEarly` function on that struct for that.

Does this work for you?

**Comment by bmwaechter** [comment]
Apologies and thanks for the response was caught up in jury duty the past couple days. digging in based on this guidance and will come back with what i find.

**Comment by bmwaechter** [comment]
@marten-seemann  just want to clarify 1 thing, you said:

> If you're able to construct a construct a `quic.Transport` that only **listens** on one interface

just to be clear , I am acting acting as a client using quic to communicate with a server, so want to make sure that the requests can be sent using a specific network interface on the machine, I think the word "listen" might be throwing me for a loop. Wanted to clarify.

**Comment by bmwaechter** [comment]
Thanks for the guidance @marten-seemann ! After experimenting I believe this can be accomplished, however i do have some concerns about the cleanup of resources/connections and dangling transports. Taking a minimal example like this: 

```golang
http3Transport := &http3.RoundTripper{
    TLSClientConfig: &tls.Config{},
    QuicConfig: &quic.Config{
    HandshakeIdleTimeout: 3 * time.Second,
    MaxIdleTimeout:       30 * time.Second,
    },
}

http3Transport.Dial = func(ctx context.Context, addr string, tlsCfg *tls.Config, cfg *quic.Config) (quic.EarlyConnection, error) {

    ip := net.ParseIP("127.0.0.1")
  
    udpConn, _ := net.ListenUDP("udp", &net.UDPAddr{IP: ip, Port: 0})
    
    updAddr, _ := net.ResolveUDPAddr("udp", addr)
    
    tr := &quic.Transport{
        Conn: udpConn,
        // createdConn -- cannot set
        // isSingleUse -- cannot set
    }
    
    conn, err := tr.DialEarly(ctx, updAddr, tlsCfg, cfg)
    
    if err != nil {
        tr.Close()
        return nil, err
    }
    
    return conn, err
}

httpClient := &http.Client{
    Transport: http3Transport,
}

httpClient.Get("https://quic.nginx.org/")
```

I noticed that both the `createdConn bool` and `isSingleUse bool` are not exported from the  `quic.Transport` struct. Searching the code it seems these are tied to internal logic for both [init](https://github.com/quic-go/quic-go/blob/master/transport.go#L186C2-L192C3) and [cleanup](https://github.com/quic-go/quic-go/blob/master/transport.go#L282C2-L286C3). And i want to be sure that we are not going to be leaking resources.

Any thoughts on how to handle these concerns?  Sorry for the long explanation, want to make sure there was enough detail!

**Comment by marten-seemann** [comment]
The `Transport` has a `Close` method, which you should call when you're done using the UDP socket. Does that answer your question?

**Comment by bmwaechter** [comment]
A bit ill play around, but i want to be able to have the transport's `onClose` tied to the connection/client's `onClose` ie. as soon as the request is read it is closed.  is there a way for me to do that? i seem to be missing the hooks to do so.

**Comment by marten-seemann** [comment]
The HTTP client keeps the connection alive on purpose - after all, you might be issuing further requests to the server. If you want to close the `http3.RoundTripper` you can do that, it has a `Close` method. That should also close the underlying transport.

Does that solve your problem?

**Comment by bmwaechter** [comment]
ok great as long as it closes the underlying transport! from tracing it wasn't clear that it did to me, I preformed a couple experiments just this morning and also see that it looks like indeed they are closing when they need to! thanks for the guidance, i am dealing with a very performance and resource sensitive scenario on networking edge devices and was being cautious, ill re-open or reach out if i notice any resource issues! 

thanks!

**Comment by marten-seemann** [comment]
Great! Please let me know if you find any problems, this shutdown logic is indeed a bit complex.
