### ISSUE TITLE
http3: likely incorrect usage of logger Debugf

### ISSUE THREAD

**Issue by nanokatze** [quic-go/quic-go#4209]
In https://github.com/quic-go/quic-go/blob/6ffb9054a25953cd2d7bcee8a0a1e62bd7cb4585/http3/server.go#L276 the error string is fed into the format string parameter of Debugf, which is clearly not what was intended

**Comment by marten-seemann** [comment]
This is fine: https://github.com/quic-go/quic-go/blob/6ffb9054a25953cd2d7bcee8a0a1e62bd7cb4585/internal/utils/log.go#L64

**Comment by nanokatze** [comment]
This usage could lead to unexpected results if the error string happened to contain format qualifiers, but sure, this isn't particularly important especially given that it's a debug level message, and likely no error produces a string with format qualifiers anyway

**Comment by marten-seemann** [comment]
Oh right, I hadn't thought about that. This error is at least partially controlled by the peer in some cases, so we should fix this. Want to send a PR?

**Comment by nanokatze** [comment]
Sure
