### ISSUE TITLE
http3: bad Errorf 

### ISSUE THREAD

**Issue by nanokatze** [quic-go/quic-go#4212]
https://github.com/quic-go/quic-go/blob/e0bf13be01aaa715329d32da90d526671b5245ce/http3/server.go#L424
will substitute `err` into the `%+v` instead of the `%s`, which is clearly not what was intended, but I'm not sure what the original intent was. Substituting `l` into `%+v`, which will print the address of that object, doesn't seem super helpful.

**Comment by marten-seemann** [comment]
Would you mind submitting another PR? 🙏
