### ISSUE TITLE
0-RTT Implementation

### ISSUE THREAD

**Issue by mollyy0514** [quic-go/quic-go#4224]
Hi, I am interested in implementing 0-rtt, but after referring to issue [#4173](https://github.com/quic-go/quic-go/issues/4173) & [#3187](https://github.com/quic-go/quic-go/issues/3187), I still have some trouble implementing 0-rtt.

My scenario is that the client will sent some messages to the server, and the client will close its connection to the server by `CloseWithError` after sending for 5 seconds. In the next iteration, resume the connection.

This is my client code segment:
``` go
func main() {
    tlsConfig := &tls.Config{
        InsecureSkipVerify: true,
        NextProtos:         []string{“h3"},
        ClientSessionCache: tls.NewLRUClientSessionCache(1),
    }

    quicConfig := quic.Config{
        Allow0RTT: true,
        TokenStore: quic.NewLRUTokenStore(100, 100),
    }


    for i := 0; i < 3; i++ {
        ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second) // 3s handshake timeout
        defer cancel()

        // connect to server IP.
        session, err := quic.DialAddrEarly(ctx, serverAddr, tlsConfig, &quicConfig)
        if err != nil {
            fmt.Println(err)
        }
        
        // create a stream
        stream, err := session.OpenStreamSync(context.Background())
        if err != nil {
            log.Fatal(err)
        }

        duration := 5 * time.Second
        start_time := time.Now()
        for time.Since(start_time) <= time.Duration(duration) {
            /* some stream.Write code */
            message := Create_packet_message()
            stream.Write(message)
            time.Sleep(500 * time.Millisecond)
            /* some stream.Write code */
        }
        print("times up \n")
        session.CloseWithError(0, "there is an error!")
        stream.Close()
    }
}
```
This is my server code segment:
``` go
func main() {
    listener, err := quic.ListenAddrEarly(fmt.Sprintf("%s:%d", host, quicPort), GenerateTLSConfig(), &quic.Config{
        KeepAlivePeriod: time.Minute * 5,
        EnableDatagrams: true,
        Allow0RTT: true,
    })
    if err != nil {
        return err
    }
    for {
        // create a session
        sess, err := listener.Accept(context.Background())
        if err != nil {
            return err
        }

        stream, err := sess.AcceptStream(context.Background())
        if err != nil {
            return
        }

        // print remote address & 0rtt
        state := sess.ConnectionState()
        log.Printf("Accepted QUIC connection from %v, 0rtt = %v, proto = %s\n",
            sess.RemoteAddr(),
            state.Used0RTT,
            state.TLS.NegotiatedProtocol)

        /* some stream.Read code */
        buf := make([]byte, packet_length)
        stream.Read(buf)
        /* some stream.Read code */

    }
}
```

In client side , I have set `tlsConfig.ClientSessionCache` and `quicConfig.TokenStore`, but in server side, I still got log like `2023/12/31 00:38:21 Accepted QUIC connection from 127.0.0.1:50222, 0rtt = false, proto = h3` in my console, which `0rtt = false` for all these 3 connections.

So I am wondering that is there anything I need to modify in my code to make `0rtt = true` except for the first connection, or is there any misunderstanding of resuming a connection? 

Thank you in advance!

**Comment by marten-seemann** [comment]
What happens if you call `ConnectionState` after completion of the handshake?

**Comment by mollyy0514** [comment]
But if I check whether the handshake is completed by `TLS.HandshakeComplete`, which makes partial of my server code become like this:
``` go
state := sess.ConnectionState()
log.Printf("Accepted QUIC connection from %v, 0rtt = %v, handshake = %v, proto = %s\n",
    sess.RemoteAddr(),
    state.Used0RTT,
    state.TLS.HandshakeComplete,
    state.TLS.NegotiatedProtocol)
```
It will print out `0rtt = false, handshake = true`, so maybe the location where I call `ConnectionState` is already after completion of the handshake?

**Comment by marten-seemann** [comment]
What does the qlog show?

**Comment by mollyy0514** [comment]
```
{"time":3.3165,
 "name":"transport:packet_sent",
 "data":{"header":{
        "packet_type":"1RTT",
        "packet_number":1,
        "key_phase_bit":"0"
        },
 "raw":{"length":307},
 "frames":[{"frame_type":"ack","ack_delay":0.21925,"acked_ranges":[[0,2]],"ect0":2,"ect1":0,"ce":0},
        {"frame_type":"new_token","token":{"data":"f1c044a5d86bd......0cd1ff35"}},
        {"frame_type":"handshake_done"},
        {"frame_type":"crypto","offset":0,"length":186}],
 "ecn":"ECT(0)"}
}
```
This is the log which contains "handshake_done" in my qlog file(server side) of the second connection, the packet type is "1RTT". And the packet type of logs for receiving packets from client are also "1RTT", which is like this:
```
{"time":4013.140958,
 "name":"transport:packet_received",
 "data":{"header":{"packet_type":"1RTT","packet_number":11,"key_phase_bit":"0"},
    "raw":{"length":277,"payload_length":274},
    "frames":[{"frame_type":"stream","stream_id":0,"offset":2000,"length":250}],
    "ecn":"ECT(0)"}
}
```
To my acknowledgment, the packet type shouldn't be "1RTT" if I implement early connection correctly, so I'm wondering did I miss anything while I'm implementing 0RTT? e.g. I need to get a token locally in the client session cache, etc.

**Comment by marten-seemann** [comment]
These snippets don't tell me anything.

You can also try turning on logging. There's plenty of log statements in the [crypto setup](https://github.com/quic-go/quic-go/blob/master/internal/handshake/crypto_setup.go), and you might add some more logging yourself to debug this. We have some quite extensive integration tests for 0-RTT, so I think this is unlikely to be a quic-go issue, so I won't do any debugging on this myself. Happy to help though if you find something.

**Comment by digitalhurricane-io** [comment]
@mollyy0514 Try adding your certificate to tls.Config.RootCAs rather than using "InsecureSkipVerify: true"

**Comment by mollyy0514** [comment]
@digitalhurricane-io Thanks for your idea! But does that mean I should use OpenSSL to generate a self-signed CA so that client can create a new pool by `x509.NewCertPool` and `AppendCertsFromPEM`?

**Comment by digitalhurricane-io** [comment]
The idea is not to use "InsecureSkipVerify: true". You can do anything that accomplishes that goal.

**Comment by marten-seemann** [comment]
Why does `InsecureSkipVerify` matter? Can you point me to the respective code?

**Comment by marten-seemann** [comment]
Closing this issue, since the situation seems to have been resolved. 

I'd like to stress that `InsecureSkipVerify` has nothing to do with this. It is possible to use 0-RTT even when not verifying the certificate. This is an easy way to test it:
```diff
diff --git a/integrationtests/self/zero_rtt_test.go b/integrationtests/self/zero_rtt_test.go
index 85ad015e2..6226e4231 100644
--- a/integrationtests/self/zero_rtt_test.go
+++ b/integrationtests/self/zero_rtt_test.go
@@ -11,6 +11,8 @@ import (
        "sync/atomic"
        "time"

+       "github.com/quic-go/quic-go/integrationtests/tools"
+
        "github.com/quic-go/quic-go"
        quicproxy "github.com/quic-go/quic-go/integrationtests/tools/proxy"
        "github.com/quic-go/quic-go/internal/protocol"
@@ -244,9 +246,14 @@ var _ = Describe("0-RTT", func() {
        for _, l := range []int{0, 15} {
                connIDLen := l

-               It(fmt.Sprintf("transfers 0-RTT data, with %d byte connection IDs", connIDLen), func() {
+               FIt(fmt.Sprintf("transfers 0-RTT data, with %d byte connection IDs", connIDLen), func() {
                        tlsConf := getTLSConfig()
-                       clientTLSConf := getTLSClientConfig()
+                       clientTLSConf := &tls.Config{
+                               InsecureSkipVerify: true,
+                               NextProtos:         []string{tools.ALPN},
+                               ClientSessionCache: tls.NewLRUClientSessionCache(5),
+                               ServerName:         "localhost",
+                       }
                        dialAndReceiveSessionTicket(tlsConf, nil, clientTLSConf)

                        counter, tracer := newPacketTracer()
```
