### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by thuc98** [quic-go/quic-go#4240]
I have noticed a memory leak in my server application. The memory consumption keeps increasing and is not released unless I restart the service.

Environment:
``` 
QUIC-GO Version: v0.40.1
Operating System: Linux centos 8, arch amd64
go: 1.21.2
```

pprof
```

Showing nodes accounting for 4904.20MB, 67.42% of 7273.69MB total
Dropped 352 nodes (cum <= 36.37MB)
Showing top 10 nodes out of 159
      flat  flat%   sum%        cum   cum%
 3512.39MB 48.29% 48.29%  3960.92MB 54.46%  github.com/quic-go/quic-go.(*connection).preSetup
  246.08MB  3.38% 51.67%   246.08MB  3.38%  crypto/aes.(*aesCipherGCM).NewGCM
  234.54MB  3.22% 54.90%   234.54MB  3.22%  crypto/aes.newCipher
  160.12MB  2.20% 57.10%  4539.29MB 62.41%  github.com/quic-go/quic-go.glob..func1
  148.15MB  2.04% 59.13%   148.15MB  2.04%  crypto/tls.(*Conn).quicWriteCryptoData
  138.59MB  1.91% 61.04%   138.59MB  1.91%  github.com/quic-go/quic-go.(*cryptoStreamImpl).Write
  128.69MB  1.77% 62.81%   128.69MB  1.77%  github.com/quic-go/quic-go.init.0.func1
  118.56MB  1.63% 64.44%   119.06MB  1.64%  github.com/quic-go/quic-go.(*frameSorter).push
  115.06MB  1.58% 66.02%   160.57MB  2.21%  github.com/quic-go/quic-go/internal/handshake.newCryptoSetup
  102.04MB  1.40% 67.42%   102.04MB  1.40%  crypto/tls.newQUICConn (inline)

```
![profile005](https://github.com/quic-go/quic-go/assets/95730450/6723875a-8940-427f-a41a-b6dd11737373)

this is how i used quic:
```
	udpConn, _ := net.ListenUDP("udp", &net.UDPAddr{Port: s.opts.Port})
	quicTLSCfg := tlsConfig.Clone()
	quicTLSCfg.NextProtos = []string{"quicgo"}

	s.quicListener, err = quic.Listen(udpConn, quicTLSCfg, &quic.Config{
		MaxIdleTimeout:         s.opts.MaxIdleTimeout,
		MaxIncomingStreams:     s.opts.MaxIncomingStreams,
		KeepAlivePeriod:        s.opts.KeepAlivePeriod,
		EnableDatagrams:        true,
		MaxStreamReceiveWindow: uint64(STREAM_RWND),
	})

```

**Comment by marten-seemann** [comment]
How do you know it's a memory leak? If you have a lot of active connections, it's expected that they consume some memory.

It's only a leak if the memory persists beyond the lifetime of the connection.

**Comment by thuc98** [comment]
I tried closing all connections to the server but the memory hasn't decreased in the past two days

**Comment by thuc98** [comment]
> How do you know it's a memory leak? If you have a lot of active connections, it's expected that they consume some memory.
> 
> It's only a leak if the memory persists beyond the lifetime of the connection.

I tried closing all connections to the server but the memory hasn't decreased in the past two days

**Comment by marten-seemann** [comment]
Can you build a minimal reproducer? There's no way to debug this based on your report.

**Comment by thuc98** [comment]
> Can you build a minimal reproducer? There's no way to debug this based on your report.

I still haven't been able to recreate it.
But why does receivedPackets use so much memory?
`
         .    29.50MB    479:   s.framer = newFramer(s.streamsMap)
    5.57GB     5.57GB    480:   s.receivedPackets = make(chan receivedPacket, protocol.MaxConnUnprocessedPackets)
   24.50MB    24.50MB    481:   s.closeChan = make(chan closeError, 1)
   25.50MB    25.50MB    482:   s.sendingScheduled = make(chan struct{}, 1)
         .       19MB    483:   s.handshakeCtx, s.handshakeCtxCancel = context.WithCancel(context.Background())
`

**Comment by marten-seemann** [comment]
It's a channel with 256 entries, and `receivedPacket` is a struct that takes 112 bytes. So for every connection, that's around 28 kB.

**Comment by thuc98** [comment]
Thank you. my fault, my connection map not remove closed connection
