### ISSUE TITLE
Update wiki - add sysctl instructions to persist UDP buffer size change across reboots

### ISSUE THREAD

**Issue by DeflateAwning** [quic-go/quic-go#4331]
On this page: https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes

### The instructions currently say:
From the non-BSD section:

> It is recommended to increase the maximum buffer size by running:

```bash
sysctl -w net.core.rmem_max=2500000
sysctl -w net.core.wmem_max=2500000
```

### The Issue
These instructions do not indicate whether or not the instructions are persisted across reboots. As they are written currently, these settings aren't persisted across reboots. 

### Requested Change
1. Indicate that the instructions, as they are written, do not persist across reboots.
2. Add instructions on how to make those settings changes persist across reboots.

### How I think that section should read now

It is recommended to increase the maximum buffer size by running:

```bash
sysctl -w net.core.rmem_max=2500000
sysctl -w net.core.wmem_max=2500000
```

This command would increase the maximum send and the receive buffer size to roughly 2.5 MB, but will not persist across reboots.

To make this settings change persist across reboots, add lines to `/etc/sysctl.d/99-udp-buffer-size.conf` by running:

```bash
echo "net.core.rmem_max = 2500000" | sudo tee /etc/sysctl.d/99-udp-buffer-size.conf
echo "net.core.wmem_max = 2500000" | sudo tee -a /etc/sysctl.d/99-udp-buffer-size.conf
```

**Comment by marten-seemann** [comment]
Thanks for the issue. I'm not sure we should add this to the wiki though. In many deployment scenarios, you don't persist these settings across reboots, but apply this just before starting the binary. I also don't want to make this any more platform-dependent as it needs to be.

**Comment by DeflateAwning** [comment]
You need to add a note that explains that it's not persisted then. I think it's entirely reasonable to assume the instructions you'd give _do_ persist.

**Comment by marten-seemann** [comment]
Fair enough, I added a sentence.

**Comment by DeflateAwning** [comment]
Thank you!
