### ISSUE TITLE
DontCloseRequestStream set true fail

### ISSUE THREAD

**Issue by 380wmda999** [quic-go/quic-go#4350]
example/client/main.go

`ropt := http3.RoundTripOpt{DontCloseRequestStream: true}
rsp, err := roundTripper.RoundTripOpt(req, ropt)`

when DontCloseRequestStream is set to true it always return error
but when DontCloseRequestStream is false it always ok?
why?
DontCloseRequestStream  only can set false??

**Comment by 380wmda999** [comment]
I looked your code, seems when DontCloseRequestStream set true the func parseNextFrame return H3_NO_ERROR  so it fail

**Comment by marten-seemann** [comment]
This option is only intended for WebTransport, and it works there. It is invalid to use for regular requests.

**Comment by 380wmda999** [comment]
for regular requests , is there any way not close RequestStream?

**Comment by marten-seemann** [comment]
There's no reason to do so, and it violates RFC 9114, so no, there isn't, and there won't be.
