### ISSUE TITLE
Changing net.Conn for a Connection

### ISSUE THREAD

**Issue by RithvikChuppala** [quic-go/quic-go#4354]
One of QUIC's main advantages is the use of ConnectionID's to identify point-to-point connections instead of the protocol/host/port 5 tuple. As such, it should be possible to use a different host/port as one of the endpoints while reusing the same connection ie the same Connection object (keeping all state the same between the handoff). This is proposed to elide NAT rebindings, ensure connection continuity during switch-offs between WiFi to cellular, etc. 

In QUIC-go, I presume that this is modeled by using a different net.Conn for a particular Connection or Transport object. Is there a way using the current API to re-use a Connection object but change the net.Conn transport that is used in the connection. Re-dialing the server with the new net.Conn won't work since that opens up a new connection instead of reusing the connection with its prior saved state (from what I understand). Thanks in advance!

**Comment by marten-seemann** [comment]
If I understand correctly, what you're referring to is QUIC Connection Migration. Unfortunately, it's a little bit more complicated than switching out the underlying `net.PacketConn`, as you 1. need to validate that the new path actually works and 2. need to deal with a path that might have vastly different parameters in terms of RTT and bandwidth.

See #234 and #3990 for more details.

**Comment by marten-seemann** [comment]
`net.PacketConn` is an interface, so you can write your own implementation that switches from one connection to the other, without any API changes in quic-go. Unfortunately, this will disable a number of optimizations that only work on actual UDP connections though (ECN and GSO, for example), which are pretty crucial if you're aiming for high throughput.
