### ISSUE TITLE
http3 server silently panics

### ISSUE THREAD

**Issue by anderspitman** [quic-go/quic-go#4366]
With a std HTTP server I would expect the following code to print some indication that the goroutine handling the request panicked:

```go
package main

import (
        "flag"
        "net/http"
        "log"

	"github.com/quic-go/quic-go/http3"
)

func main() {
        cert := flag.String("crt", "", "Cert")
        key := flag.String("key", "", "Key")
        flag.Parse()

        http.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
                panic("Hi there")
        })

        log.Fatal(http3.ListenAndServeQUIC(":443", *cert, *key, nil))
}
```

But http3 appears to just silently eat the panic. If this behavior is intentional, is there a way to surface panics so I am aware they're happening?

**Comment by marten-seemann** [comment]
That’s definitely not the intention. It turns out that we’re writing message to the custom logger: https://github.com/quic-go/quic-go/blob/497d3f58a556ea2aea596609e464e4f0b45b8031/http3/server.go#L658

We should probably use the same logger that net/http uses. Want to send us a PR?

**Comment by anderspitman** [comment]
I can take a look at least. Looks like net/http lets you specify your own logger, and defaults to the log package's default logger:

https://github.com/golang/go/blob/6e5398bad16aba15db365b72cb70d1177330b603/src/net/http/server.go#L2910

quic-go is currently using a custom Logger interface. Would you want to stop using that and do exactly what std does (ie only allow log.Logger), or should we try and make a wrapper for log.Logger that conforms to quic.Logger, or something else?

**Comment by anderspitman** [comment]
Link to quic.Logger for reference: https://github.com/quic-go/quic-go/blob/497d3f58a556ea2aea596609e464e4f0b45b8031/internal/utils/log.go#L28

**Comment by marten-seemann** [comment]
We should move away from the custom logger. It was not the best design decision in the first place, we really shouldn’t be in the business to define logger interfaces.

This change is harder for the quic package itself, but should be easier for the http3 package.

**Comment by rfwatson** [comment]
It makes sense to not redefine a new logging interface but `*log.Logger` has no levels and is generally inflexible. 

Any thoughts about accepting a [`*slog.Logger`](https://pkg.go.dev/log/slog@go1.22.2#Logger) instead? It comes with levels out of the box, can work with any logging backend, and its performance should be useful in this package.

**Comment by marten-seemann** [comment]
The most important question is: what should the HTTP/3 package log at all? Any input on what (if anything!) would be useful?

**Comment by rfwatson** [comment]
I suppose similar to Go's net/http [package](https://github.com/golang/go/blob/6e5398bad16aba15db365b72cb70d1177330b603/src/net/http/server.go#L2906-L2908):

> errors accepting connections, unexpected behavior from handlers, and underlying FileSystem errors.

(In this case I found this issue after debugging what turned out to be a silent panic in a handler).

**Comment by marten-seemann** [comment]
I took a stab at this in #4449. @anderspitman @rfwatson Does this PR work for you as you'd expect?

**Comment by anderspitman** [comment]
@marten-seemann sorry for the late response. I ran into some issues with WebTransport (may be a browser or even protocol issue), so I switched to WebSockets in my project for now, but I'm hoping to resume WT testing before too long. Thanks for fixing this!
