### ISSUE TITLE
any possibilities to use the latest golang 1.22 with quic-go compiler?

### ISSUE THREAD

**Issue by ouvaa** [quic-go/quic-go#4367]
there are significant speed improvements to using golang 1.22.

any possibilities to upgrade this or use ktls or something? i'm not sure about this part just hope i can compile it with the latest golang
https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions

just curious, what's the latest feedback on this issue? when will we not be needing to use 1.18 compiler?

**Comment by marten-seemann** [comment]
You can build with Go 1.22. Actually, Go 1.18 won’t work anymore. I’ll update / delete the wiki page, it’s totally outdated.

**Comment by ouvaa** [comment]
@marten-seemann thx for the prompt reply.

can you also please update this as well as it is quite old and doesnt give a lot of assurance to users using quic-go:
https://github.com/quic-go/quic-go/wiki/DoS-mitigations
