### ISSUE TITLE
Question about Making Stream Frames Manually

### ISSUE THREAD

**Issue by nxenon** [quic-go/quic-go#4390]
Hi, I am currently working on a research on the HTTP/3 protocol and I need to open a Quic connection and then open STREAM Frame `manually` (with intended flags that I want) and put HTTP/3 frames into it and send it into Quic connection.
As my first step:
1. Can someone help me with creating STREAM Frames with intended flags and data and send it into server (in Quic conn) ? (I do not want to deal with quic protocol itself like headers &..., just STREAM frames)

**Comment by marten-seemann** [comment]
quic-go doesn't provide an API for that, but you should find all the serialization methods you need somewhere in the wire package.

**Comment by nxenon** [comment]
> quic-go doesn't provide an API for that, but you should find all the serialization methods you need somewhere in the wire package.

Yeah now I am seeing it. But there is still a question, we suppose that I make the STREAM Frame bytes and it is ready to send. Is there any API or function that I can send STREAM frame bytes with it ? I mean add bytes to the end of the UDP packet after Quic Short Header ?

**Comment by nxenon** [comment]
I mean add this part to the end of the packet. I do not want to deal with parts before:
![image](https://github.com/quic-go/quic-go/assets/61124903/bd469511-dc0c-48ba-8ca8-4e088d091463)

**Comment by marten-seemann** [comment]
No there's no API. There's no reason a user of this library would ever want to do something like that. I can see how it can be useful to do security research, but this is a production-ready QUIC stack, not a research tool.

It should be fairly easy to add, but you'll have to do a little bit of work.
