### ISSUE TITLE
About two-way dialing (Questions)

### ISSUE THREAD

**Issue by peakedshout** [quic-go/quic-go#4402]
I really like Quic, it's the most comfortable one to use in the current UDP reliable stream (I've also tried the Go implementation of KCP, but it doesn't work very well).
As I use Quic-Go, I have a question, can Quic do two-way dialing? In TCP design, it is able to do two-way dialing and successfully establish a connection, which is very interesting, TCP sockets will change their dialing status after receiving the request, and finally it will not affect the handshake proces.
This approach does have a certain need, e.g. both parties only need a certain connection, because both parties are supplicants, which does not create a situation where the listener needs to additionally filter the connection (because it needs to be dialed at the same time, which is filtered to a certain extent), such as P2P.
It's just some questions and curiosity on my part, my project needs to make some one-time connections repeatedly, and it works well on TCP, but in Quic-Go, I don't know what's going on, I don't see much documentation, and it doesn't seem to be related to it. Hopefully someone with good man can answer my curiosity, and if there is a solution, it would be great.

**Comment by marten-seemann** [comment]
I assume you're referring to TCP simultaneous open? That won't work on QUIC, because QUIC connections use connection IDs. If you're interested in QUIC hole punching, have a look at the libp2p code, it achieves that by sending UDP packets with random payloads from one side.

**Comment by peakedshout** [comment]
> I assume you're referring to TCP simultaneous open? That won't work on QUIC, because QUIC connections use connection IDs. If you're interested in QUIC hole punching, have a look at the libp2p code, it achieves that by sending UDP packets with random payloads from one side.

No, I'm not talking about UDP punching issues. I'm wondering if there is a way to open in both directions, so that I don't need to create an additional one-time listening object, and it would be more convenient to use a dialer to dial. Thank you for answering my questions.
