### ISSUE TITLE
Increase buffer sizes

### ISSUE THREAD

**Issue by bt90** [quic-go/quic-go#4426]
This topic came up in the Syncthing forum: https://forum.syncthing.net/t/system-is-slow-on-windows-look-here/21925

I'm unsure if users really need to modify the registry or if the socket options are enough to tune the buffer sizes. After briefly skimming the code, I couldn't spot where we do this for Windows?

**Comment by marten-seemann** [comment]
It's done here: https://github.com/quic-go/quic-go/blob/master/sys_conn_buffers.go

Not sure how / if it works on Windows. Would be great if you could try it out.

**Comment by bt90** [comment]
wireguard-go seems to directly set the socket options:

https://github.com/WireGuard/wireguard-go/blob/master/conn/controlfns_windows.go

No idea if that's necessary, though.

> Would be great if you could try it out.

Can I evaluate this using Syncthing?

**Comment by marten-seemann** [comment]
This function is used to check the size of the buffer: https://github.com/quic-go/quic-go/blob/da410a7b5935e1399d66434ac5fbc472ea3993f1/sys_conn_windows.go#L16-L25

You could add some logging before and after we increase the buffer, and see if the value changes.

**Comment by bt90** [comment]
Judging from the debug logging, things are working as expected:

```
2024/04/12 17:06:34 Increased receive buffer size to 2048 kiB
2024/04/12 17:06:34 Increased send buffer size to 2048 kiB
2024/04/12 17:06:34 Setting DF for IPv4 and IPv6.
2024/04/12 17:06:34 server Listening for udp connections on [::]:22000
```

Simply tested via

```bat
set QUIC_GO_LOG_LEVEL=debug
.\syncthing.exe
```

I suspect that the speedup observed by our forum user was due to the obscenely high default buffer size of 25MB. While this is obviously too much, should we follow wireguard-go and increase our buffer to 7MB? See this commit message for more details: https://github.com/WireGuard/wireguard-go/commit/f26efb65f23acbd88785d1ae793fa3264c999673

**Comment by marten-seemann** [comment]
> I suspect that the speedup observed by our forum user was due to the obscenely high default buffer size of 25MB. While this is obviously too much, should we follow wireguard-go and increase our buffer to 7MB? See this commit message for more details: [WireGuard/wireguard-go@f26efb6](https://github.com/WireGuard/wireguard-go/commit/f26efb65f23acbd88785d1ae793fa3264c999673)

Sounds reasonable. Want to create a PR?
