### ISSUE TITLE
Is there a way for clients to proactively modify their ports and perform connection migration? Due to the limited speed of UDP connections in many regions, it can only be resolved by regularly changing the client port!

### ISSUE THREAD

**Issue by masx200** [quic-go/quic-go#4443]
Is there a way for clients to proactively modify their ports and perform connection migration? Due to the limited speed of UDP connections in many regions, it can only be resolved by regularly changing the client port!

**Comment by marten-seemann** [comment]
Why would changing the UDP port increase the transmission speed?

**Comment by masx200** [comment]
https://cloud.tencent.com/developer/article/2153908

https://blog.csdn.net/dog250/article/details/113706995

**Comment by marten-seemann** [comment]
Sorry, I don't speak Chinese. I haven't heard of this problem ever before, maybe it's related to some kind of GFW censorship?

Support for connection migration is tracked in #234.
