### ISSUE TITLE
How can I use the same port for accepting connections/streams and handling REST-style http requests?

### ISSUE THREAD

**Issue by yaziciahmet** [quic-go/quic-go#4454]
I want to be able to use the same port for accepting connections/streams, and also handling REST-like (request-response) http requests. Is this possible?

I have an endpoint which I need the client-side to stream data to my server, and I also need other regular REST endpoints next to it, served from the same server and same port. So if client dials `https://example.com/stream`, I want to open a unidirectional stream from client to server. But if client sends a GET request to `https://example.com/user`, I want to return the user details from my http handler.

I actually managed to do this with the WebTransport server. `/stream` request connections are upgraded and a stream is opened. `/user` requests are returned a response right away with the user details. But I am afraid WebTransport has very little to no support from reverse proxies and load balancers currently, which I definitely need. That is why I am looking for a solution with quic and http3.

**Comment by marten-seemann** [comment]
Headers are parsed into an `http.Request`. If you want to use a non-HTTP protocol, you can use ALPN.

**Comment by yaziciahmet** [comment]
But I don't have access to the underlying QUIC connection in my `http.Handler` to open a stream do I?

**Comment by yaziciahmet** [comment]
Here is what I tried to do:

```go
	listener, err := quic.ListenAddrEarly(":8080", tlsConfig, &quic.Config{
		EnableDatagrams: true,
		Allow0RTT:       true,
	})
	if err != nil {
		return err
	}

	go func() {
		for {
			conn, err := listener.Accept(context.Background())
			if err != nil {
				slog.Error("Failed to accept connection", "err", err)
				continue
			}

			slog.Info("Accepted connection", "remoteAddr", conn.RemoteAddr())
		}
	}()

	return s.h3.ServeListener(listener)
```
where `s.h3` is a `*http3.Server` instance.

When I send http3 requests, sometimes `http3.Server` captures the request and serves it successfully, but sometimes the `quic.EarlyListener` captures the request in the goroutine and nothing happens and client is stuck. How can I make sure that http3 requests are only handled by `http3.Server`, and other quic connection requests are captured by the listener? Keep in mind that I want both `http3.Server` and the quic listener process to share the same Listener instance so that they can be served on the same port.

**Comment by marten-seemann** [comment]
There seems to be some confusion about what constitutes a request. HTTP requests are sent on streams, so accepting the connection won’t have any influence on that.
