### ISSUE TITLE
Panic in http3.RoundTripper.Close

### ISSUE THREAD

**Issue by ainar-g** [quic-go/quic-go#4457]
Discovered while testing #4456.

Panic occurs in `RoundTripper.Close` here:

```go
if err := client.conn.CloseWithError(0, ""); err != nil 
```

My main hypothesis is that this occurs when there is a dialing error.  See `RoundTripper.getClient`:

```go
cl, ok := r.clients[hostname]
if !ok {
	if onlyCached {
		return nil, false, ErrNoCachedConn
	}
	cl = &roundTripperWithCount{
		dialing: make(chan struct{}),
	}
	go func() {
		defer close(cl.dialing)
		conn, rt, err := r.dial(ctx, hostname)
		if err != nil {
			cl.dialErr = err
			return
		}
		cl.conn = conn
		cl.rt = rt
	}()
	r.clients[hostname] = cl
}
```

Note how `cl.conn` is only set in the anonymous goroutine if `r.dial` is successful.

Which means that `r.clients` can contain clients with `conn == nil`, but methods `Close`, `CloseIdleConnections`, and `getClient` all lack nil checks and assume that a non-nil `*roundTripperWithCount` always has a non-nil `conn`.

**Comment by marten-seemann** [comment]
Thanks for reporting. Very valuable to get this resolved before shipping v0.43 :)
