### ISSUE TITLE
version issue:quic.DialContext does not exist in lastest version,we can't pass localAddress 

### ISSUE THREAD

**Issue by introspection3** [quic-go/quic-go#4487]
DialContext can pass a localAddress 
but,lastest version can't .
![image](https://github.com/quic-go/quic-go/assets/12368358/85ca5a77-3147-41ec-b3ee-49b1cdb0ea2d)

**Comment by marten-seemann** [comment]
Please refer to the documentation: https://quic-go.net/docs/quic/client/.
