### ISSUE TITLE
The method `ListenAndServe` in package `http3` is not compatible with `http`

### ISSUE THREAD

**Issue by ETZhangSX** [quic-go/quic-go#4521]
The method `ListenAndServe` in package `http3` is not compatible with the method in built-in package `http`
https://github.com/quic-go/quic-go/blob/2557fb98b2423ab1f0ae525509c68b51510422e0/http3/server.go#L673

The definitions in `http` are
```go
func ListenAndServe(addr string, handler Handler) error
func ListenAndServeTLS(addr, certFile, keyFile string, handler Handler) error
```

Maybe we should rename it to `ListenAndServeTLS` ?

**Comment by marten-seemann** [comment]
We could, but what's the advantage of that?

**Comment by ETZhangSX** [comment]
Maybe for compatibility upgrade from http1/2 to http3, which can just change the package name.

**Comment by marten-seemann** [comment]
I doubt this would be the only change needed. For anything but the simplest use case, you'd set up a `http.Server` anyway. But I'm ok to change this, as long you don't remove, but only deprecate the old function. Want to send a PR?

**Comment by ETZhangSX** [comment]
OK, I will send a PR.
