### ISSUE TITLE
quic-go.newStream high memory usage

### ISSUE THREAD

**Issue by nguyenduongnhj** [quic-go/quic-go#4525]
I use quic-go to create a reverse proxy. Although I don't use it much, the application takes up a lot of memory.
![Screenshot 2024-05-19 at 13 28 47](https://github.com/quic-go/quic-go/assets/44090434/10ee9476-c3da-40a3-8586-bf8296bfc651)

![profile001](https://github.com/quic-go/quic-go/assets/44090434/a0055659-bfe1-4ad4-881b-77ff9b06b2de)
Here is screenshot of a heap profile where we can see it accumulating in the map.

Is this normal?

**Comment by marten-seemann** [comment]
Probably fixed by https://github.com/quic-go/quic-go/pull/4523. Can you try out the brand new v0.44 release?

**Comment by nguyenduongnhj** [comment]
may

> Probably fixed by #4523. Can you try out the brand new v0.44 release?

seems unrelated, I don't use http3,

**Comment by marten-seemann** [comment]
How many connections are you handling? How many streams are open? What are the stream limits, both on your and on your peer's side?

This could be a totally expected behavior, or indicative of a memory leak. Without more information, we won't know which.

**Comment by nguyenduongnhj** [comment]
I have tried to measure the following information
 - 20k quic connection 
 - 70k stream open 
 - MaxIncomingStreams: 100000000
 - 
![Screenshot 2024-05-21 at 21 43 06](https://github.com/quic-go/quic-go/assets/44090434/f33f744a-29fc-41e8-bb3e-8559cb3934e2)

**Comment by nguyenduongnhj** [comment]
[profile (2).pb.gz](https://github.com/quic-go/quic-go/files/15391565/profile.2.pb.gz)
Go pprof profile. Can you give me some reasons why newStream is taking up a lot of resources so I can check again if my code is affecting it?

**Comment by marten-seemann** [comment]
You could try running your app with quic-go v0.42. We made some minor changes to the stream state machine in v0.43 and v0.44, maybe that introduced a bug.

To be honest, I'm not sure if the memory consumption you're seeing is that unusual though. You're handling a lot of streams after all. In your code, make sure to properly close both sides of the stream, and to not keep references to closed streams around, so that the stream can actually be garbage collected.

**Comment by nguyenduongnhj** [comment]
Thank you, it seems like the error was closing the stream without calling cancel write first. I changed the code to call cancel write before closing the stream and the memory problem was solved
