### ISSUE TITLE
Datagram no recent network activity error

### ISSUE THREAD

**Issue by Generalomosco** [quic-go/quic-go#4527]
Don't know why Quic connection aways get disconnected after some seconds to minute with "no recent network activity error" report while using Datagram along with Stream.

Even the KeepAlivePeriod is not helpful it just add latency to keep dead connection for long 
 ```
quic.Config{
			MaxIdleTimeout:  1500,
			KeepAlivePeriod: 1000,
			EnableDatagrams: true,
		}
```

**Comment by marten-seemann** [comment]
How do you expect us to respond this? "Oh yes, with this config, it's expected that your QUIC connection drops!"?

If you want help with your issue, you'll need to give us enough information to actually see what's going on.

**Comment by Generalomosco** [comment]
When a connection gets disconnected the other party waited till the default 30secs before getting noticing the other peer has disconnected when the MaxIdleTimeout is set to default or higher value.
I think no issue with that i think that is the logic. i leave the MaxIdleTimeout and KeepAlivePeriod to default values then using another method to track ungraceful disconnection, because the app need to tracks disconnected services at very low latency

**Comment by marten-seemann** [comment]
> When a connection gets disconnected the other party waited till the default 30secs before getting noticing the other peer has disconnected when the MaxIdleTimeout is set to default or higher value.

Not if you correctly configure [Stateless Resets](https://quic-go.net/docs/quic/transport/#stateless-reset).
