### ISSUE TITLE
In some cases I have turned off Stream on the server side, but OpenStreamSync on the client side is still blocked

### ISSUE THREAD

**Issue by ZYKJShadow** [quic-go/quic-go#4530]
My server code is as follows:
```go
for {
			stream, err := conn.AcceptStream(context.Background())
			if err != nil {
				logrus.Errorf("Failed to accept stream: %v", err)
				return err
			}

			s.Lock()
			s.streamCount++
			logrus.Infof("accept stream, remain count:%v", s.streamCount)
			s.Unlock()

			go func(stream quic.Stream) {
				defer func() {
					s.Lock()
					s.streamCount--
					logrus.Infof("close stream, remain count:%v", s.streamCount)
					s.Unlock()
				}()
				s.onHandleStream(stream)
			}(stream)

func (s *TUICServer) onHandleStream(stream quic.Stream) {
	var cmd protocol.Command
	err := cmd.Unmarshal(stream)
	if err != nil {
		logrus.Errorf("Failed to read command: %v", err)
		return
	}

	switch cmd.Type {
	case protocol.CmdAuthenticate:
		err = errors.New("bad command authenticate")
	case protocol.CmdConnect:
		err = s.connect(stream, cmd.Options.(*options.ConnectOptions))
	case protocol.CmdPacket:
		err = errors.New("bad command packet")
	case protocol.CmdDissociate:
		err = errors.New("bad command dissociate")
	case protocol.CmdHeartbeat:
		err = errors.New("bad command heartbeat")
	default:
		err = errors.New("unknown command type")
	}

	if err != nil && err != io.EOF && !errors.Is(err, net.ErrClosed) {
		logrus.Errorf("onHandleStream err:%v", err)
	}
}

func (s *TUICServer) connect(stream quic.Stream, opts *options.ConnectOptions) error {
	conn, err := s.tcp(stream, opts.Addr)
	if err != nil {
		return err
	}

	defer func() {
		_ = conn.Close()
		_ = stream.Close()
	}()

	errCh := make(chan error, 2)

	go func() {
		for {
			b := make([]byte, 1024*2)
			i, err := stream.Read(b[:])
			if err != nil {
				errCh <- err
				return
			}

			_, err = conn.Write(b[:i])
			if err != nil {
				errCh <- err
				return
			}
		}
	}()

	go func() {
		for {
			b := make([]byte, 1024*2)
			i, err := conn.Read(b[:])
			if err != nil {
				errCh <- err
				return
			}

			_, err = stream.Write(b[:i])
			if err != nil {
				errCh <- err
				return
			}
		}
	}()

	return <-errCh
}
```

The logs on the server are displayed as follows:【close stream, remain count:0】

The client code is as follows:
```go
func (c *TUICClient) onHandleTcpConnect(packet *channel.Packet) error {
	defer func() {
		_ = packet.Conn.Close()
	}()

	opts := &options.ConnectOptions{
		Addr: packet.Addr,
	}

	logrus.Infof("wait OpenStreamSync")

	ctx, cancel := context.WithDeadline(c.ctx, time.Now().Add(time.Second*3))
	defer cancel()

	stream, err := c.conn.OpenStreamSync(ctx)
	if err != nil {
		logrus.Errorf("open stream failed: %v", err)
		return err
	}

	defer func() {
		_ = stream.Close()
	}()

	logrus.Infof("OpenStreamSync success")

	cmd := protocol.Command{
		Version: protocol.VersionMajor,
		Type:    protocol.CmdConnect,
		Options: opts,
	}

	err = c.sendCommand(stream, cmd)
	if err != nil {
		logrus.Errorf("send command failed: %v", err)
		return err
	}

	conn := packet.Conn

	errCh := make(chan error, 2)
	go func() {
		for {
			b := make([]byte, 1024*2)
			i, err := stream.Read(b[:])
			if err != nil {
				errCh <- err
				return
			}

			_, err = conn.Write(b[:i])
			if err != nil {
				errCh <- err
				return
			}
		}
	}()

	go func() {
		for {
			b := make([]byte, 1024*2)
			i, err := conn.Read(b[:])
			if err != nil {
				errCh <- err
				return
			}

			_, err = stream.Write(b[:i])
			if err != nil {
				errCh <- err
				return
			}
		}
	}()

	return <-errCh
}
```

The client will be stuck in 【 wait OpenStreamSync 】

**Comment by marten-seemann** [comment]
Too much code, didn’t read. If you suspect a bug, please put in a tiny amount of effort and boil it down to a minimal example.

**Comment by ZYKJShadow** [comment]
Ok, thank you for your reply

```go
func (c *TUICClient) onHandleTcpConnect(packet *channel.Packet) error {
    defer packet.Conn.Close()

    ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
    defer cancel()

    stream, err := c.conn.OpenStreamSync(ctx)
    if err != nil {
        return err
    }
    defer stream.Close()

    errCh := make(chan error, 2)

    go func() {
        _, err := io.Copy(stream, packet.Conn)
        errCh <- err
    }()

    go func() {
        _, err := io.Copy(packet.Conn, stream)
        errCh <- err
    }()

    return <-errCh
}
```
```go
func (s *TUICServer) connect(stream quic.Stream, opts *options.ConnectOptions) error {
    conn, err := s.tcp(stream, opts.Addr)
    if err != nil {
        return err
    }
    defer conn.Close()
    defer stream.Close()

    errCh := make(chan error, 2)

    go func() {
        _, err := io.Copy(conn, stream)
        errCh <- err
    }()

    go func() {
        _, err := io.Copy(stream, conn)
        errCh <- err
    }()

    return <-errCh
}
```

**Comment by marten-seemann** [comment]
I still don’t see any problem.

**Comment by ZYKJShadow** [comment]
> I still don’t see any problem.

In some cases, the client will block OpenStreamSync even if both parties have called stream.Close()

**Comment by ZYKJShadow** [comment]
If I reopen a new quic.Connection, it works again, so it's not a server blocking problem, it's probably a stream counter problem

**Comment by ZYKJShadow** [comment]
Well, I've found a solution where I have to call the following code at the same time for it to work, which seems a little unintuitive, but by definition, just call Close() and it should all be closed

```go
stream.Close()
stream.CancelRead(quic.StreamErrorCode(0))
stream.CancelWrite(quic.StreamErrorCode(0))
```

**Comment by omarcosr** [comment]
> Bem, eu encontrei uma solução onde eu tenho que chamar o seguinte código ao mesmo tempo para que funcione, o que parece um pouco pouco intuitivo, mas por definição, basta chamar Close() e tudo deve ser fechado
> 
> stream.Close()
> stream.CancelRead(quic.StreamErrorCode(0))
> stream.CancelWrite(quic.StreamErrorCode(0))

This is still an issue, thanks for sharing the solution.

**Comment by marten-seemann** [comment]
> Well, I've found a solution where I have to call the following code at the same time for it to work, which seems a little unintuitive, but by definition, just call Close() and it should all be closed
> 
> stream.Close()
> stream.CancelRead(quic.StreamErrorCode(0))
> stream.CancelWrite(quic.StreamErrorCode(0))

This is incorrect. Do not use this.

**Comment by omarcosr** [comment]
> > Well, I've found a solution where I have to call the following code at the same time for it to work, which seems a little unintuitive, but by definition, just call Close() and it should all be closed
> > stream.Close()
> > stream.CancelRead(quic.StreamErrorCode(0))
> > stream.CancelWrite(quic.StreamErrorCode(0))
> 
> This is incorrect. Do not use this.

Could you clarify? In my tests, it was the only thing that prevented AcceptStream() from getting stuck.

**Comment by marten-seemann** [comment]
Please refer to the documentation. This has been asked 100 times, has been answered 100 times, and is explained in great detail there.

**Comment by ZYKJShadow** [comment]
In fact, the document has no appropriate solution in the scenario I described. Conversely, if this question can be asked 100 times, it indicates that the design is highly misleading, which is a problem that the author should consider

**Comment by marten-seemann** [comment]
> In fact, the document has no appropriate solution in the scenario I described.

It does: https://quic-go.net/docs/quic/streams/#states

<img width="800" height="999" alt="Image" src="https://github.com/user-attachments/assets/bbbf138f-11a2-4f54-a9a7-7dcf1a3aecdd" />

**Comment by ZYKJShadow** [comment]
I had already read the content of this part of the document when I raised this question. You can take a close look at the cases I shared above. They are not applicable to the situation of the document. I am already aware of the warning content. For my scenario, the ultimate solution is only the method I proposed above
