### ISSUE TITLE
gquic branch usage

### ISSUE THREAD

**Issue by RidoBluff** [quic-go/quic-go#4541]
Is the gquic branch still available now? I used this piece of code to send a gquic request of the q043 version, and received the following error message.
```
package main

import (
	"fmt"
	"net/http"
	"net/url"

	"github.com/lucas-clemente/quic-go"
	"github.com/lucas-clemente/quic-go/h2quic"
)

func main() {
	roundTripper := &h2quic.RoundTripper{
		QuicConfig: &quic.Config{Versions: []quic.VersionNumber{quic.VersionGQUIC43}},
	}

	defer roundTripper.Close()
	hclient := &http.Client{
		Transport: roundTripper,
	}

	url, _ := url.Parse("https://www.litespeedtech.com/")
	req := &http.Request{
		Method: http.MethodGet,
		URL:    url,
		Header: nil,
	}

	resp, err := hclient.Do(req)
	if err != nil {
		fmt.Println(err.Error())
	} else {
		fmt.Println(resp.StatusCode, resp.Proto)
	}
}
```
error message:
```
Get "https://www.litespeedtech.com/": HandshakeTimeout: Crypto handshake did not complete in time.
```
https://www.litespeedtech.com/ is a website that supports the gquic q043 version protocol, and the version of the quic-go package I use is github.com/lucas-clemente/quic-go v0.10.3-0.20190519135638-0810051757ce.

**Comment by marten-seemann** [comment]
Maybe it's still available in git, but frankly, I don't care about gQUIC at all. And neither should anyone else, it has loooong been deprecated.
