### ISSUE TITLE
http3: RoundTripper is caching dialErr since v0.43.0

### ISSUE THREAD

**Issue by nekohasekai** [quic-go/quic-go#4561]
Since da410a7, r.getClient is caching any errors from r.dial (specifically a custom Dial func) unless Close is called manually.

In my use case, it fails and always returns an error after the client's network environment changes, which is common on mobile devices.

**Comment by marten-seemann** [comment]
I haven't looked into this in detail yet, but this sounds like a bug. Want to contribute a fix?
