### ISSUE TITLE
Cancel retransmission of data when sending with quic Client 

### ISSUE THREAD

**Issue by gus3inov** [quic-go/quic-go#4564]
Hi! I am currently working with the quic-go and have encountered a scenario where I need to cancel the retransmission of data that is being sent by a QUIC client through a stream using `stream.Write`

In my application, there are situations where certain data becomes irrelevant or outdated after being written to the stream, and I want to ensure that such data is not retransmitted in case of packet loss or other transmission issues.

Is there a way to explicitly cancel the retransmission of data that has been written to a stream in quic-go? If so, could you provide an example on how to achieve this?

Thank you for your assistance!

**Comment by marten-seemann** [comment]
Yes, just use `CancelWrite`.
