### ISSUE TITLE
use `net.ErrClosed` for the server and the connection

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#4566]

**Comment by marten-seemann** [comment]
The connection errors already do this: https://github.com/quic-go/quic-go/blob/v0.45.0/internal/qerr/errors.go#L51-L53

**Comment by sukunrt** [comment]
Are all `TransportErrors` `net.ErrClosed`?

**Comment by marten-seemann** [comment]
Yes, the transport error has an equivalent implementation.
