### ISSUE TITLE
[Suggestion] multi-staging build in quic-go example Dockerfile

### ISSUE THREAD

**Issue by lkeix** [quic-go/quic-go#4567]
## Background

I encountered an issue when trying to build the `quic-go` example using the Docker build command:

```sh
$ docker build -t quic-go-example .
[+] Building 0.1s (4/4) FINISHED
 => [internal] load build definition from Dockerfile                                             0.0s
 => => transferring dockerfile: 178B                                                             0.0s
 => [internal] load .dockerignore                                                                0.0s
 => => transferring context: 2B                                                                  0.0s
 => [internal] load build context                                                                0.0s
 => => transferring context: 2B                                                                  0.0s
 => ERROR [1/1] ADD main /main                                                                   0.0s
------
 > [1/1] ADD main /main:
------
failed to compute cache key: "/main" not found: not found
```

## Concerns

The current Dockerfile implementation requires a pre-build step in the local environment, which complicates the process for users.

## Proposed Solution

I believe the example implementation should be straightforward to run, ideally with a single command like docker build -t quic-go-example .. This can be achieved by using multi-stage builds in the Dockerfile.

## Benefits

- Reduces the complexity for users, allowing them to build and run the example with a single command.
- Improves the user experience by providing a self-contained Docker build process.
- Decreases the likelihood of build errors related to missing files or incorrect paths.

I hope this suggestion is helpful, and I look forward to your feedback.

**Comment by marten-seemann** [comment]
I think we should just remove it. There's little value in having a Dockerfile here in the first place.
