### ISSUE TITLE
http3: Low Network Usage Efficiency with HTTP3 in quic-go

### ISSUE THREAD

**Issue by shivmohith** [quic-go/quic-go#4603]
We have been using quic-go with HTTP/3 to fetch files in parts from CloudFront. During our tests, we varied latencies (100ms & 1000ms) and bandwidths (50KBps, 1.25MBps, 3.75MBps). Latency and bandwidth were emulated using `tc` and `netem` tools.

Each part size was set to 5% of the bandwidth, and we fetched 20 parts in parallel by making 20 HTTP/3 Range Requests concurrently.

For every transfer, we captured the network traffic using tshark (v3.6.2). We then calculated the network usage efficiency as File size in bytes / Total bytes on the wire (both sent and received bytes).

Observed Results:

- For small file sizes (10KB, 100KB), we observed very low network usage efficiency (~65%) for low bandwidth (50KBps). This is understandable due to the high overhead relative to the small file size.
- For larger file sizes (1MB, 10MB, 100MB), we still observed ~65% efficiency at low bandwidths.
- For higher bandwidths, efficiency improved to ~85%-91%, potentially due to fewer HTTP/3 requests needed.

We still feel that 85% efficiency is low.

Questions:

1. Has anyone else performed similar testing? I found a related discussion [here](https://serverfault.com/questions/1160047/why-has-http3-more-overhead), but it does not use quic-go.
2. Is this level of efficiency expected with QUIC/HTTP/3?
3. Can you see any issues with our testing methodology?

Additional Context:
1-2 months ago, we conducted a similar calculation using qlog. We summed the length of all packet_sent and packet_received events and observed an efficiency of ~93%-95%. This might be because HTTP/3 qlog data was not accounted for, as it's not supported yet (an existing issue acknowledges this).

Let me know if you need any further details. Thanks!

PS: This might not be an issue with quic-go itself, but we are seeking insights from QUIC protocol experts to understand QUIC/HTTP/3 better.

**Comment by marten-seemann** [comment]
Framing overhead should be pretty low. On the QUIC layer, the largest overhead is probably the QUIC packet header (depending on the connection ID length). There's also overhead from STREAM frames, and occasionally other control frames (such as ACK and MAX_DATA frames, for example). Framing overhead on the HTTP/3 layer should be very low, as it is possible to use DATA frames with a large size.

If you want to dig into this deeper, it would probably make sense to classify the overhead you're seeing into (at least) the 4 categories I mentioned above.

**Comment by marten-seemann** [comment]
I forgot to mention another source of overhead you might be seeing, which is (spurious?) retransmissions.

Regarding methodology, going by qlogs is an option, but qlog wasn't really designed to capture the exact byte representation on the wire (e.g. how a varint was encoded), so you won't be able to get exact numbers. You can import an SSLKEYLOG file into Wireshark, allowing it to decrypt QUIC packet contents.

**Comment by shivmohith** [comment]
Yes, we were able to decrypt the QUIC packet contents in Wireshark. I was wondering how to identify retransmissions, I believe qlog does not emit an event for retransmission, is there a way to identify that?

**Comment by marten-seemann** [comment]
QUIC doesn't retransmit packets. It retransmit frames. That makes identifying retransmissions more challenging. For STREAM frames, you can check if the same stream offset was already sent before. If I remember correctly, Wireshark even does that for you. Obviously, this means that you need to record the pcap close to the server side (i.e. before the network segment where the packet loss happens).
