### ISSUE TITLE
failed to sufficiently increase receive buffer size

### ISSUE THREAD

**Issue by ayushs-2k4** [quic-go/quic-go#4604]
I am using macOS, using docker to host my API locally using cloudflare. However, this issue appears in logs
"failed to sufficiently increase receive buffer size (was: 208 kiB, wanted: 7168 kiB, got: 416 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details." 

On searching internet, I found linux specific solutions which I tries on Mac and as expected, they do not work. so how to increase buffer size on Mac?

**Comment by marten-seemann** [comment]
As you've already identified in https://github.com/quic-go/quic-go/issues/3801#issuecomment-2256548795, this is a known issue. Why open a new one, that you know is a duplicate. I consider this spam.
