### ISSUE TITLE
How to Retrieve QUIC Connection ID from HTTP/3 Client in quic-go

### ISSUE THREAD

**Issue by suggalat** [quic-go/quic-go#4606]
Hello, 
I am currently exploring QUIC for a side project, where I use the quic-go library to create a pool of HTTP/3 clients. My goal is to map each HTTP/3 client to its underlying QUIC connection ID. This mapping is essential for tracking connections easily using qlog or pcap capture.

However, I am unable to find a way to retrieve the QUIC connection ID from an HTTP/3 client. After creating an HTTP/3 client using the DialAddr, I need to access the connection ID of the underlying QUIC connection.

I would greatly appreciate guidance on how to achieve this, or if there is an existing method or workaround that I can use. If this functionality is not currently supported, it would be a valuable addition to the library for managing HTTP/3 connections more effectively.

Thanks
Sai Teja

**Comment by marten-seemann** [comment]
There are 2 ways:

The easiest way would be to implement your own `ConnectionIDGenerator` (it's a field on the `Config`), which would put your application in control of issuing new connection IDs.

Alternatively, you could implement some methods on the `ConnectionTracer`, and observe which connection ID is getting used.

Hope that helps!
