### ISSUE TITLE
http3: uploading a body without a predefined content-length cause the body to be skipped

### ISSUE THREAD

**Issue by Ousret** [quic-go/quic-go#4622]
Originally coming from https://github.com/traefik/traefik/issues/10185

We spotted an issue where streaming a body without a predefined content-length cause Traefik to ignore the body.
The question I am raising here is: "Is this a quic-go bug or rather a mistake in Traefik usage of quic-go? or worst, our implementation is faulty?"

Streaming a body using http3 without content-length should wait for the FIN bit in the given stream.

Please find attached the reproducer: [reproducer.zip](https://github.com/user-attachments/files/16429164/reproducer.zip)
Unfortunately I am unable to create a reproducer solely using (isolated) quic-go.

expected output:

![image](https://github.com/user-attachments/assets/0bef897d-b88c-4d41-b2a3-bdaba55194af)

regards,

**Comment by marten-seemann** [comment]
I'm not really sure how your setup looks like, but if a request don't have a Content-Length, you'll need to read until the end of the stream. Are you saying that quic-go is incorrectly setting a Content-Length of 0?

**Comment by Ousret** [comment]
OK, I will try to explain myself better.

First and foremost, I am not a go developer. I happen to have a QUIC/H3 implementation built for Python using aws-lc-rs crypto layer.

And for our CI, we happen to test our implementation against Traefik, which itself depend on quic-go to handle the QUIC layer, and of course the HTTP/3 state-machine on top of it. As far as I am concerned, we have zero evidence that the issue is coming from quic-go. We are seeking an expert to help us solve this case pending for a year now.

We noticed a bug in the following scenario:

POST /post (no content-length) --------> traefik http3 entrypoint ---(translated to http1.1)----> httpbin container

---

here are the header sent (excl special headers) on all cases

```
user-agent: niquests/3.7.2
accept-encoding: gzip, deflate
accept: */*
```

### HTTP/3

Here is what "httpbin" container receive in http1.1 behind a traefik router

```
'headers': {'Accept': ['*/*'],
             'Accept-Encoding': ['gzip, deflate'],
             'Content-Length': ['0'],
             'Host': ['httpbin.local:4443'],
             'User-Agent': ['niquests/3.7.2'],
             'X-Forwarded-For': ['172.24.0.1'],
             'X-Forwarded-Host': ['httpbin.local:4443'],
             'X-Forwarded-Port': ['4443'],
             'X-Forwarded-Proto': ['https'],
             'X-Forwarded-Server': ['912f105c82b3'],
             'X-Real-Ip': ['172.24.0.1']},
```

Here is what "httpbin" container receive in http1.1 behind a quiche router

```
'headers': {'Accept': '*/*',
             'Accept-Encoding': 'gzip, br',
             'Cdn-Loop': 'cloudflare',
             'Cf-Connecting-Ip': '2a01:cb05:8bdd:3000:5985:864e:89c8:82ac',
             'Cf-Ipcountry': 'FR',
             'Cf-Ray': '8aee5effbb1d6f42-FRA',
             'Cf-Visitor': '{"scheme":"https"}',
             'Connection': 'Keep-Alive',
             'Content-Length': '6',
             'Host': 'pie.dev',
             'User-Agent': 'niquests/3.7.2'},
```

### HTTP/2

Here is what "httpbin" container receive in http1.1 behind a traefik router

```
'headers': {'Accept': ['*/*'],
             'Accept-Encoding': ['gzip, deflate'],
             'Host': ['httpbin.local:4443'],
             'Transfer-Encoding': ['chunked'],
             'User-Agent': ['niquests/3.7.2'],
             'X-Forwarded-For': ['172.24.0.1'],
             'X-Forwarded-Host': ['httpbin.local:4443'],
             'X-Forwarded-Port': ['4443'],
             'X-Forwarded-Proto': ['https'],
             'X-Forwarded-Server': ['912f105c82b3'],
             'X-Real-Ip': ['172.24.0.1']},
```

Here is what "httpbin" container receive in http1.1 behind a quiche router

```
'headers': {'Accept': '*/*',
             'Accept-Encoding': 'gzip, br',
             'Cdn-Loop': 'cloudflare',
             'Cf-Connecting-Ip': '2a01:cb05:8bdd:3000:5985:864e:89c8:82ac',
             'Cf-Ipcountry': 'FR',
             'Cf-Ray': '8aee68b34a4d790f-FRA',
             'Cf-Visitor': '{"scheme":"https"}',
             'Connection': 'Keep-Alive',
             'Content-Length': '6',
             'Host': 'pie.dev',
             'User-Agent': 'niquests/3.7.2'},
```

---

Notes:

- Weirdly, in Traefik v2.10.4 and prior, you can set (even if illegal) "Content-Length: -1" and the bug would.. vanish.
  -  In v2.10.5+ sending any invalid content-length cause (for good reasons) a stream rst. `Stream 0 was reset by remote peer. Reason: 0x10e.`
- The best behavior is how Traefik handle incoming request using http2. It forward it immediately (latency reduced) using chunked http1.1 transfer.
- quiche behavior is consistent

---

I hope this would be sufficient to investigate if the issue is coming from quic-go or not.

regards,

**Comment by uniquefine** [comment]
Hi, we came across the same issue when using Caddy with a http3 listener as a reverse proxy before a go application.

If we send request with chunked body to the http3.Server.
The request doesn't have the "Content-Length" header set (the request is sent via the http client with http3.RoundTripper).

The handler receives a request `http.Request` object where `req.ContentLength == 0`. This is different from the behavior of the stdlib http.Server.

In our case this hit a condition in the Caddy reverse proxy (which is also present in the stdlib reverse proxy)
that does not forward the body if `req.ContentLength == 0` [here](https://github.com/golang/go/blob/36b45bca66d86020f0b4daf1f15b02921a8dad43/src/net/http/httputil/reverseproxy.go#L365-L367).


The http3.Server sets the ContentLength [here](https://github.com/quic-go/quic-go/blob/920bfb46af9db2ab23a94e54701b7a310ecc4928/http3/headers.go#L179). It should set it to -1 if no content length header is present.

**Comment by uniquefine** [comment]
Hi @marten-seemann, thanks for the quick fix. Yes. This resolves the issue in my reproducer :100:

**Comment by bt90** [comment]
> If we send request with chunked body to the http3.Server.

Isn't chunked transfer prohibited in HTTP/3?

**Comment by uniquefine** [comment]
True, a http3 client would not use chunked transfer encoding.
What I meant is that the body is not sent in a single DATA frame and the total body size is not known in advance.
