### ISSUE TITLE
some quic packet(client->server) no dcid and scid?

### ISSUE THREAD

**Issue by lastpepole** [quic-go/quic-go#4631]
@marten-seemann some quic packet(client->server) no dcid and scid?
the is an packet from client to server. 
**no dcid！！！**
![image](https://github.com/user-attachments/assets/4295b994-a7c7-4f26-b484-c5d1a72624e3)

**Comment by marten-seemann** [comment]
How about you go and read the RFC instead of spamming the issue tracker here?

**Comment by marten-seemann** [comment]
https://datatracker.ietf.org/doc/html/rfc9000#name-connection-id. Zero-length Connection IDs is what you're looking for.

**Comment by marten-seemann** [comment]
Again, please read the spec. You clearly haven't understood how connection IDs work.
