### ISSUE TITLE
Closing a bi-directional stream on both ends doesn't appear to close the stream

### ISSUE THREAD

**Issue by vitorpmoreira** [quic-go/quic-go#4632]
Hi!

**Note**: I'm not sure this is an issue in quic-go!

I've noticed a strange behaviour when closing bi-directional streams. I have a setup with a Peer and a Server, where the Peer establishes a connection to the Server. The Server then opens bi-directional streams with the following workflow:
1. Open stream
2. Write a message
3. Read a response
4. Close the stream

On the other end, the peer is accepting streams and has the following workflow:
1. Accept streams
2. Read the message
3. Write a response
4. Close the stream

I may have understood this wrong but closing a bi-directional stream will only close the Send part of it, while the Receive is untouched. Isn't the SendStream part of the Server, the ReceiveStream part of the Peer and vice-versa? Explicitly calling Close() on both ends shouldn't close the stream, making the peer available for a new one?

I have the maximum number of streams unset, which defaults to 100. While load testing the server, I noticed that after 100 messages, it was unable to open more streams. I was opening them with the Sync approach and, after changing to the non-sync version, I confirmed that the issue was due to "too many opened streams".
I also tried, on the Server, to call CancelRead() after Close() but it didn't help.

I'm I understanding this wrong, and I need to deal with the streams in a different way?

Thanks,
Vítor

**Comment by vitorpmoreira** [comment]
Okay, I got it working by cancelling the Read part and closing the Stream, on both the Peer and the Server. Is this the expected behavior?

**Comment by marten-seemann** [comment]
No, closing the stream from both sides is sufficient, you don't need to cancel the stream.

This exact same question has been asked 100 times here.
It's explained in RFC 9000. And it's explained in great detail in the documentation: https://quic-go.net/docs/quic/streams/#states.

**Comment by vitorpmoreira** [comment]
Thanks for your reply.

First of all, I read most of the documentation but failed to go more in-depth on the closed issues to find similar ones. My sincere apologies.

Regarding closing the streams, what I was missing was reading the `io.EOF` frame, which was causing the streams to hang. Closing the stream and reading the `io.EOF` is enough and it is the proper way to deal with the stream's lifecycle.
Thank you!

Kind regards,
Vítor

**Comment by marten-seemann** [comment]
> First of all, I read most of the documentation but failed to go more in-depth on the closed issues to find similar ones. My sincere apologies.

@vitorpmoreira No worries. Do you have any suggestions on how we can make the documentation more helpful? This has come up so many times, and I'd love to clarify the documentation so it's clear for new users.

**Comment by vitorpmoreira** [comment]
I'd probably add a note to the QUIC stream's page, indicating that one must read the `io.EOF` in order to finish the process of closing a stream. I double checked the Bidirectional Streams part and a good place would be to add this topic to the Warning Note that is already there.
However, if I'm not mistaken, this also applies to uni streams, right? Calling the `Close` will require the other end to read the frame. Since there's an **Opening Streams** section, how about a "Closing Streams"?
