### ISSUE TITLE
File transfer using stream hangs

### ISSUE THREAD

**Issue by chocolatkey** [quic-go/quic-go#4636]
I am attempting to build a file transfer system using QUIC, and managed to get quite far, however I am having an issue that is not consistently reproducible. When I am transferring a ~270MB file through a bidirectional stream, the write from client to server will sometimes complete, and sometimes hang at random points in the process. I am copying using `io.Copy` from a file to a stream on the client side, and from a stream to a file on the server side. Here is an example, with a lot of logging/debugging added:

client:
```go
// ...
s.log.Debug("Waiting for OK to start")
buf := make([]byte, 1)
_, err = io.ReadFull(stream, buf)
if err != nil {
	inspect.Error(slog.Default(), err)
	return errors.Wrap(err, "failed awaiting OK to start")
}
if buf[0] != 0x0 {
	return errors.New("received strange response for transfer start")
}

s.log.Debug("sending file", path, "...")
sendFile, err := os.Open(path)
if err != nil {
	return errors.Wrap(err, "failed opening file for transfer")
}
defer sendFile.Close()

sbuf := make([]byte, 32*1024) // 32*1024 is the Go default
s.log.Debug("copying...")

pw := utils.NewProgressWriter(stream)
pr := utils.NewProgressReader(sendFile)
done := make(chan bool)
go func() {
	repeat := 0
	curr := int64(0)
	for {
		select {
		case <-done:
			return
		default:
			ww := pw.N()
			if ww != curr {
				curr = ww
				repeat = 0
			} else {
				repeat++
			}
			if repeat > 20 {
				s.log.Debug("no progress for 10 seconds, closing")
				stream.CancelWrite(0x999)
				stream.CancelRead(0x999)
				stream.Close()
				return
			}

			time.Sleep(1 * time.Second)
			fmt.Printf("Read %d bytes, sent %d bytes\n", pr.N(), ww)
		}
	}
}()
n, err := io.CopyBuffer(pw, pr, sbuf)
if err != nil {
	s.log.Debug("copy error", "err", err.Error(), slog.Int64("bytes", n))
	inspect.Error(slog.Default(), err)
	done <- true
	s.log.Debug("done ;(")
	return err
}
done <- true
s.log.Debug(fmt.Sprintf("Sent %d bytes\n", n))
```

server:
```go
// Let the client know we're ready
_, err = stream.Write([]byte{0x0})
if err != nil {
	return errors.Wrap(err, "failed writing ready signal")
}

// Create new file
path := fmt.Sprintf("receive_%s_%s", transferId, file.FileName)
newFile, err := os.Create(path)
if err != nil {
	return errors.Wrap(err, "failed creating file for receiving")
}
defer newFile.Close()

start := time.Now()
log.Info("receiving file", slog.Time("started_at", start))

pw := utils.NewProgressWriter(newFile)
pr := utils.NewProgressReader(stream)
done := make(chan bool)
go func() {
	for {
		select {
		case <-done:
			return
		default:
			time.Sleep(1 * time.Second)
			fmt.Printf("Received %d bytes, wrote %d bytes\n", pr.N(), pw.N())
		}
	}
}()
b, err := io.CopyN(pw, pr, int64(file.FileSize))
if err != nil {
	log.Debug("copy error", "err", err.Error(), slog.Int64("bytes", b))
	done <- true
	return errors.Wrap(err, "failed copying file data from stream to file")
}
done <- true
now := time.Now()
log.Info(
	"received file",
	slog.Time("finished_at", now),
	slog.Float64("duration", time.Since(start).Seconds()),
	slog.Int64("size", b),
)
```

Here is a file with the complete logs (both .sqlog and console output) included: [quick-transfer-fail.zip](https://github.com/user-attachments/files/16652970/quick-transfer-fail.zip)

The logging that I added to track sent/received bytes seems to indicate that, in this example, the server wasn't able to receive more than 5320449 bytes before getting stuck (`Received 5320449 bytes, wrote 5320449 bytes`), and the client only sent 6029312 bytes before getting stuck (`Read 6062080 bytes, sent 6029312 bytes`).
I've tested this on both a localhost --> localhost transfer, and a remote transfer, with the same problem, so it's not a network problem.
I've checked the logs and visualizer, and it looks to me like the transfer just stops despite keepalive packets continuing to get sent. Maybe I'm missing something obvious? Please let me know if more info is needed

**Comment by marten-seemann** [comment]
The qlog looks fine. The FIN is transmitted, and the connection is shut down properly.
