### ISSUE TITLE
http3 RoundTripper does not support Close during Read, inconsistent with http/http2

### ISSUE THREAD

**Issue by mmmray** [quic-go/quic-go#4637]
*copied from https://github.com/quic-go/quic-go/issues/2143#issuecomment-2301652942*

Both h1/h2 transports handle Close+Read without crashing, but h3 does not. This inconsistency makes it difficult to handle all HTTP versions transparently in application code that already relies on this behavior. While not explicitly documented, `net.TCPConn` and some other networking APIs also support this usecase.

The workaround I have so far is to wrap `response.Body` in this struct:

```go

type h3Body struct {
	inner  io.ReadCloser
	lock   sync.Mutex
	cancel context.CancelFunc
}

func (c *h3Body) Read(b []byte) (int, error) {
	c.lock.Lock()
	defer c.lock.Unlock()

	return c.inner.Read(b)
}

func (c *h3Body) Close() error {
	c.cancel()

	c.lock.Lock()
	defer c.lock.Unlock()

	return c.inner.Close()
}

ctx, ctxCancel := context.WithCancel(context.Background())
req, err := http.NewRequestWithContext(ctx, ...)

...

response, err := client.Do(req)

...

body := h3Body { inner: response.Body, cancel: ctxCancel }
```

But clearly this comes with some overhead on Read. I can also only `cancel()` without `inner.Close` to avoid the mutex, but that seems like it might cause more bugs.

**Comment by marten-seemann** [comment]
Your workaround code is completely useless for debugging this issue. Instead of posting your workaround, please post a **minimal** example that triggers the alleged bug.

**Comment by mmmray** [comment]
@marten-seemann there is nothing to debug, and this is not a bug. This was an explicit API decision made by you 5 years ago, and I'd like you to reconsider that decision for the reasons stated above. This issue is an exact duplicate of https://github.com/quic-go/quic-go/issues/2143. Nevertheless, here is some demo code that triggers the issue for me:

```go
package main

import (
	"net/http"
    "sync"
    "context"
    "fmt"
    "io"
	"github.com/quic-go/quic-go/http3"
)
func main() {
	roundTripper := &http3.RoundTripper{}
	defer roundTripper.Close()
	hclient := &http.Client{
		Transport: roundTripper,
	}

    var wg sync.WaitGroup
    wg.Add(10000)

    for i := 0; i < 10000; i++ {
        go func() {
            req, err := http.NewRequestWithContext(
                context.Background(),
                "GET",
                // any URL with long-running response, may just be idle, slow or a large file
                "https://watertower.lol/test/cdntest/chunked-pong",
                nil,
            )

            if err != nil {
                panic(err)
            }

            response, err := hclient.Do(req)
            if err != nil {
                panic(err)
            }

            go func() {
                response.Body.Close()
            }()

            io.Copy(io.Discard, response.Body)
            fmt.Println("response: ", response)

            wg.Done()
        }()
    }

    wg.Wait()
}

```

**Comment by marten-seemann** [comment]
Well, as I said back then, it is not expected that `Read` and `Close` are called concurrently, so technically this is not a bug.

I'd be open to reviewing a PR that resolves the panic though.

**Comment by marten-seemann** [comment]
Closing this issue, since #4638 was closed.
