### ISSUE TITLE
Incorrect handling of the idle timeout parameter in v0.46.0

### ISSUE THREAD

**Issue by Blankwonder** [quic-go/quic-go#4644]
According to RFC 9000, the max_idle_timeout parameter of transport parameters is used to negotiate the idle timeout mechanism's duration. However, when it is set to 0, it indicates that idle timeout is not enabled.

> max_idle_timeout (0x01):  The maximum idle timeout is a value in milliseconds that is encoded as an integer; see (Section 10.1).       Idle timeout is disabled when both endpoints omit this transport parameter or specify a value of 0.

However, in version v0.46.0, if max_idle_timeout is set to 0 by client, it actually sets the idle timer time to 0, causing the connection to be immediately deemed idle and closed after the first stream is closed.

**Comment by marten-seemann** [comment]
This is not correct. The idle timeout is always set to at least the value of the local idle timeout:
https://github.com/quic-go/quic-go/blob/920bfb46af9db2ab23a94e54701b7a310ecc4928/connection.go#L1768-L1771

This satisfies the requirement to take the minimum of both peers' advertised idle timeout values.

The only case where this logic would fail is when the local idle timeout is set to 0, which is not possible by definition of `Config.MaxIdleTimeout`: 
https://github.com/quic-go/quic-go/blob/920bfb46af9db2ab23a94e54701b7a310ecc4928/interface.go#L279-L280

**Comment by Blankwonder** [comment]
When `s.config.MaxIdleTimeout` is set to 30 (non-zero) and `params.MaxIdleTimeout` is 0, `s.idleTimeout` will be set to 0 according to the code.

**Comment by marten-seemann** [comment]
Oops, you’re right.

**Comment by Blankwonder** [comment]
Sorry. There are some errors in my previous comment. The RFC states that the mechanism should be closed only when **both** parties specify max_idle_timeout as 0. If only one party specifies it as 0, idle timeout should still be enabled and based on the value specified by the other party.

**Comment by marten-seemann** [comment]
Fix in https://github.com/quic-go/quic-go/pull/4666. Would appreciate a quick code review 🙏
