### ISSUE TITLE
Support Android

### ISSUE THREAD

**Issue by cpeliciari** [quic-go/quic-go#4678]
Hello everyone,

I'm working on an application using libp2p. I'm receiving the following message:

``` 
failed to sufficiently increase receive buffer size (was: 160 kiB, wanted: 7168 kiB, got: 2929 kiB). See https://github.com/quic-go/quic-go/wiki/UDP-Buffer-Sizes for details.
```

Is there anything that can be done on Android?

**Comment by marten-seemann** [comment]
It's all described on the linked page.

That said, running a p2p stack on a mobile device doesn't seem like a good idea...
