### ISSUE TITLE
Getting reports of HTTP/3 broken in Safari/iOS 18

### ISSUE THREAD

**Issue by mholt** [quic-go/quic-go#4679]
We're getting reports of HTTP/3 connection errors in Safari on iOS 18. I don't have this to test, but the only details I have so far are that the error is "connection reset" or "They just randomly timeout or only load half of the page content":

https://caddy.community/t/caddy-http-3-quic-and-the-new-apple-software-today/25660

I'll try to find out more, and I have no idea if this is something wrong with Safari/iOS, Caddy, or some quirk in quic-go. But I wanted to open this issue to track it.

**Comment by marten-seemann** [comment]
Thanks for the report. I'm on it.

Struggling to reproduce it though. On macOS, Safari refuses to use H3 in the first place. Next up: testing on iOS devices.

**Comment by marten-seemann** [comment]
According to the discussion on caddy.community, it looks like this has been resolved by updating quic-go to the most recent version.
