### ISSUE TITLE
About Quic's traffic proxy

### ISSUE THREAD

**Issue by peakedshout** [quic-go/quic-go#4684]
I am currently implementing a traffic forwarding function, and I can forward UDP packets, but when I use Quic, the TLS verification fails:
```
panic: CRYPTO_ERROR 0x12a (local): tls: failed to verify certificate: x509: certificate is valid for 1.0.0.1, 1.1.1.1, 162.159.36.1, 162.159.46.1, 2606:4700:4700::1001, 2606:4700:4700: :1111, 2606:4700:4700::64, 2606:4700:4700::6400, not ::
```
Although it is possible to disable this check for forwarding data by 'InsecureSkipVerify: true', it leads to more security issues.
It seems that I don't understand the quic properly, I would like to know a scheme that works to forward traffic. (TCP traffic forwarding is simple, but it seems that UDP forwarding alone cannot complete QUIC traffic forwarding.)

**Comment by marten-seemann** [comment]
This is not an issue with quic-go.
