### ISSUE TITLE
failed to increase buffer.. etc.. why such a low recommendation?

### ISSUE THREAD

**Issue by bcookatpcsd** [quic-go/quic-go#4686]
Stood up a baremetal i5 FreeBSD machine for running DNS/DHCP/tailscale/wiki for a medium sized network.. 

Adguardhome gave it's "wanted: 7168 kiB, got 41 kiB' in the logs.. and it gave the wiki link.. 

Googling led me down the rabbit hole of fbsd multicasting issues solved/changed by increasing the maxsockbuf sysctl and calomel's site.. 

(not being an OS programmer..) Is there a reason why to not (suggest) increasing maxsockbuf beyond 8M or 16M or 32M? 

I couldn't find a way to 'read usage' of the 16M buffer size I had set.. 

How would one determine (short of hoping a developer threw in an errlog statement) if the value is appropriate for their situation?

Thank you in advance.

**Comment by marten-seemann** [comment]
I haven't seen significant performance benefits beyond 8 MB, but I only have limited data. If you have any measurements that show improvements beyond that size, please share your data!
