### ISSUE TITLE
StreamFrame does not put back

### ISSUE THREAD

**Issue by nguyenduongnhj** [quic-go/quic-go#4703]
Hello today I have a problem counting StreamFrame usage, even though all connections are closed, the StreamFrame is not returned to the pool. I waited another hour but still no put back  streamframe to pool
quic-go version 0.48.0
`
func GetStreamFrame() *StreamFrame {
	f := pool.Get().(*StreamFrame)
	log.Println("GET BUFF", atomic.AddInt32(&total, 1))
	return f
}

func putStreamFrame(f *StreamFrame) {
	if !f.fromPool {
		return
	}
	if protocol.ByteCount(cap(f.Data)) != protocol.MaxPacketBufferSize {
		panic("wire.PutStreamFrame called with packet of wrong size!")
	}
	pool.Put(f)
	log.Println("PUT BUFF", atomic.AddInt32(&total, -1))

}
`

2024/10/18 15:29:09 GET BUFF 677
2024/10/18 15:29:09 GET BUFF 678
2024/10/18 15:29:09 GET BUFF 673
2024/10/18 15:29:09 PUT BUFF 677
2024/10/18 15:29:09 PUT BUFF 676
2024/10/18 15:29:09 PUT BUFF 675
2024/10/18 15:29:09 PUT BUFF 674
2024/10/18 15:29:09 PUT BUFF 673
2024/10/18 15:29:09 PUT BUFF 672
2024/10/18 15:29:09 PUT BUFF 671
2024/10/18 15:29:09 PUT BUFF 670
2024/10/18 15:29:09 PUT BUFF 669
2024/10/18 15:29:09 PUT BUFF 668
2024/10/18 15:29:09 PUT BUFF 667
2024/10/18 15:29:09 PUT BUFF 666
2024/10/18 15:29:09 PUT BUFF 665
2024/10/18 15:29:09 PUT BUFF 664

**Comment by marten-seemann** [comment]
So what? It's not a requirement to put it back.
