### ISSUE TITLE
Packet Retransmission through Stream

### ISSUE THREAD

**Issue by gus3inov** [quic-go/quic-go#4709]
I have a QUIC client where a new stream is created for each packet, and the data is written to that stream:

```go
func (c *QUICClient) write(msg []byte) error {
	// Open a new stream for each patch
	ctx := context.Background()
	stream, err := c.conn.OpenStreamSync(ctx)
	if err != nil {
		loggerClient.Info("Failed to open stream", "err", err)

		return ErrOpenStream
	}
	defer stream.Close()

	err = stream.SetWriteDeadline(time.Now().Add(c.writeTimeout))
	if err != nil {
		loggerClient.Error("Failed to set write deadline", "err", err)
		return ErrOpenStream
	}

	_, err = stream.Write(msg)
	if err != nil {
		loggerClient.Error("Failed to write to stream", "err", err)
		return ErrSendPatch
	}

	return nil
}
```

I'm not entirely sure what will happen if a packet isn't delivered on the first attempt. Will the stream attempt to resend the packet to the server, or do I need to open a single stream and implement my own retry mechanism for packets?

Which approach is more appropriate here:
- One stream per packet
- One stream for all packets, implementing my own packet retry mechanism?

What should be done if packets need to be sent frequently and it's crucial to ensure reliable delivery? How can I guarantee that the packets are always delivered successfully in this case?

**Comment by marten-seemann** [comment]
First of all, you can't control how the QUIC stack packetizes the stream data. `msg` might get sent out in a single packet, split across multiple packets, or coalesced into a single packet together with data from other streams.

If the packet is lost, you don't have to do anything. The QUIC stack will retransmit all STREAM frames contained in packets that were lost, unless the stream was canceled in the mean time.

**Comment by gus3inov** [comment]
Got it!
> unless the stream was canceled in the mean time

Does this mean that if I call `stream.Write(msg)` and then `stream.Close()`, it will cancel the stream, and if the packet is lost, QUIC won't retransmit it because the stream is closed?

**Comment by marten-seemann** [comment]
Nope, this applies to `CancelWrite` / `CancelRead`.

Data sent on streams that you have `Close`d will be retransmitted.
