### ISSUE TITLE
Efficient Handling of High-Frequency Patches in QUIC Client-Server Communication

### ISSUE THREAD

**Issue by gus3inov** [quic-go/quic-go#4721]
I have a system where QUIC clients and servers are implemented with this library.
Each client sends patches to the server at a high frequency — approximately 4 patches per second per client.
Let's assume there are about 100 clients in total.

I'm considering two approaches for sending patches from the clients to the server:
1. **Stream per Patch:**
   - Each client creates a new QUIC stream for every patch it sends.
   - This results in 4 streams per second per client.
   - The server accepts each stream and handles the patches individually.

2. **One Stream per Client:**
   - Each client establishes a single persistent QUIC stream.
   - All patches are sent over this one stream sequentially.
   - The server handles the incoming patches from each client's stream over time.

**Question**: Is stream creation in QUIC lightweight enough to handle the overhead of creating multiple streams per second per client, or would it be more efficient in this case to use a single stream per client to send multiple patches?

**Comment by marten-seemann** [comment]
Yes, streams in QUIC are very lightweight, and regarding bytes sent on the wire, there's practically no difference between the two approaches.

As general principles:
* If messages should be delivered in-order, use a single stream.
* Conversely, if you don't care about ordering between messages, use multiple streams. If this is the case, this removes head-of-line blocking, and can speed up your application when packet loss happens.
* As a third option, if you also don't care about reliable delivery of messages, you can use DATAGRAM frames.
