### ISSUE TITLE
http3: set Content-Length to 0 for GET and HEAD requests

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#4722]
I'm not sure if I'd design that way it if I was designing an HTTP package from scratch, but this is how Go's HTTP/1.1 and HTTP/2 implementation behave, apparently. Behaving differently can lead to subtle bugs, as @WeidiDeng has been debugging in https://github.com/caddyserver/caddy/issues/6678#issuecomment-2472562439.

Open question: How would we detect a misbehaving client that sends a request body for HEAD and GET requests? Do we need to? How does this work on HTTP/1.1 and HTTP/2?

**Comment by mohammed90** [comment]
Last I remember GET requests with body are simply unspecified/undefined in the spec, i.e. not forbidden, but not explicitly allowed either. I've seen at least one bank system that expects a body with GET.

**Comment by marten-seemann** [comment]
After discussion this with a few people at the HTTP Workshop, here's my understanding of the situation:

According to the specification, GET and HEAD requests with a body are **unspecified**. That doesn't mean that they're invalid though, and from the RFC that @mohammed90 cited, if client and server agree on the semantics, it is valid to send a request body.

As such, it would be incorrect to set the Content-Length to 0.

The reason that Caddy is seeing this bug is that in HTTP/2 there's a STREAM_ENDED flag on the HEADERS frame, allowing the H2 implementation to set the `http.Request.ContentLength`, even if no Content-Length header is set on a GET request.

**Comment by WeidiDeng** [comment]
I tested using stdlib http servers, and indeed, both h1 and h2 supports request bodies for `GET` and `HEAD` requests. Forgot to put the findings here. 

The only restrictions regarding request and response bodies seem to be only response bodies for specific status codes.
