### ISSUE TITLE
Can we specify custom transport parameters?

### ISSUE THREAD

**Issue by Diniboy1123** [quic-go/quic-go#4772]
Hi,

This would be a feature request as I haven't found a way to do this with the library yet. I would like to replicate the way how Google Chrome connects from within go. In wireshark I can see that Chrome sets certain fields like `google_version` or `google_connection_options` similar to how its set here in this go project: https://github.com/gaukas/clienthellod/blob/master/quic_transport_parameters_test.go#L55

Is there a way to specify custom QTPIDs here as well somehow? If not, is it planned?

Thanks

**Comment by Diniboy1123** [comment]
Nvm, it seems to be related to the stdlib tls library and unrelated to this project.

**Comment by marten-seemann** [comment]
QUIC transport parameters are indeed created by quic-go, not by crypto/tls. However, we don't plan to expose any hooks to allow applications to set custom transport parameters, others than the existing testing hooks (which thanks to `internal` can't be used externally):
https://github.com/quic-go/quic-go/blob/468cea250d71dd135d109177732c175f390319ae/internal/wire/transport_parameters.go#L18-L22
