### ISSUE TITLE
Question: what is `now` param used for in `UpdateRTT`?

### ISSUE THREAD

**Issue by hedwigz** [quic-go/quic-go#4777]
It seems to be unused. 
https://github.com/quic-go/quic-go/blob/95998056d5d2d4686a7ce810adc6757887f1068e/internal/utils/rtt_stats.go#L61-L91

**Comment by marten-seemann** [comment]
Probably a leftover from an earlier implementation of the method. It can now be removed, see #4780. Thanks!
