### ISSUE TITLE
send stream doesn't account for lost RESET_STREAM frames

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#4803]
The stream has a `numOutstandingFrames` counter, and only considers itself closed once this counter hits 0, and a few other conditions are met: for example the stream needs to have sent the FIN, or have been reset.

When a STREAM frames is lost, this number is reduced (which is correct):
https://github.com/quic-go/quic-go/blob/f6e7789854f034a592ba6f12bfbd84b639ef06e9/send_stream.go#L556-L565

However, when a RESET_STREAM frame is lost, it's not:
https://github.com/quic-go/quic-go/blob/f6e7789854f034a592ba6f12bfbd84b639ef06e9/send_stream.go#L592-L597

I suspect that this is incorrect. The effect is that the stream never marks itself for garbage collection, and we don't increase the peer's stream credit when the stream it closed. This might be the cause for some connection stalls that have been report, first and foremost #4712.

**Comment by Wondertan** [comment]
How STREAM_RESET packet might get lost and hoe can we detect that? I presume there is no ACKing for this packet

**Comment by marten-seemann** [comment]
Yes, and there would also be a [`packet_lost`](https://datatracker.ietf.org/doc/html/draft-ietf-quic-qlog-quic-events#name-packet_lost) event in the qlog for that packet.
