### ISSUE TITLE
handle closed clients in http3.RoundTripper

### ISSUE THREAD

**Issue by marten-seemann** [quic-go/quic-go#765]
When a QUIC connection is closed (e.g. due to an idle timeout), subsequent `RoundTrip`calls in the  `h2quic.RoundTripper` will fail.

**Comment by marten-seemann** [comment]
Since this came up a couple of times, but I don't have the time to fix this issue myself at the moment:

There two cases for closed connections here: The connection could be closed regularly, or time out, or receive a Public Reset. In these cases, `RoundTrip` should re-dial the connection. If the connection was closed as a result of a failed version negotiation, failed crypto negotiation or a general protocol violation, there's no need to try again.

**Comment by heri16** [comment]
@marten-seemann could you layout a high-level design that makes sense since the approaches of both PR #933 and PR #1095 has been rejected. With a design specification, it would be easier to write a PR that would be acceptable.

**Comment by marten-seemann** [comment]
I'll take care of it.

**Comment by fbzhong** [comment]
@marten-seemann can you write down high level design of this? I encounter this issue and want to fix.

**Comment by marten-seemann** [comment]
There should be similar code in the standard library HTTP/2 package.

**Comment by gabrielperezs** [comment]
Hi. Here is a proposal to detect "done" clients and force it to create a new one: https://github.com/lucas-clemente/quic-go/compare/master...gabrielperezs:reuse-roundTripper-if-client-fails

I didn't send a PR because I'm not sure about one of the unit tests that returns an error:

```
• Failure [0.001 seconds]
RoundTripper
/go/src/github.com/lucas-clemente/quic-go/http3/roundtrip_test.go:60
  dialing hosts
  /go/src/github.com/lucas-clemente/quic-go/http3/roundtrip_test.go:79
    reuses existing clients [It]
    /go/src/github.com/lucas-clemente/quic-go/http3/roundtrip_test.go:136

    Unexpected call to *mockquic.MockEarlySession.Context([]) at /go/src/github.com/lucas-clemente/quic-go/internal/mocks/quic/early_session.go:101 because: there are no expected calls of the method "Context" for that receiver

    /go/src/github.com/lucas-clemente/quic-go/internal/mocks/quic/early_session.go:101
```

I suppose that if the changes linked before are ok, then this test can be updated because it is not an issue any more?

Let me know so I can send the PR with the mentioned changes.

**Comment by spacewander** [comment]
Is there any updates?

**Comment by kaiyuhou** [comment]
Based on my observation, this is no longer a problem in v0.20.1. (v0.19.3 still has this problem.)

**Comment by marten-seemann** [comment]
I don’t think we made any changes in v0.20 to resolve this issue.

**Comment by kaiyuhou** [comment]
Just carefully tested. Yes, it's still an issue in v0.20.1.

**Comment by rs** [comment]
Please see my PR. It's far from perfect, but makes the h3 client usable.

**Comment by ayanamist** [comment]
Surprise found this serious bug, which make quic-go is totally unusable in production after quic server restarts, is there any planned progress to solve this issue? If no, can you pin this issue up so that other people know this issue?

**Comment by koalabearguo** [comment]
I meet the same issue，is there any progress or fix please?
